//! Codebase Compiler — compile all project files into a single document for AI consumption.
//!
//! Walks a directory tree, collects all text files, and produces a single Markdown
//! document containing a directory tree and complete file contents. Designed for
//! feeding entire codebases to AI agents in one shot.

const std = @import("std");

const skip_dirs = [_][]const u8{
    "zig-cache",
    "zig-out",
    ".zig-cache",
    ".git",
    ".github",
    "target",
    "node_modules",
    "__pycache__",
    ".svelte-kit",
    ".next",
    "dist",
    "venv",
    ".venv",
    ".egg-info",
    "build",
    ".build",
    "vendor",
    ".terraform",
    "codebase_compilations",
};

const binary_extensions = [_][]const u8{
    ".png",     ".jpg",    ".jpeg",   ".gif",     ".bmp",     ".ico",
    ".webp",    ".svg",    ".mp3",    ".mp4",     ".avi",     ".mov",
    ".wav",     ".flac",   ".ogg",    ".zip",     ".tar",     ".gz",
    ".bz2",     ".7z",     ".xz",     ".rar",     ".exe",     ".dll",
    ".so",      ".dylib",  ".o",      ".a",       ".lib",     ".obj",
    ".bin",     ".dat",    ".db",     ".sqlite",  ".sqlite3", ".wasm",
    ".pdf",     ".doc",    ".docx",   ".xls",     ".xlsx",    ".ppt",
    ".pptx",    ".ttf",    ".otf",    ".woff",    ".woff2",   ".eot",
    ".pyc",     ".pyo",    ".class",  ".jar",     ".iso",     ".img",
    ".dmg",     ".deb",    ".rpm",    ".textClipping",
};

const max_file_size: usize = 5 * 1024 * 1024; // 5 MB per file

const TreeNode = struct {
    name: []const u8,
    children: std.ArrayListUnmanaged(*TreeNode),
    is_file: bool,
};

pub fn compileCodebase(
    allocator: std.mem.Allocator,
    io: std.Io,
    target_path: []const u8,
    project_name: []const u8,
) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;

    // Collect all text files
    var rel_paths: std.ArrayListUnmanaged([]const u8) = .empty;
    var full_paths: std.ArrayListUnmanaged([]const u8) = .empty;

    var dir = std.Io.Dir.cwd().openDir(io, target_path, .{ .iterate = true }) catch {
        try appendStr(allocator, &buf, "Error: could not open directory\n");
        return buf.items;
    };
    defer dir.close(io);

    var walker = dir.walk(allocator) catch {
        try appendStr(allocator, &buf, "Error: could not walk directory\n");
        return buf.items;
    };
    defer walker.deinit();

    while (walker.next(io) catch null) |entry| {
        if (entry.kind != .file) continue;
        if (shouldSkipPath(entry.path)) continue;
        if (shouldSkipFile(entry.basename)) continue;

        const rel = try allocator.dupe(u8, entry.path);
        const full = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ target_path, entry.path });
        try rel_paths.append(allocator, rel);
        try full_paths.append(allocator, full);
    }

    // Sort by relative path (index-based to keep arrays in sync)
    const indices = try allocator.alloc(usize, rel_paths.items.len);
    for (indices, 0..) |*idx, i| idx.* = i;

    std.mem.sortUnstable(usize, indices, rel_paths.items, struct {
        fn lessThan(paths: []const []const u8, a: usize, b: usize) bool {
            return std.mem.order(u8, paths[a], paths[b]) == .lt;
        }
    }.lessThan);

    var sorted_rel = try allocator.alloc([]const u8, indices.len);
    var sorted_full = try allocator.alloc([]const u8, indices.len);
    for (indices, 0..) |idx, i| {
        sorted_rel[i] = rel_paths.items[idx];
        sorted_full[i] = full_paths.items[idx];
    }

    // === Header ===
    try appendFmt(allocator, &buf, "# Codebase Compilation: {s}\n\n", .{project_name});
    try appendStr(allocator, &buf, "> This is an automated codebase compilation generated by **zig-lens**.\n");
    try appendStr(allocator, &buf, "> All source files are included below for AI consumption.\n\n");

    // === Directory Tree ===
    try appendStr(allocator, &buf, "## Directory Tree\n\n```\n");
    try writeTree(allocator, &buf, sorted_rel, project_name);
    try appendStr(allocator, &buf, "```\n\n");

    // === File Contents ===
    try appendStr(allocator, &buf, "## Files\n\n");

    var total_bytes: usize = 0;
    var files_included: usize = 0;

    for (sorted_rel, sorted_full) |rel, full| {
        const content = readFileContent(io, allocator, full) catch {
            try appendFmt(allocator, &buf, "### `{s}`\n\n", .{rel});
            try appendStr(allocator, &buf, "*[Error reading file]*\n\n");
            continue;
        };
        defer allocator.free(content);

        // Skip empty files
        if (content.len == 0) continue;

        try appendFmt(allocator, &buf, "### `{s}`\n\n", .{rel});

        const lang_tag = detectLangTag(rel);
        try appendFmt(allocator, &buf, "```{s}\n", .{lang_tag});
        try buf.appendSlice(allocator, content);
        if (content[content.len - 1] != '\n') {
            try buf.append(allocator, '\n');
        }
        try appendStr(allocator, &buf, "```\n\n");

        total_bytes += content.len;
        files_included += 1;
    }

    // === Footer ===
    try appendStr(allocator, &buf, "---\n\n");

    if (total_bytes < 1024) {
        try appendFmt(allocator, &buf, "*Compiled by zig-lens — {d} files, {d} bytes*\n", .{ files_included, total_bytes });
    } else if (total_bytes < 1024 * 1024) {
        try appendFmt(allocator, &buf, "*Compiled by zig-lens — {d} files, {d} KB*\n", .{ files_included, total_bytes / 1024 });
    } else {
        try appendFmt(allocator, &buf, "*Compiled by zig-lens — {d} files, {d} MB*\n", .{ files_included, total_bytes / (1024 * 1024) });
    }

    return buf.items;
}

// ============================================================================
// Tree Building and Rendering
// ============================================================================

fn writeTree(
    allocator: std.mem.Allocator,
    buf: *std.ArrayListUnmanaged(u8),
    paths: []const []const u8,
    project_name: []const u8,
) !void {
    // Build tree structure
    const root = try allocator.create(TreeNode);
    root.* = .{ .name = project_name, .children = .empty, .is_file = false };

    for (paths) |path| {
        var current = root;
        var it = std.mem.splitScalar(u8, path, '/');
        var components: [64][]const u8 = undefined;
        var depth: usize = 0;
        while (it.next()) |comp| {
            if (depth < 64) {
                components[depth] = comp;
                depth += 1;
            }
        }

        for (0..depth) |d| {
            const is_leaf = (d == depth - 1);
            current = try getOrCreateChild(allocator, current, components[d], is_leaf);
        }
    }

    // Sort children at all levels (dirs first, then alphabetical)
    sortTreeChildren(root);

    // Render
    try appendFmt(allocator, buf, "{s}/\n", .{project_name});
    var ancestry: [64]bool = .{false} ** 64;
    for (root.children.items, 0..) |child, i| {
        const is_last = (i == root.children.items.len - 1);
        try renderNode(allocator, buf, child, 0, is_last, &ancestry);
    }
}

fn getOrCreateChild(
    allocator: std.mem.Allocator,
    parent: *TreeNode,
    name: []const u8,
    is_file: bool,
) !*TreeNode {
    for (parent.children.items) |child| {
        if (std.mem.eql(u8, child.name, name)) return child;
    }
    const node = try allocator.create(TreeNode);
    node.* = .{ .name = name, .children = .empty, .is_file = is_file };
    try parent.children.append(allocator, node);
    return node;
}

fn sortTreeChildren(node: *TreeNode) void {
    if (node.children.items.len == 0) return;

    std.mem.sortUnstable(*TreeNode, node.children.items, {}, struct {
        fn lessThan(_: void, a: *TreeNode, b: *TreeNode) bool {
            // Directories before files
            if (!a.is_file and b.is_file) return true;
            if (a.is_file and !b.is_file) return false;
            return std.mem.order(u8, a.name, b.name) == .lt;
        }
    }.lessThan);

    for (node.children.items) |child| {
        sortTreeChildren(child);
    }
}

fn renderNode(
    allocator: std.mem.Allocator,
    buf: *std.ArrayListUnmanaged(u8),
    node: *TreeNode,
    depth: usize,
    is_last: bool,
    ancestry: *[64]bool,
) !void {
    // Print prefix for current depth
    for (0..depth) |d| {
        if (ancestry[d]) {
            try appendStr(allocator, buf, "    ");
        } else {
            try appendStr(allocator, buf, "\xe2\x94\x82   "); // │
        }
    }

    // Connector
    if (is_last) {
        try appendStr(allocator, buf, "\xe2\x94\x94\xe2\x94\x80\xe2\x94\x80 "); // └──
    } else {
        try appendStr(allocator, buf, "\xe2\x94\x9c\xe2\x94\x80\xe2\x94\x80 "); // ├──
    }

    // Name
    try appendStr(allocator, buf, node.name);
    if (!node.is_file) {
        try appendStr(allocator, buf, "/");
    }
    try appendStr(allocator, buf, "\n");

    // Children
    ancestry[depth] = is_last;
    for (node.children.items, 0..) |child, i| {
        const child_is_last = (i == node.children.items.len - 1);
        try renderNode(allocator, buf, child, depth + 1, child_is_last, ancestry);
    }
}

// ============================================================================
// File Filtering
// ============================================================================

fn shouldSkipPath(path: []const u8) bool {
    var it = std.mem.splitScalar(u8, path, '/');
    while (it.next()) |component| {
        for (&skip_dirs) |skip| {
            if (std.mem.eql(u8, component, skip)) return true;
        }
    }
    return false;
}

fn shouldSkipFile(basename: []const u8) bool {
    // Binary extensions
    for (&binary_extensions) |ext| {
        if (std.mem.endsWith(u8, basename, ext)) return true;
    }
    // Lock files
    if (std.mem.endsWith(u8, basename, ".lock")) return true;
    if (std.mem.eql(u8, basename, "package-lock.json")) return true;
    // Minified files
    if (std.mem.endsWith(u8, basename, ".min.js")) return true;
    if (std.mem.endsWith(u8, basename, ".min.css")) return true;
    // OS metadata
    if (std.mem.eql(u8, basename, ".DS_Store")) return true;
    if (std.mem.eql(u8, basename, "Thumbs.db")) return true;
    return false;
}

fn detectLangTag(path: []const u8) []const u8 {
    if (std.mem.endsWith(u8, path, ".zig")) return "zig";
    if (std.mem.endsWith(u8, path, ".rs")) return "rust";
    if (std.mem.endsWith(u8, path, ".c") or std.mem.endsWith(u8, path, ".h")) return "c";
    if (std.mem.endsWith(u8, path, ".cpp") or std.mem.endsWith(u8, path, ".hpp")) return "cpp";
    if (std.mem.endsWith(u8, path, ".py")) return "python";
    if (std.mem.endsWith(u8, path, ".js") or std.mem.endsWith(u8, path, ".jsx")) return "javascript";
    if (std.mem.endsWith(u8, path, ".ts") or std.mem.endsWith(u8, path, ".tsx")) return "typescript";
    if (std.mem.endsWith(u8, path, ".svelte")) return "svelte";
    if (std.mem.endsWith(u8, path, ".json")) return "json";
    if (std.mem.endsWith(u8, path, ".toml")) return "toml";
    if (std.mem.endsWith(u8, path, ".yaml") or std.mem.endsWith(u8, path, ".yml")) return "yaml";
    if (std.mem.endsWith(u8, path, ".xml")) return "xml";
    if (std.mem.endsWith(u8, path, ".html") or std.mem.endsWith(u8, path, ".htm")) return "html";
    if (std.mem.endsWith(u8, path, ".css")) return "css";
    if (std.mem.endsWith(u8, path, ".scss")) return "scss";
    if (std.mem.endsWith(u8, path, ".sh") or std.mem.endsWith(u8, path, ".bash")) return "bash";
    if (std.mem.endsWith(u8, path, ".md") or std.mem.endsWith(u8, path, ".mdx")) return "markdown";
    if (std.mem.endsWith(u8, path, ".sql")) return "sql";
    if (std.mem.endsWith(u8, path, ".go")) return "go";
    if (std.mem.endsWith(u8, path, ".java")) return "java";
    if (std.mem.endsWith(u8, path, ".kt")) return "kotlin";
    if (std.mem.endsWith(u8, path, ".swift")) return "swift";
    if (std.mem.endsWith(u8, path, ".rb")) return "ruby";
    if (std.mem.endsWith(u8, path, ".lua")) return "lua";
    if (std.mem.endsWith(u8, path, ".r") or std.mem.endsWith(u8, path, ".R")) return "r";
    return "";
}

fn readFileContent(io: std.Io, allocator: std.mem.Allocator, path: []const u8) ![]const u8 {
    return std.Io.Dir.cwd().readFileAllocOptions(
        io,
        path,
        allocator,
        .limited(max_file_size),
        .of(u8),
        0,
    ) catch {
        return error.FileReadFailed;
    };
}

// ============================================================================
// Helpers
// ============================================================================

fn appendFmt(allocator: std.mem.Allocator, buf: *std.ArrayListUnmanaged(u8), comptime fmt: []const u8, args: anytype) !void {
    const s = try std.fmt.allocPrint(allocator, fmt, args);
    defer allocator.free(s);
    try buf.appendSlice(allocator, s);
}

fn appendStr(allocator: std.mem.Allocator, buf: *std.ArrayListUnmanaged(u8), s: []const u8) !void {
    try buf.appendSlice(allocator, s);
}

// ============================================================================
// Tests
// ============================================================================

test "detectLangTag for common extensions" {
    try std.testing.expectEqualSlices(u8, "zig", detectLangTag("main.zig"));
    try std.testing.expectEqualSlices(u8, "rust", detectLangTag("lib.rs"));
    try std.testing.expectEqualSlices(u8, "python", detectLangTag("app.py"));
    try std.testing.expectEqualSlices(u8, "json", detectLangTag("package.json"));
    try std.testing.expectEqualSlices(u8, "typescript", detectLangTag("app.tsx"));
    try std.testing.expectEqualSlices(u8, "bash", detectLangTag("build.sh"));
    try std.testing.expectEqualSlices(u8, "markdown", detectLangTag("README.md"));
    try std.testing.expectEqualSlices(u8, "", detectLangTag("LICENSE"));
}

test "shouldSkipFile skips binary and generated files" {
    try std.testing.expect(shouldSkipFile("image.png"));
    try std.testing.expect(shouldSkipFile("archive.zip"));
    try std.testing.expect(shouldSkipFile("package-lock.json"));
    try std.testing.expect(shouldSkipFile("app.min.js"));
    try std.testing.expect(shouldSkipFile(".DS_Store"));
    try std.testing.expect(shouldSkipFile("Cargo.lock"));
    try std.testing.expect(!shouldSkipFile("main.zig"));
    try std.testing.expect(!shouldSkipFile("README.md"));
    try std.testing.expect(!shouldSkipFile("Makefile"));
    try std.testing.expect(!shouldSkipFile("Dockerfile"));
}

test "shouldSkipPath skips excluded directories" {
    try std.testing.expect(shouldSkipPath("node_modules/express/index.js"));
    try std.testing.expect(shouldSkipPath(".git/config"));
    try std.testing.expect(shouldSkipPath("zig-cache/stuff"));
    try std.testing.expect(shouldSkipPath("src/target/debug/main"));
    try std.testing.expect(!shouldSkipPath("src/main.zig"));
    try std.testing.expect(!shouldSkipPath("lib/utils.zig"));
}
