const std = @import("std");
const models = @import("../models.zig");
const graph_builder = @import("../graph/builder.zig");

pub fn writeReport(allocator: std.mem.Allocator, report: *const models.ProjectReport, graph: ?*const graph_builder.DependencyGraph) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;

    try appendFmt(allocator, &buf, "# {s}\n\n", .{report.name});

    // Summary table
    const s = &report.summary;
    try appendFmt(allocator, &buf, "## Summary\n\n", .{});
    try appendFmt(allocator, &buf, "| Metric | Count |\n|--------|-------|\n", .{});
    try appendFmt(allocator, &buf, "| Files | {d} |\n", .{s.total_files});
    try appendFmt(allocator, &buf, "| Lines of Code | {d} |\n", .{s.total_loc});
    try appendFmt(allocator, &buf, "| Functions | {d} |\n", .{s.total_functions});
    try appendFmt(allocator, &buf, "| Public API | {d} |\n", .{s.total_pub_functions});
    try appendFmt(allocator, &buf, "| Structs | {d} |\n", .{s.total_structs});
    try appendFmt(allocator, &buf, "| Enums | {d} |\n", .{s.total_enums});
    if (s.total_unions > 0)
        try appendFmt(allocator, &buf, "| Unions | {d} |\n", .{s.total_unions});
    try appendFmt(allocator, &buf, "| Tests | {d} |\n", .{s.total_tests});
    try appendFmt(allocator, &buf, "| Imports | {d} |\n", .{s.total_imports});
    if (s.total_unsafe_ops > 0)
        try appendFmt(allocator, &buf, "| Unsafe Ops | {d} |\n", .{s.total_unsafe_ops});
    try appendFmt(allocator, &buf, "\n", .{});

    // File listing
    try appendFmt(allocator, &buf, "## Files\n\n", .{});
    try appendFmt(allocator, &buf, "| File | LOC | Functions | Structs | Tests |\n", .{});
    try appendFmt(allocator, &buf, "|------|-----|-----------|---------|-------|\n", .{});
    for (report.files.items) |*file| {
        try appendFmt(allocator, &buf, "| `{s}` | {d} | {d} | {d} | {d} |\n", .{
            file.relative_path,
            file.loc,
            file.functions.items.len,
            file.structs.items.len,
            file.tests.items.len,
        });
    }
    try appendFmt(allocator, &buf, "\n", .{});

    // Dependency graph as Mermaid
    if (graph) |g| {
        if (g.edges.items.len > 0) {
            try appendFmt(allocator, &buf, "## Dependency Graph\n\n", .{});
            try appendFmt(allocator, &buf, "```mermaid\ngraph LR\n", .{});
            for (g.edges.items) |*edge| {
                const from_short = std.fs.path.basename(edge.from);
                const to_short = std.fs.path.basename(edge.to);
                try appendFmt(allocator, &buf, "  {s} --> {s}\n", .{ from_short, to_short });
            }
            try appendFmt(allocator, &buf, "```\n\n", .{});
        }

        if (g.hub_files.items.len > 0) {
            try appendFmt(allocator, &buf, "### Hub Modules\n\n", .{});
            for (g.hub_files.items) |hub| {
                try appendFmt(allocator, &buf, "- `{s}`\n", .{hub});
            }
            try appendFmt(allocator, &buf, "\n", .{});
        }
    }

    // Public API
    try appendFmt(allocator, &buf, "## Public API\n\n", .{});
    for (report.files.items) |*file| {
        var has_pub = false;
        for (file.functions.items) |*f| {
            if (f.is_pub) {
                if (!has_pub) {
                    try appendFmt(allocator, &buf, "### `{s}`\n\n", .{file.relative_path});
                    has_pub = true;
                }
                if (f.doc_comment.len > 0) {
                    try appendFmt(allocator, &buf, "- `{s}` — {s}\n", .{ f.name, f.doc_comment });
                } else {
                    try appendFmt(allocator, &buf, "- `{s}`\n", .{f.name});
                }
            }
        }
        if (has_pub) try appendFmt(allocator, &buf, "\n", .{});
    }

    // Unsafe ops
    if (s.total_unsafe_ops > 0) {
        try appendFmt(allocator, &buf, "## Unsafe Operations\n\n", .{});
        try appendFmt(allocator, &buf, "| File | Line | Operation | Risk |\n", .{});
        try appendFmt(allocator, &buf, "|------|------|-----------|------|\n", .{});
        for (report.files.items) |*file| {
            for (file.unsafe_ops.items) |*op| {
                try appendFmt(allocator, &buf, "| `{s}` | {d} | `{s}` | {s} |\n", .{
                    file.relative_path,
                    op.line,
                    op.operation,
                    @tagName(op.risk_level),
                });
            }
        }
        try appendFmt(allocator, &buf, "\n", .{});
    }

    try appendFmt(allocator, &buf, "---\n*Generated by zig-lens*\n", .{});

    return buf.items;
}

fn appendFmt(allocator: std.mem.Allocator, buf: *std.ArrayListUnmanaged(u8), comptime fmt: []const u8, args: anytype) !void {
    const s = try std.fmt.allocPrint(allocator, fmt, args);
    defer allocator.free(s);
    try buf.appendSlice(allocator, s);
}
