const std = @import("std");
const models = @import("../models.zig");
const json_output = @import("json.zig");
const markdown_output = @import("markdown.zig");
const graph_dot = @import("../graph/dot.zig");
const graph_builder = @import("../graph/builder.zig");

/// Generate all report files into a target directory.
/// Creates the directory if it doesn't exist.
pub fn generateReports(
    allocator: std.mem.Allocator,
    io: std.Io,
    report: *const models.ProjectReport,
    graph: *const graph_builder.DependencyGraph,
    output_dir: []const u8,
) !void {
    // Create output directory
    const dir = std.Io.Dir.cwd().createDirPathOpen(io, output_dir, .{}) catch {
        std.debug.print("Failed to create report directory: {s}\n", .{output_dir});
        return;
    };
    defer dir.close(io);

    std.debug.print("\nzig-lens report generator — {s}\n", .{report.name});
    std.debug.print("Output: {s}/\n\n", .{output_dir});

    // 1. AI context (compact JSON)
    writeFile(dir, io, "ai-context.json", json_output.writeProjectReport(allocator, report, true) catch null);

    // 2. Full analysis (detailed JSON)
    writeFile(dir, io, "full-analysis.json", json_output.writeProjectReport(allocator, report, false) catch null);

    // 3. Summary markdown
    writeFile(dir, io, "summary.md", markdown_output.writeReport(allocator, report, graph) catch null);

    // 4. Dependencies DOT graph
    if (graph.edges.items.len > 0) {
        writeFile(dir, io, "dependencies.dot", graph_dot.writeDot(allocator, graph, report.name) catch null);
    }

    // 5. Architecture overview (narrative)
    writeFile(dir, io, "OVERVIEW.md", writeOverview(allocator, report, graph) catch null);

    std.debug.print("Done.\n", .{});
}

fn writeFile(dir: std.Io.Dir, io: std.Io, name: []const u8, content: ?[]const u8) void {
    const data = content orelse {
        std.debug.print("  [SKIP] {s} (generation failed)\n", .{name});
        return;
    };
    const file = dir.createFile(io, name, .{}) catch {
        std.debug.print("  [FAIL] {s}\n", .{name});
        return;
    };
    defer file.close(io);
    file.writeStreamingAll(io, data) catch {
        std.debug.print("  [FAIL] {s} (write error)\n", .{name});
        return;
    };
    std.debug.print("  [OK]   {s} ({d} bytes)\n", .{ name, data.len });
}

/// Generate a narrative architecture overview document.
fn writeOverview(allocator: std.mem.Allocator, report: *const models.ProjectReport, graph: *const graph_builder.DependencyGraph) ![]const u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;

    try appendFmt(allocator, &buf, "# {s} — Architecture Overview\n\n", .{report.name});
    try appendFmt(allocator, &buf, "> Auto-generated by zig-lens. Feed this to an AI agent for instant codebase understanding.\n\n", .{});

    // Summary
    const s = &report.summary;
    try appendFmt(allocator, &buf, "## At a Glance\n\n", .{});
    try appendFmt(allocator, &buf, "- **{d} files** across ", .{s.total_files});

    // Language breakdown
    var lang_counts = [_]u32{0} ** 5;
    for (report.files.items) |*f| {
        lang_counts[@intFromEnum(f.language)] += 1;
    }
    var first_lang = true;
    const lang_names = [_][]const u8{ "Zig", "Rust", "C", "Python", "JavaScript/TypeScript" };
    for (lang_names, 0..) |name, i| {
        if (lang_counts[i] > 0) {
            if (!first_lang) try appendStr(allocator, &buf, ", ");
            try appendFmt(allocator, &buf, "{d} {s}", .{ lang_counts[i], name });
            first_lang = false;
        }
    }
    try appendStr(allocator, &buf, "\n");

    try appendFmt(allocator, &buf, "- **{d} lines of code** ({d} blank, {d} comments)\n", .{ s.total_loc, s.total_blank, s.total_comments });
    try appendFmt(allocator, &buf, "- **{d} functions** ({d} public API)\n", .{ s.total_functions, s.total_pub_functions });
    if (s.total_structs > 0) try appendFmt(allocator, &buf, "- **{d} structs/classes**\n", .{s.total_structs});
    if (s.total_enums > 0) try appendFmt(allocator, &buf, "- **{d} enums**\n", .{s.total_enums});
    if (s.total_unions > 0) try appendFmt(allocator, &buf, "- **{d} unions**\n", .{s.total_unions});
    if (s.total_tests > 0) try appendFmt(allocator, &buf, "- **{d} tests**\n", .{s.total_tests});
    if (s.total_unsafe_ops > 0) try appendFmt(allocator, &buf, "- **{d} unsafe operations**\n", .{s.total_unsafe_ops});
    try appendStr(allocator, &buf, "\n");

    // Language breakdown table
    {
        var has_multi = false;
        var count: u32 = 0;
        for (lang_counts) |c| {
            if (c > 0) count += 1;
        }
        if (count > 1) has_multi = true;

        if (has_multi) {
            try appendStr(allocator, &buf, "## Language Breakdown\n\n");
            try appendStr(allocator, &buf, "| Language | Files | LOC | Functions | Structs |\n");
            try appendStr(allocator, &buf, "|----------|-------|-----|-----------|--------|\n");

            for (lang_names, 0..) |name, li| {
                if (lang_counts[li] == 0) continue;
                var lang_loc: u32 = 0;
                var lang_fns: u32 = 0;
                var lang_structs: u32 = 0;
                for (report.files.items) |*f| {
                    if (@intFromEnum(f.language) == li) {
                        lang_loc += f.loc;
                        lang_fns += @intCast(f.functions.items.len);
                        lang_structs += @intCast(f.structs.items.len);
                    }
                }
                try appendFmt(allocator, &buf, "| {s} | {d} | {d} | {d} | {d} |\n", .{ name, lang_counts[li], lang_loc, lang_fns, lang_structs });
            }
            try appendStr(allocator, &buf, "\n");
        }
    }

    // Core modules (hub files from dependency graph)
    if (graph.hub_files.items.len > 0) {
        try appendStr(allocator, &buf, "## Core Modules\n\n");
        try appendStr(allocator, &buf, "These files are imported by 3+ other files and form the backbone of the architecture:\n\n");
        for (graph.hub_files.items) |hub| {
            // Find LOC and function count for this file
            for (report.files.items) |*f| {
                if (std.mem.eql(u8, f.relative_path, hub)) {
                    try appendFmt(allocator, &buf, "- **`{s}`** — {d} LOC, {d} functions", .{ hub, f.loc, f.functions.items.len });
                    if (f.structs.items.len > 0)
                        try appendFmt(allocator, &buf, ", {d} structs", .{f.structs.items.len});
                    try appendStr(allocator, &buf, "\n");
                    break;
                }
            }
        }
        try appendStr(allocator, &buf, "\n");
    }

    // Key types (structs/classes with most fields+methods, top 20)
    {
        const TypeRef = struct {
            name: []const u8,
            file: []const u8,
            kind: models.ContainerKind,
            fields: u32,
            methods: u32,
            doc: []const u8,
            score: u32,
        };
        var types: std.ArrayListUnmanaged(TypeRef) = .empty;

        for (report.files.items) |*f| {
            for (f.structs.items) |*st| {
                const score = st.fields_count + st.methods_count * 2;
                if (score >= 2) {
                    try types.append(allocator, .{
                        .name = st.name,
                        .file = f.relative_path,
                        .kind = st.kind,
                        .fields = st.fields_count,
                        .methods = st.methods_count,
                        .doc = st.doc_comment,
                        .score = score,
                    });
                }
            }
        }

        if (types.items.len > 0) {
            std.mem.sortUnstable(TypeRef, types.items, {}, struct {
                fn lessThan(_: void, a: TypeRef, b: TypeRef) bool {
                    return a.score > b.score;
                }
            }.lessThan);

            try appendStr(allocator, &buf, "## Key Types\n\n");
            const show = @min(types.items.len, 20);
            for (types.items[0..show]) |t| {
                const kind_str = switch (t.kind) {
                    .@"struct" => "struct",
                    .packed_struct => "packed struct",
                    .extern_struct => "extern struct",
                    .trait => "trait",
                    .impl_block => "impl",
                    .interface => "interface",
                    .class => "class",
                    .type_alias => "type",
                    else => "struct",
                };
                try appendFmt(allocator, &buf, "- **`{s}`** ({s}) in `{s}` — {d} fields, {d} methods", .{
                    t.name, kind_str, t.file, t.fields, t.methods,
                });
                if (t.doc.len > 0) {
                    try appendFmt(allocator, &buf, " — {s}", .{t.doc});
                }
                try appendStr(allocator, &buf, "\n");
            }
            try appendStr(allocator, &buf, "\n");
        }
    }

    // Public API surface
    {
        const ApiEntry = struct {
            name: []const u8,
            file: []const u8,
            params: []const u8,
            return_type: []const u8,
            doc: []const u8,
        };
        var api: std.ArrayListUnmanaged(ApiEntry) = .empty;

        for (report.files.items) |*f| {
            for (f.functions.items) |*fn_info| {
                if (fn_info.is_pub) {
                    try api.append(allocator, .{
                        .name = fn_info.name,
                        .file = f.relative_path,
                        .params = fn_info.params,
                        .return_type = fn_info.return_type,
                        .doc = fn_info.doc_comment,
                    });
                }
            }
        }

        if (api.items.len > 0) {
            try appendStr(allocator, &buf, "## Public API\n\n");
            try appendFmt(allocator, &buf, "{d} public functions across {d} files.\n\n", .{ api.items.len, s.total_files });

            // Group by file
            var current_file: []const u8 = "";
            for (api.items) |entry| {
                if (!std.mem.eql(u8, entry.file, current_file)) {
                    current_file = entry.file;
                    try appendFmt(allocator, &buf, "### `{s}`\n\n", .{current_file});
                }
                try appendFmt(allocator, &buf, "- `{s}`", .{entry.name});
                if (entry.params.len > 0 or entry.return_type.len > 0) {
                    try appendStr(allocator, &buf, "(");
                    if (entry.params.len > 0) try appendFmt(allocator, &buf, "{s}", .{entry.params});
                    try appendStr(allocator, &buf, ")");
                    if (entry.return_type.len > 0) try appendFmt(allocator, &buf, " -> {s}", .{entry.return_type});
                }
                if (entry.doc.len > 0) {
                    try appendFmt(allocator, &buf, " — {s}", .{entry.doc});
                }
                try appendStr(allocator, &buf, "\n");
            }
            try appendStr(allocator, &buf, "\n");
        }
    }

    // Largest files
    if (report.files.items.len > 3) {
        try appendStr(allocator, &buf, "## Largest Files\n\n");
        try appendStr(allocator, &buf, "| File | LOC | Functions | Structs | Language |\n");
        try appendStr(allocator, &buf, "|------|-----|-----------|---------|----------|\n");

        var indices = try allocator.alloc(usize, report.files.items.len);
        for (indices, 0..) |*idx, i| idx.* = i;

        std.mem.sortUnstable(usize, indices, report.files.items, struct {
            fn lessThan(files: []const models.FileReport, a: usize, b: usize) bool {
                return files[a].loc > files[b].loc;
            }
        }.lessThan);

        const show = @min(indices.len, 15);
        for (indices[0..show]) |idx| {
            const f = &report.files.items[idx];
            const lang_str = langName(f.language);
            try appendFmt(allocator, &buf, "| `{s}` | {d} | {d} | {d} | {s} |\n", .{
                f.relative_path,
                f.loc,
                f.functions.items.len,
                f.structs.items.len,
                lang_str,
            });
        }
        try appendStr(allocator, &buf, "\n");
    }

    // Warnings & risks
    {
        var has_warnings = false;
        // Unsafe ops
        if (s.total_unsafe_ops > 0) {
            if (!has_warnings) {
                try appendStr(allocator, &buf, "## Warnings & Risks\n\n");
                has_warnings = true;
            }
            try appendFmt(allocator, &buf, "### Unsafe Operations ({d} total)\n\n", .{s.total_unsafe_ops});

            var critical_count: u32 = 0;
            var high_count: u32 = 0;
            for (report.files.items) |*f| {
                for (f.unsafe_ops.items) |*op| {
                    if (op.risk_level == .critical) critical_count += 1;
                    if (op.risk_level == .high) high_count += 1;
                }
            }
            if (critical_count > 0) try appendFmt(allocator, &buf, "- **{d} critical** (asm, @setRuntimeSafety(false))\n", .{critical_count});
            if (high_count > 0) try appendFmt(allocator, &buf, "- **{d} high risk** (@ptrCast, @intFromPtr, etc.)\n", .{high_count});
            try appendStr(allocator, &buf, "\n");

            try appendStr(allocator, &buf, "| File | Line | Operation | Risk |\n");
            try appendStr(allocator, &buf, "|------|------|-----------|------|\n");
            var shown: u32 = 0;
            for (report.files.items) |*f| {
                for (f.unsafe_ops.items) |*op| {
                    if (shown >= 30) break;
                    try appendFmt(allocator, &buf, "| `{s}` | {d} | `{s}` | {s} |\n", .{
                        f.relative_path, op.line, op.operation, @tagName(op.risk_level),
                    });
                    shown += 1;
                }
            }
            if (s.total_unsafe_ops > 30) {
                try appendFmt(allocator, &buf, "\n*...and {d} more. See full-analysis.json for complete list.*\n", .{s.total_unsafe_ops - 30});
            }
            try appendStr(allocator, &buf, "\n");
        }

        // Large functions
        {
            var large_fns: std.ArrayListUnmanaged(struct { file: []const u8, name: []const u8, lines: u32 }) = .empty;
            for (report.files.items) |*f| {
                for (f.functions.items) |*fn_info| {
                    if (fn_info.body_lines > 50) {
                        try large_fns.append(allocator, .{
                            .file = f.relative_path,
                            .name = fn_info.name,
                            .lines = fn_info.body_lines,
                        });
                    }
                }
            }
            if (large_fns.items.len > 0) {
                if (!has_warnings) {
                    try appendStr(allocator, &buf, "## Warnings & Risks\n\n");
                    has_warnings = true;
                }
                try appendFmt(allocator, &buf, "### Large Functions ({d} over 50 lines)\n\n", .{large_fns.items.len});
                try appendStr(allocator, &buf, "| File | Function | Lines |\n");
                try appendStr(allocator, &buf, "|------|----------|-------|\n");
                const show = @min(large_fns.items.len, 20);
                for (large_fns.items[0..show]) |lf| {
                    try appendFmt(allocator, &buf, "| `{s}` | `{s}` | {d} |\n", .{ lf.file, lf.name, lf.lines });
                }
                try appendStr(allocator, &buf, "\n");
            }
        }

        // Parse errors
        if (s.parse_errors > 0) {
            if (!has_warnings) {
                try appendStr(allocator, &buf, "## Warnings & Risks\n\n");
                has_warnings = true;
            }
            try appendFmt(allocator, &buf, "### Parse Errors ({d} files)\n\n", .{s.parse_errors});
            for (report.files.items) |*f| {
                if (f.parse_error) {
                    try appendFmt(allocator, &buf, "- `{s}`\n", .{f.relative_path});
                }
            }
            try appendStr(allocator, &buf, "\n");
        }
    }

    // Dependency structure
    if (graph.edges.items.len > 0) {
        try appendStr(allocator, &buf, "## Dependency Structure\n\n");
        try appendFmt(allocator, &buf, "- {d} internal dependencies\n", .{graph.edges.items.len});
        try appendFmt(allocator, &buf, "- {d} hub modules (imported by 3+ files)\n", .{graph.hub_files.items.len});
        try appendFmt(allocator, &buf, "- {d} leaf/orphan files (not imported by others)\n", .{graph.orphan_files.items.len});
        try appendStr(allocator, &buf, "\nSee `dependencies.dot` for full Graphviz graph.\n\n");
    }

    // Import summary
    if (s.total_imports > 0) {
        var std_count: u32 = 0;
        var local_count: u32 = 0;
        var pkg_count: u32 = 0;
        for (report.files.items) |*f| {
            for (f.imports.items) |*imp| {
                switch (imp.kind) {
                    .std_lib => std_count += 1,
                    .local => local_count += 1,
                    .package => pkg_count += 1,
                }
            }
        }
        try appendStr(allocator, &buf, "## Import Summary\n\n");
        try appendFmt(allocator, &buf, "- **{d}** standard library imports\n", .{std_count});
        try appendFmt(allocator, &buf, "- **{d}** local/relative imports\n", .{local_count});
        try appendFmt(allocator, &buf, "- **{d}** external package imports\n", .{pkg_count});
        try appendStr(allocator, &buf, "\n");
    }

    // Testing overview
    if (s.total_tests > 0) {
        try appendStr(allocator, &buf, "## Testing\n\n");
        try appendFmt(allocator, &buf, "{d} test blocks found.\n\n", .{s.total_tests});

        var files_with_tests: u32 = 0;
        for (report.files.items) |*f| {
            if (f.tests.items.len > 0) files_with_tests += 1;
        }
        try appendFmt(allocator, &buf, "- {d}/{d} files have tests ({d}%)\n\n", .{
            files_with_tests,
            s.total_files,
            if (s.total_files > 0) files_with_tests * 100 / s.total_files else @as(u32, 0),
        });
    }

    try appendStr(allocator, &buf, "---\n\n*Generated by [zig-lens](https://github.com/quantum-encoding/zig-forge/tree/master/programs/zig_lens)*\n");

    return buf.items;
}

fn langName(lang: models.Language) []const u8 {
    return switch (lang) {
        .zig => "Zig",
        .rust => "Rust",
        .c => "C",
        .python => "Python",
        .javascript => "JS/TS",
        .go => "Go",
    };
}

fn appendFmt(allocator: std.mem.Allocator, buf: *std.ArrayListUnmanaged(u8), comptime fmt: []const u8, args: anytype) !void {
    const fmted = try std.fmt.allocPrint(allocator, fmt, args);
    defer allocator.free(fmted);
    try buf.appendSlice(allocator, fmted);
}

fn appendStr(allocator: std.mem.Allocator, buf: *std.ArrayListUnmanaged(u8), s: []const u8) !void {
    try buf.appendSlice(allocator, s);
}
