//! zig_doom/src/sound/defs.zig
//!
//! Sound effect and music ID definitions.
//! Translated from: linuxdoom-1.10/sounds.h
//! Original: Copyright (C) 1993-1996 id Software, Inc. GPL-2.0

const std = @import("std");

pub const SfxId = enum(u16) {
    none = 0,
    pistol,
    shotgn,
    sgcock,
    dshtgn,
    dbopn,
    dbcls,
    dbload,
    plasma,
    bfg,
    sawup,
    sawidl,
    sawful,
    sawhit,
    rlaunc,
    rxplod,
    firsht,
    firxpl,
    pstart,
    pstop,
    doropn,
    dorcls,
    stnmov,
    swtchn,
    swtchx,
    plpain,
    dmpain,
    popain,
    vipain,
    mnpain,
    pepain,
    slop,
    itemup,
    wpnup,
    oof,
    telept,
    posit1,
    posit2,
    posit3,
    bgsit1,
    bgsit2,
    sgtsit,
    cacsit,
    brssit,
    cybsit,
    spisit,
    bspsit,
    kntsit,
    vilsit,
    mansit,
    pesit,
    sklatk,
    sgtatk,
    skepch,
    vilatk,
    claw,
    skeswg,
    pldeth,
    pdiehi,
    podth1,
    podth2,
    podth3,
    bgdth1,
    bgdth2,
    sgtdth,
    cacdth,
    skldth,
    brsdth,
    cybdth,
    spidth,
    bspdth,
    vildth,
    kntdth,
    pedth,
    skedth,
    mandth,
    posact,
    bgact,
    dmact,
    bspact,
    bspwlk,
    vilact,
    noway,
    barexp,
    punch,
    hoof,
    metal,
    chgun,
    tink,
    bdopn,
    bdcls,
    itmbk,
    flame,
    flamst,
    getpow,
    bospit,
    boscub,
    bossit,
    bospn,
    bosdth,
    manatk,
    mandth2,
    sssit,
    ssdth,
    keenpn,
    keendt,
    skeact,
    skesit,
    skeatk,
    radio,
    _,
};

pub const MusicId = enum(u16) {
    none = 0,
    e1m1,
    e1m2,
    e1m3,
    e1m4,
    e1m5,
    e1m6,
    e1m7,
    e1m8,
    e1m9,
    e2m1,
    e2m2,
    e2m3,
    e2m4,
    e2m5,
    e2m6,
    e2m7,
    e2m8,
    e2m9,
    e3m1,
    e3m2,
    e3m3,
    e3m4,
    e3m5,
    e3m6,
    e3m7,
    e3m8,
    e3m9,
    inter,
    intro,
    bunny,
    victor,
    introa,
    _,
};

/// WAD lump name prefix for sound effects
pub const SFX_PREFIX = "DS";

/// WAD lump name prefix for music
pub const MUSIC_PREFIX = "D_";

test "sfx enum values" {
    try std.testing.expectEqual(@as(u16, 0), @intFromEnum(SfxId.none));
    try std.testing.expectEqual(@as(u16, 1), @intFromEnum(SfxId.pistol));
    try std.testing.expect(@intFromEnum(SfxId.radio) > 0);
}

test "music enum values" {
    try std.testing.expectEqual(@as(u16, 0), @intFromEnum(MusicId.none));
    try std.testing.expectEqual(@as(u16, 1), @intFromEnum(MusicId.e1m1));
}
