//! Invoice/Quote Template Renderer
//!
//! Generates professional PDF invoices from structured data.
//! Supports multiple template styles and customization options.
//!
//! Features:
//! - Company logo embedding
//! - QR code embedding (VeriFactu compliance)
//! - Multiple display modes (itemized, blackbox)
//! - Color customization
//! - Multi-page support for long item lists

const std = @import("std");
const document = @import("document.zig");
const image = @import("image.zig");
const qrcode = @import("qrcode.zig");
const identicon = @import("identicon.zig");
const crypto_receipt = @import("crypto_receipt.zig");

// =============================================================================
// Invoice Data Model
// =============================================================================

pub const LineItem = struct {
    description: []const u8,
    quantity: f64,
    unit_price: f64,
    total: f64,
};

pub const DisplayMode = enum {
    itemized, // Show full item details
    blackbox, // Show single summary line
};

pub const TemplateStyle = enum {
    professional,
    modern,
    classic,
    creative,
};

pub const QrCodeMode = enum {
    none, // No QR code displayed
    verifactu, // Spanish VeriFactu compliance
    payment_link, // Stripe/GoCardless payment URL
    bank_details, // UK Faster Payments format
    verification, // Hosted invoice verification link
    crypto, // Cryptocurrency payment (BTC, ETH, etc.)
};

pub const InvoiceData = struct {
    // Document type
    document_type: []const u8 = "invoice", // "invoice" or "quote"

    // Company info
    company_name: []const u8 = "",
    company_address: []const u8 = "",
    company_vat: []const u8 = "",
    company_logo_base64: ?[]const u8 = null,

    // Client info
    client_name: []const u8 = "",
    client_address: []const u8 = "",
    client_vat: []const u8 = "",

    // Document details
    invoice_number: []const u8 = "",
    invoice_date: []const u8 = "",
    due_date: []const u8 = "",

    // Items
    display_mode: DisplayMode = .itemized,
    items: []const LineItem = &[_]LineItem{},
    blackbox_description: []const u8 = "",

    // Totals
    subtotal: f64 = 0,
    tax_rate: f64 = 0.21,
    tax_amount: f64 = 0,
    total: f64 = 0,

    // Optional
    qr_base64: ?[]const u8 = null, // QR code image (base64 PNG)
    qr_mode: QrCodeMode = .none, // QR code purpose/label
    qr_label: ?[]const u8 = null, // Custom label for QR code (overrides default)
    verifactu_qr_base64: ?[]const u8 = null, // Legacy: maps to qr_base64 + verifactu mode
    notes: []const u8 = "",
    payment_terms: []const u8 = "",

    // VeriFactu compliance fields (Spanish e-invoicing)
    verifactu_hash: ?[]const u8 = null, // Hash signature (huella) to display on invoice
    verifactu_series: ?[]const u8 = null, // Invoice series (A, B, etc.)
    verifactu_nif: ?[]const u8 = null, // Tax ID (NIF) for verification
    verifactu_timestamp: ?[]const u8 = null, // Timestamp of hash chain registration

    // Crypto payment fields
    crypto_wallet: ?[]const u8 = null, // Recipient wallet address for payment
    crypto_network: crypto_receipt.Network = .bitcoin, // Blockchain network
    crypto_amount: ?f64 = null, // Optional: exact crypto amount to request
    crypto_sender_wallet: ?[]const u8 = null, // Optional: sender wallet for receipt/confirmation
    show_crypto_identicons: bool = false, // Show blockie identicons for wallet addresses
    crypto_custom_symbol: ?[]const u8 = null, // Custom token symbol (overrides network default)

    // Styling
    primary_color: []const u8 = "#b39a7d",
    secondary_color: []const u8 = "#2c3e50",
    title_color: []const u8 = "#b39a7d",
    company_name_color: []const u8 = "#1a1a1a",
    font_family: []const u8 = "Helvetica",
    template_style: TemplateStyle = .professional,

    // Layout adjustments (in points)
    logo_x: f32 = 40,
    logo_y: f32 = 750,
    logo_width: f32 = 80,
    logo_height: f32 = 50,

    // Branding
    show_branding: bool = true, // Show "Generated by Quantum Quote" with link
    branding_url: []const u8 = "https://quantumencoding.io/software/quantum-quote",

    // Payment Button (clickable link in PDF)
    payment_button_url: ?[]const u8 = null, // e.g., "https://checkout.stripe.com/pay/cs_live_abc123"
    payment_button_label: []const u8 = "Pay Now", // Button text
    payment_button_color: []const u8 = "#635BFF", // Stripe purple default
    payment_button_text_color: []const u8 = "#FFFFFF", // White text default
};

// =============================================================================
// Invoice Renderer
// =============================================================================

pub const InvoiceRenderer = struct {
    allocator: std.mem.Allocator,
    doc: document.PdfDocument,
    data: InvoiceData,

    // Decoded images (need to track for cleanup)
    logo_decoded: ?[]u8 = null,
    qr_decoded: ?[]u8 = null,
    logo_pixels: ?[]u8 = null,
    qr_pixels: ?[]u8 = null,

    // Crypto-generated images (native QR and identicons)
    crypto_qr_pixels: ?[]u8 = null,
    recipient_identicon_pixels: ?[]u8 = null,
    sender_identicon_pixels: ?[]u8 = null,

    // Page state
    current_y: f32 = 0,
    margin_left: f32 = 40,
    margin_right: f32 = 40,
    margin_top: f32 = 40,
    margin_bottom: f32 = 60,
    page_width: f32 = document.A4_WIDTH,
    page_height: f32 = document.A4_HEIGHT,

    // Font IDs (will be assigned during init)
    font_regular: []const u8 = "F0",
    font_bold: []const u8 = "F1",

    pub fn init(allocator: std.mem.Allocator, data: InvoiceData) InvoiceRenderer {
        var renderer = InvoiceRenderer{
            .allocator = allocator,
            .doc = document.PdfDocument.init(allocator),
            .data = data,
        };

        // Add fonts based on font_family
        if (std.mem.eql(u8, data.font_family, "Times-Roman") or std.mem.eql(u8, data.font_family, "Times")) {
            renderer.font_regular = renderer.doc.getFontId(.times_roman);
            renderer.font_bold = renderer.doc.getFontId(.times_bold);
        } else if (std.mem.eql(u8, data.font_family, "Courier")) {
            renderer.font_regular = renderer.doc.getFontId(.courier);
            renderer.font_bold = renderer.doc.getFontId(.courier_bold);
        } else {
            // Default to Helvetica
            renderer.font_regular = renderer.doc.getFontId(.helvetica);
            renderer.font_bold = renderer.doc.getFontId(.helvetica_bold);
        }

        renderer.current_y = renderer.page_height - renderer.margin_top;

        return renderer;
    }

    pub fn deinit(self: *InvoiceRenderer) void {
        // For JPEG: decoded_bytes contains the raw JPEG, pixels is null
        // For PNG: decoded_bytes contains the pixel data (same as image.data), pixels is null
        // So we only free decoded_bytes, never pixels (they're the same pointer for PNG)
        if (self.logo_decoded) |d| self.allocator.free(d);
        if (self.qr_decoded) |d| self.allocator.free(d);
        // Note: logo_pixels and qr_pixels are NOT freed - they point to same memory as decoded

        // Free crypto-generated images (these are owned by us, not decoded from base64)
        if (self.crypto_qr_pixels) |p| self.allocator.free(p);
        if (self.recipient_identicon_pixels) |p| self.allocator.free(p);
        if (self.sender_identicon_pixels) |p| self.allocator.free(p);

        self.doc.deinit();
    }

    /// Generate the complete invoice PDF
    pub fn render(self: *InvoiceRenderer) ![]const u8 {
        var content = document.ContentStream.init(self.allocator);
        defer content.deinit();

        // Load images if provided
        var logo_id: ?[]const u8 = null;
        var qr_id: ?[]const u8 = null;

        if (self.data.company_logo_base64) |logo_b64| {
            if (logo_b64.len > 0) {
                const result = image.loadImageFromBase64(self.allocator, logo_b64) catch null;
                if (result) |r| {
                    self.logo_decoded = r.decoded_bytes;
                    if (r.image.format != .jpeg) {
                        self.logo_pixels = @constCast(r.image.data);
                    }
                    logo_id = self.doc.addImage(r.image) catch null;
                }
            }
        }

        // Load QR code - check new field first, fall back to legacy verifactu field
        const qr_b64_data = self.data.qr_base64 orelse self.data.verifactu_qr_base64;
        // Determine effective QR mode
        var effective_qr_mode = self.data.qr_mode;
        if (effective_qr_mode == .none) {
            // Legacy field implies verifactu mode (only if non-empty)
            if (self.data.verifactu_qr_base64) |legacy_qr| {
                if (legacy_qr.len > 0) {
                    effective_qr_mode = .verifactu;
                }
            }
        }

        if (qr_b64_data) |qr_b64| {
            if (qr_b64.len > 0 and effective_qr_mode != .none) {
                const result = image.loadImageFromBase64(self.allocator, qr_b64) catch null;
                if (result) |r| {
                    self.qr_decoded = r.decoded_bytes;
                    if (r.image.format != .jpeg) {
                        self.qr_pixels = @constCast(r.image.data);
                    }
                    qr_id = self.doc.addImage(r.image) catch null;
                }
            }
        }

        // Native crypto QR generation (when crypto_wallet is set and mode is crypto)
        var crypto_qr_id: ?[]const u8 = null;
        var recipient_identicon_id: ?[]const u8 = null;
        var sender_identicon_id: ?[]const u8 = null;

        if (self.data.crypto_wallet) |wallet| {
            if (wallet.len > 0 and (effective_qr_mode == .crypto or self.data.qr_mode == .crypto)) {
                // Set effective mode to crypto if not already
                effective_qr_mode = .crypto;

                // Build crypto payment URI
                const uri = try self.buildCryptoUri(wallet);
                defer self.allocator.free(uri);

                // Generate native QR code
                const qr_config = qrcode.QrConfig{
                    .ec_level = .M,
                    .min_version = 1,
                    .max_version = 10,
                };

                if (qrcode.encodeAndRender(self.allocator, uri, 4, qr_config)) |qr_img| {
                    self.crypto_qr_pixels = qr_img.pixels;
                    const img = document.Image{
                        .width = qr_img.width,
                        .height = qr_img.height,
                        .data = qr_img.pixels,
                        .format = .raw_rgb,
                    };
                    crypto_qr_id = self.doc.addImage(img) catch null;
                    // Use crypto QR if no base64 QR was provided
                    if (qr_id == null) {
                        qr_id = crypto_qr_id;
                    }
                } else |_| {}

                // Generate recipient identicon
                if (self.data.show_crypto_identicons) {
                    if (identicon.generate(self.allocator, wallet, .{ .size = 8, .scale = 8 })) |icon| {
                        self.recipient_identicon_pixels = icon.pixels;
                        const img = document.Image{
                            .width = icon.width,
                            .height = icon.height,
                            .data = icon.pixels,
                            .format = .raw_rgb,
                        };
                        recipient_identicon_id = self.doc.addImage(img) catch null;
                    } else |_| {}
                }
            }
        }

        // Generate sender identicon if address provided and identicons enabled
        if (self.data.crypto_sender_wallet) |sender| {
            if (sender.len > 0 and self.data.show_crypto_identicons) {
                if (identicon.generate(self.allocator, sender, .{ .size = 8, .scale = 8 })) |icon| {
                    self.sender_identicon_pixels = icon.pixels;
                    const img = document.Image{
                        .width = icon.width,
                        .height = icon.height,
                        .data = icon.pixels,
                        .format = .raw_rgb,
                    };
                    sender_identicon_id = self.doc.addImage(img) catch null;
                } else |_| {}
            }
        }

        const primary = document.Color.fromHex(self.data.primary_color);
        const secondary = document.Color.fromHex(self.data.secondary_color);
        const title_color = document.Color.fromHex(self.data.title_color);
        const company_color = document.Color.fromHex(self.data.company_name_color);

        // Usable width
        const usable_width = self.page_width - self.margin_left - self.margin_right;

        // =====================================================================
        // Header Section
        // =====================================================================

        // Logo (if available)
        if (logo_id) |lid| {
            try content.drawImage(lid, self.data.logo_x, self.data.logo_y, self.data.logo_width, self.data.logo_height);
        }

        // Document title (INVOICE / QUOTE)
        const doc_title = if (std.mem.eql(u8, self.data.document_type, "quote")) "QUOTE" else "INVOICE";
        try content.drawText(doc_title, self.page_width - self.margin_right - 120, self.page_height - self.margin_top, self.font_bold, 28, title_color);

        self.current_y = self.page_height - self.margin_top - 50;

        // Company name
        try content.drawText(self.data.company_name, self.margin_left, self.current_y, self.font_bold, 16, company_color);
        self.current_y -= 18;

        // Company address (multi-line)
        if (self.data.company_address.len > 0) {
            var line_iter = std.mem.splitSequence(u8, self.data.company_address, ", ");
            while (line_iter.next()) |line| {
                try content.drawText(line, self.margin_left, self.current_y, self.font_regular, 10, document.Color.black);
                self.current_y -= 13;
            }
        }

        // Company VAT
        if (self.data.company_vat.len > 0) {
            var vat_buf: [64]u8 = undefined;
            const vat_line = std.fmt.bufPrint(&vat_buf, "VAT: {s}", .{self.data.company_vat}) catch self.data.company_vat;
            try content.drawText(vat_line, self.margin_left, self.current_y, self.font_regular, 10, document.Color.black);
            self.current_y -= 18;
        }

        // =====================================================================
        // Invoice Details (right side)
        // =====================================================================

        const details_x = self.page_width - self.margin_right - 180;
        var details_y = self.page_height - self.margin_top - 50;

        // Invoice number
        try content.drawText("Invoice #:", details_x, details_y, self.font_bold, 10, document.Color.black);
        try content.drawText(self.data.invoice_number, details_x + 70, details_y, self.font_regular, 10, document.Color.black);
        details_y -= 15;

        // Date
        try content.drawText("Date:", details_x, details_y, self.font_bold, 10, document.Color.black);
        try content.drawText(self.data.invoice_date, details_x + 70, details_y, self.font_regular, 10, document.Color.black);
        details_y -= 15;

        // Due date
        if (self.data.due_date.len > 0) {
            try content.drawText("Due Date:", details_x, details_y, self.font_bold, 10, document.Color.black);
            try content.drawText(self.data.due_date, details_x + 70, details_y, self.font_regular, 10, document.Color.black);
        }

        // =====================================================================
        // Client Section
        // =====================================================================

        self.current_y -= 30;

        // "Bill To" header
        try content.drawText("Bill To:", self.margin_left, self.current_y, self.font_bold, 12, primary);
        self.current_y -= 18;

        // Client name
        try content.drawText(self.data.client_name, self.margin_left, self.current_y, self.font_bold, 11, document.Color.black);
        self.current_y -= 14;

        // Client address
        if (self.data.client_address.len > 0) {
            var addr_iter = std.mem.splitSequence(u8, self.data.client_address, ", ");
            while (addr_iter.next()) |line| {
                try content.drawText(line, self.margin_left, self.current_y, self.font_regular, 10, document.Color.black);
                self.current_y -= 13;
            }
        }

        // Client VAT
        if (self.data.client_vat.len > 0) {
            var cvat_buf: [64]u8 = undefined;
            const cvat_line = std.fmt.bufPrint(&cvat_buf, "VAT: {s}", .{self.data.client_vat}) catch self.data.client_vat;
            try content.drawText(cvat_line, self.margin_left, self.current_y, self.font_regular, 10, document.Color.black);
            self.current_y -= 18;
        }

        // =====================================================================
        // Items Table
        // =====================================================================

        self.current_y -= 20;

        // Table header background
        try content.drawRect(self.margin_left, self.current_y - 5, usable_width, 22, primary, null);

        // Table header text
        const col_desc = self.margin_left + 5;
        const col_qty = self.margin_left + 280;
        const col_price = self.margin_left + 350;
        const col_total = self.margin_left + 450;

        try content.drawText("Description", col_desc, self.current_y, self.font_bold, 10, document.Color.white);
        try content.drawText("Qty", col_qty, self.current_y, self.font_bold, 10, document.Color.white);
        try content.drawText("Unit Price", col_price, self.current_y, self.font_bold, 10, document.Color.white);
        try content.drawText("Total", col_total, self.current_y, self.font_bold, 10, document.Color.white);

        self.current_y -= 28;

        // Table rows - with text wrapping for descriptions
        const desc_col_width = col_qty - col_desc - 10; // Description column width with padding
        const line_height: f32 = 12; // Height per line of text
        const row_padding: f32 = 6; // Padding above/below text in row

        // Get font enum for text measurement
        const font_enum = if (std.mem.eql(u8, self.data.font_family, "Times-Roman") or std.mem.eql(u8, self.data.font_family, "Times"))
            document.Font.times_roman
        else if (std.mem.eql(u8, self.data.font_family, "Courier"))
            document.Font.courier
        else
            document.Font.helvetica;

        if (self.data.display_mode == .itemized) {
            for (self.data.items, 0..) |item, i| {
                // Wrap description text to fit column width
                var wrapped = try document.wrapText(self.allocator, item.description, font_enum, 9, desc_col_width);
                defer wrapped.deinit();

                const num_lines = @max(1, wrapped.lines.len);
                const row_height = @as(f32, @floatFromInt(num_lines)) * line_height + row_padding;

                // Alternate row background - sized for wrapped text
                if (i % 2 == 0) {
                    try content.drawRect(self.margin_left, self.current_y - row_height + line_height, usable_width, row_height, document.Color.fromHex("#f5f5f5"), null);
                }

                // Draw wrapped description lines
                var desc_y = self.current_y;
                for (wrapped.lines) |line| {
                    try content.drawText(line, col_desc, desc_y, self.font_regular, 9, document.Color.black);
                    desc_y -= line_height;
                }

                // Draw qty/price/total on first line (aligned with top of description)
                var qty_buf: [16]u8 = undefined;
                const qty_str = std.fmt.bufPrint(&qty_buf, "{d:.0}", .{item.quantity}) catch "0";
                try content.drawText(qty_str, col_qty, self.current_y, self.font_regular, 9, document.Color.black);

                var price_buf: [24]u8 = undefined;
                const price_str = std.fmt.bufPrint(&price_buf, "{d:.2}", .{item.unit_price}) catch "0.00";
                try content.drawText(price_str, col_price, self.current_y, self.font_regular, 9, document.Color.black);

                var total_buf: [24]u8 = undefined;
                const total_str = std.fmt.bufPrint(&total_buf, "{d:.2}", .{item.total}) catch "0.00";
                try content.drawText(total_str, col_total, self.current_y, self.font_regular, 9, document.Color.black);

                self.current_y -= row_height + 2; // Move down by row height plus small gap

                // Check if we need a new page
                if (self.current_y < self.margin_bottom + 100) {
                    // Would need multi-page support here
                    break;
                }
            }
        } else {
            // Blackbox mode - wrap description text
            var wrapped = try document.wrapText(self.allocator, self.data.blackbox_description, font_enum, 9, desc_col_width);
            defer wrapped.deinit();

            const num_lines = @max(1, wrapped.lines.len);
            const row_height = @as(f32, @floatFromInt(num_lines)) * line_height + row_padding;

            try content.drawRect(self.margin_left, self.current_y - row_height + line_height, usable_width, row_height, document.Color.fromHex("#f5f5f5"), null);

            // Draw wrapped description lines
            var desc_y = self.current_y;
            for (wrapped.lines) |line| {
                try content.drawText(line, col_desc, desc_y, self.font_regular, 9, document.Color.black);
                desc_y -= line_height;
            }

            var total_buf: [24]u8 = undefined;
            const total_str = std.fmt.bufPrint(&total_buf, "{d:.2}", .{self.data.subtotal}) catch "0.00";
            try content.drawText(total_str, col_total, self.current_y, self.font_regular, 9, document.Color.black);

            self.current_y -= row_height + 2;
        }

        // =====================================================================
        // Totals Section
        // =====================================================================

        self.current_y -= 20;

        // Separator line
        try content.drawLine(col_price - 20, self.current_y + 15, self.page_width - self.margin_right, self.current_y + 15, secondary, 0.5);

        // Subtotal
        try content.drawText("Subtotal:", col_price, self.current_y, self.font_regular, 10, document.Color.black);
        var subtotal_buf: [24]u8 = undefined;
        const subtotal_str = std.fmt.bufPrint(&subtotal_buf, "{d:.2}", .{self.data.subtotal}) catch "0.00";
        try content.drawText(subtotal_str, col_total, self.current_y, self.font_regular, 10, document.Color.black);
        self.current_y -= 16;

        // Tax
        var tax_label_buf: [32]u8 = undefined;
        const tax_pct = self.data.tax_rate * 100;
        const tax_label = std.fmt.bufPrint(&tax_label_buf, "Tax ({d:.0}%):", .{tax_pct}) catch "Tax:";
        try content.drawText(tax_label, col_price, self.current_y, self.font_regular, 10, document.Color.black);
        var tax_buf: [24]u8 = undefined;
        const tax_str = std.fmt.bufPrint(&tax_buf, "{d:.2}", .{self.data.tax_amount}) catch "0.00";
        try content.drawText(tax_str, col_total, self.current_y, self.font_regular, 10, document.Color.black);
        self.current_y -= 28; // Extra spacing before TOTAL row

        // Total (highlighted) - width calculated to align with table right edge
        const total_bar_x = col_price - 10;
        const table_right_edge = self.margin_left + usable_width;
        const total_bar_width = table_right_edge - total_bar_x;
        try content.drawRect(total_bar_x, self.current_y - 5, total_bar_width, 22, primary, null);
        try content.drawText("TOTAL:", col_price, self.current_y, self.font_bold, 12, document.Color.white);
        var grand_total_buf: [24]u8 = undefined;
        const grand_total_str = std.fmt.bufPrint(&grand_total_buf, "{d:.2}", .{self.data.total}) catch "0.00";
        try content.drawText(grand_total_str, col_total, self.current_y, self.font_bold, 12, document.Color.white);

        // =====================================================================
        // Footer Section - Notes/Payment Terms then QR Code below
        // =====================================================================

        self.current_y -= 30;

        // Notes (full width with text wrapping)
        const notes_max_width = usable_width - 10; // Full width minus small padding

        if (self.data.notes.len > 0) {
            try content.drawText("Notes:", self.margin_left, self.current_y, self.font_bold, 10, secondary);
            self.current_y -= 14;

            // Wrap notes text
            var notes_wrapped = try document.wrapText(self.allocator, self.data.notes, font_enum, 9, notes_max_width);
            defer notes_wrapped.deinit();

            for (notes_wrapped.lines) |line| {
                try content.drawText(line, self.margin_left, self.current_y, self.font_regular, 9, document.Color.black);
                self.current_y -= 12;
            }
            self.current_y -= 6; // Extra spacing after notes
        }

        // Payment terms (full width with text wrapping)
        if (self.data.payment_terms.len > 0) {
            try content.drawText("Payment Terms:", self.margin_left, self.current_y, self.font_bold, 10, secondary);
            self.current_y -= 14;

            // Wrap payment terms text
            var terms_wrapped = try document.wrapText(self.allocator, self.data.payment_terms, font_enum, 9, notes_max_width);
            defer terms_wrapped.deinit();

            for (terms_wrapped.lines) |line| {
                try content.drawText(line, self.margin_left, self.current_y, self.font_regular, 9, document.Color.black);
                self.current_y -= 12;
            }
            self.current_y -= 8; // Extra spacing after payment terms
        }

        // =====================================================================
        // Crypto Payment Section (with optional identicons)
        // =====================================================================
        if (self.data.crypto_wallet) |wallet| {
            if (wallet.len > 0) {
                self.current_y -= 10;

                // Section header with network color
                const network_color = document.Color.fromHex(self.data.crypto_network.color());
                const network_name = self.data.crypto_network.displayName();
                const symbol = self.data.crypto_custom_symbol orelse self.data.crypto_network.symbol();

                var header_buf: [64]u8 = undefined;
                const header_text = std.fmt.bufPrint(&header_buf, "Pay with {s} ({s})", .{ network_name, symbol }) catch "Crypto Payment";
                try content.drawText(header_text, self.margin_left, self.current_y, self.font_bold, 11, network_color);
                self.current_y -= 18;

                // Recipient wallet address with optional identicon
                const identicon_size: f32 = 24;
                const addr_x = if (recipient_identicon_id != null) self.margin_left + identicon_size + 8 else self.margin_left;

                if (recipient_identicon_id) |icon_id| {
                    try content.drawImage(icon_id, self.margin_left, self.current_y - identicon_size + 10, identicon_size, identicon_size);
                }

                try content.drawText("To:", addr_x, self.current_y, self.font_bold, 9, secondary);
                self.current_y -= 12;

                // Show truncated address
                const truncated = truncateAddress(wallet, 10, 8);
                try content.drawText(&truncated, addr_x, self.current_y, self.font_regular, 9, document.Color.black);
                self.current_y -= 14;

                // Full address in smaller font (for verification)
                try content.drawText(wallet, addr_x, self.current_y, self.font_regular, 7, document.Color.fromHex("#666666"));
                self.current_y -= 16;

                // Sender wallet (if provided) with optional identicon
                if (self.data.crypto_sender_wallet) |sender| {
                    if (sender.len > 0) {
                        const sender_x = if (sender_identicon_id != null) self.margin_left + identicon_size + 8 else self.margin_left;

                        if (sender_identicon_id) |icon_id| {
                            try content.drawImage(icon_id, self.margin_left, self.current_y - identicon_size + 10, identicon_size, identicon_size);
                        }

                        try content.drawText("From:", sender_x, self.current_y, self.font_bold, 9, secondary);
                        self.current_y -= 12;

                        const sender_truncated = truncateAddress(sender, 10, 8);
                        try content.drawText(&sender_truncated, sender_x, self.current_y, self.font_regular, 9, document.Color.black);
                        self.current_y -= 18;
                    }
                }

                // Crypto amount if specified
                if (self.data.crypto_amount) |amount| {
                    var amount_buf: [64]u8 = undefined;
                    const amount_text = std.fmt.bufPrint(&amount_buf, "Amount: {d:.8} {s}", .{ amount, symbol }) catch "Amount: [error]";
                    try content.drawText(amount_text, self.margin_left, self.current_y, self.font_bold, 10, network_color);
                    self.current_y -= 20;
                }
            }
        }

        // QR Code - positioned below notes, right-aligned with table
        if (qr_id) |qid| {
            const qr_size: f32 = 80; // ~28mm for good scannability
            const qr_padding: f32 = 15;

            // Right edge aligns with table right edge
            const qr_x = table_right_edge - qr_size;
            const qr_y = self.current_y - qr_size - qr_padding;

            try content.drawImage(qid, qr_x, qr_y, qr_size, qr_size);

            // Label below QR code - use custom label if provided, otherwise default by mode
            const qr_label: []const u8 = if (self.data.qr_label) |custom_label|
                if (custom_label.len > 0) custom_label else switch (effective_qr_mode) {
                    .verifactu => "VeriFactu",
                    .payment_link => "Scan to Pay",
                    .bank_details => "Bank Details",
                    .verification => "Verify Invoice",
                    .crypto => "Crypto Payment",
                    .none => "",
                }
            else switch (effective_qr_mode) {
                .verifactu => "VeriFactu",
                .payment_link => "Scan to Pay",
                .bank_details => "Bank Details",
                .verification => "Verify Invoice",
                .crypto => "Crypto Payment",
                .none => "",
            };

            if (qr_label.len > 0) {
                // Center label under QR (approximate centering based on label length)
                const label_width: f32 = @as(f32, @floatFromInt(qr_label.len)) * 4.5;
                const label_x = qr_x + (qr_size / 2) - (label_width / 2);
                try content.drawText(qr_label, label_x, qr_y - 10, self.font_bold, 9, primary);
            }

            // Payment button next to QR code (if URL provided)
            if (self.data.payment_button_url) |btn_url| {
                const btn_width: f32 = 100;
                const btn_height: f32 = 30;
                const btn_x = qr_x - btn_width - 15; // Left of QR code with spacing
                const btn_y = qr_y + (qr_size - btn_height) / 2; // Vertically centered with QR

                // Parse button colors
                const btn_bg = document.Color.fromHex(self.data.payment_button_color);
                const btn_text_color = document.Color.fromHex(self.data.payment_button_text_color);

                // Draw the button and get its bounds
                const bounds = try content.drawButton(
                    self.data.payment_button_label,
                    btn_x,
                    btn_y,
                    btn_width,
                    btn_height,
                    self.font_bold,
                    11,
                    btn_bg,
                    btn_text_color,
                    6, // border radius
                );

                // Add clickable link annotation
                try self.doc.addLinkAnnotation(bounds.x1, bounds.y1, bounds.x2, bounds.y2, btn_url);
            }

            // Update current_y to account for QR placement
            self.current_y = qr_y - 25;
        } else if (self.data.payment_button_url) |btn_url| {
            // No QR code but payment button requested - show button standalone
            const btn_width: f32 = 120;
            const btn_height: f32 = 35;
            const btn_x = table_right_edge - btn_width;
            const btn_y = self.current_y - btn_height - 15;

            // Parse button colors
            const btn_bg = document.Color.fromHex(self.data.payment_button_color);
            const btn_text_color = document.Color.fromHex(self.data.payment_button_text_color);

            // Draw the button and get its bounds
            const bounds = try content.drawButton(
                self.data.payment_button_label,
                btn_x,
                btn_y,
                btn_width,
                btn_height,
                self.font_bold,
                12,
                btn_bg,
                btn_text_color,
                6, // border radius
            );

            // Add clickable link annotation
            try self.doc.addLinkAnnotation(bounds.x1, bounds.y1, bounds.x2, bounds.y2, btn_url);

            // "Click to Pay" label below button
            const label_text = "Click to Pay Online";
            const lbl_width: f32 = @as(f32, @floatFromInt(label_text.len)) * 4.0;
            const lbl_x = btn_x + (btn_width - lbl_width) / 2;
            try content.drawText(label_text, lbl_x, btn_y - 12, self.font_regular, 8, secondary);

            self.current_y = btn_y - 30;
        }

        // Footer line - fixed position near bottom
        try content.drawLine(self.margin_left, self.margin_bottom - 10, self.page_width - self.margin_right, self.margin_bottom - 10, secondary, 0.5);

        // Footer text - varies by QR mode
        if (qr_id != null) {
            const footer_label: []const u8 = switch (effective_qr_mode) {
                .verifactu => "VeriFactu Compliant Invoice",
                .payment_link => "Scan QR to Pay Online",
                .bank_details => "Bank Transfer Details Above",
                .verification => "Scan to Verify Invoice",
                .crypto => "Cryptocurrency Payment Accepted",
                .none => "",
            };
            if (footer_label.len > 0) {
                try content.drawText(footer_label, self.margin_left, self.margin_bottom - 25, self.font_regular, 8, secondary);
            }

            // VeriFactu: Display hash signature (huella) in footer
            if (effective_qr_mode == .verifactu) {
                if (self.data.verifactu_hash) |hash| {
                    if (hash.len > 0) {
                        // Show truncated hash (first 16 chars as per VeriFactu QR standard)
                        const hash_display = if (hash.len > 16) hash[0..16] else hash;
                        // Format: "Huella: XXXXXXXXXXXXXXXX"
                        var hash_buf: [32]u8 = undefined;
                        const hash_text = std.fmt.bufPrint(&hash_buf, "Huella: {s}...", .{hash_display}) catch "Huella: [error]";
                        try content.drawText(hash_text, self.margin_left, self.margin_bottom - 38, self.font_regular, 7, secondary);
                    }
                }

                // Display series and NIF if available
                if (self.data.verifactu_series) |series| {
                    if (series.len > 0) {
                        var series_buf: [32]u8 = undefined;
                        const series_text = std.fmt.bufPrint(&series_buf, "Serie: {s}", .{series}) catch "Serie: [error]";
                        try content.drawText(series_text, self.margin_left + 180, self.margin_bottom - 38, self.font_regular, 7, secondary);
                    }
                }

                if (self.data.verifactu_nif) |nif| {
                    if (nif.len > 0) {
                        var nif_buf: [32]u8 = undefined;
                        const nif_text = std.fmt.bufPrint(&nif_buf, "NIF: {s}", .{nif}) catch "NIF: [error]";
                        try content.drawText(nif_text, self.margin_left + 250, self.margin_bottom - 38, self.font_regular, 7, secondary);
                    }
                }
            }

            try content.drawText("Thank you for your business", self.page_width - self.margin_right - 130, self.margin_bottom - 25, self.font_regular, 9, secondary);
        } else {
            try content.drawText("Thank you for your business", self.page_width / 2 - 60, self.margin_bottom - 25, self.font_regular, 9, secondary);
        }

        // Branding footer with clickable link
        if (self.data.show_branding) {
            const branding_text = "Generated by Quantum Quote";
            const branding_font_size: f32 = 7;
            const branding_y = self.margin_bottom - 45;

            // Calculate text width for link annotation (approx 4.2 points per char at size 7)
            const text_width: f32 = @as(f32, @floatFromInt(branding_text.len)) * 4.2;

            // Draw centered branding text in subtle gray
            const branding_x = (self.page_width - text_width) / 2;
            const branding_color = document.Color{ .r = 0.6, .g = 0.6, .b = 0.6 }; // Light gray
            try content.drawText(branding_text, branding_x, branding_y, self.font_regular, branding_font_size, branding_color);

            // Add clickable link annotation (PDF coordinates: x1, y1, x2, y2)
            try self.doc.addLinkAnnotation(
                branding_x,
                branding_y - 2, // Slight padding below text
                branding_x + text_width,
                branding_y + branding_font_size + 2, // Slight padding above text
                self.data.branding_url,
            );
        }

        // Add page to document
        try self.doc.addPage(&content);

        // Build and return PDF
        return try self.doc.build();
    }

    /// Build cryptocurrency payment URI for QR code
    /// Supports BIP21 (Bitcoin), EIP681 (Ethereum/ERC20), and other chain-specific formats
    fn buildCryptoUri(self: *InvoiceRenderer, wallet: []const u8) ![]u8 {
        const network = self.data.crypto_network;
        const symbol = self.data.crypto_custom_symbol orelse network.symbol();

        // Buffer for URI construction
        var uri_buf: [512]u8 = undefined;

        // Determine URI scheme based on network
        const uri_str: []const u8 = switch (network) {
            .bitcoin => blk: {
                // BIP21: bitcoin:<address>?amount=<amount>&label=<label>
                if (self.data.crypto_amount) |amount| {
                    break :blk std.fmt.bufPrint(&uri_buf, "bitcoin:{s}?amount={d:.8}", .{ wallet, amount }) catch "bitcoin:error";
                } else {
                    break :blk std.fmt.bufPrint(&uri_buf, "bitcoin:{s}", .{wallet}) catch "bitcoin:error";
                }
            },
            .ethereum, .polygon, .bnb => blk: {
                // EIP681: ethereum:<address>[@chainId]?value=<wei>
                const chain_id: u32 = switch (network) {
                    .ethereum => 1,
                    .polygon => 137,
                    .bnb => 56,
                    else => 1,
                };
                if (self.data.crypto_amount) |amount| {
                    // Convert to wei (1 ETH = 10^18 wei)
                    const wei: u64 = @intFromFloat(amount * 1e18);
                    break :blk std.fmt.bufPrint(&uri_buf, "ethereum:{s}@{d}?value={d}", .{ wallet, chain_id, wei }) catch "ethereum:error";
                } else {
                    break :blk std.fmt.bufPrint(&uri_buf, "ethereum:{s}@{d}", .{ wallet, chain_id }) catch "ethereum:error";
                }
            },
            .litecoin => blk: {
                // Similar to BIP21
                if (self.data.crypto_amount) |amount| {
                    break :blk std.fmt.bufPrint(&uri_buf, "litecoin:{s}?amount={d:.8}", .{ wallet, amount }) catch "litecoin:error";
                } else {
                    break :blk std.fmt.bufPrint(&uri_buf, "litecoin:{s}", .{wallet}) catch "litecoin:error";
                }
            },
            .dogecoin => blk: {
                if (self.data.crypto_amount) |amount| {
                    break :blk std.fmt.bufPrint(&uri_buf, "dogecoin:{s}?amount={d:.8}", .{ wallet, amount }) catch "dogecoin:error";
                } else {
                    break :blk std.fmt.bufPrint(&uri_buf, "dogecoin:{s}", .{wallet}) catch "dogecoin:error";
                }
            },
            .bitcoin_cash => blk: {
                if (self.data.crypto_amount) |amount| {
                    break :blk std.fmt.bufPrint(&uri_buf, "bitcoincash:{s}?amount={d:.8}", .{ wallet, amount }) catch "bitcoincash:error";
                } else {
                    break :blk std.fmt.bufPrint(&uri_buf, "bitcoincash:{s}", .{wallet}) catch "bitcoincash:error";
                }
            },
            .solana => blk: {
                // Solana Pay URL format
                if (self.data.crypto_amount) |amount| {
                    break :blk std.fmt.bufPrint(&uri_buf, "solana:{s}?amount={d:.9}", .{ wallet, amount }) catch "solana:error";
                } else {
                    break :blk std.fmt.bufPrint(&uri_buf, "solana:{s}", .{wallet}) catch "solana:error";
                }
            },
            .tron => blk: {
                // TRON uses tron: scheme
                if (self.data.crypto_amount) |amount| {
                    break :blk std.fmt.bufPrint(&uri_buf, "tron:{s}?amount={d:.6}", .{ wallet, amount }) catch "tron:error";
                } else {
                    break :blk std.fmt.bufPrint(&uri_buf, "tron:{s}", .{wallet}) catch "tron:error";
                }
            },
            .xrp => blk: {
                // XRP Ledger payment format
                if (self.data.crypto_amount) |amount| {
                    break :blk std.fmt.bufPrint(&uri_buf, "xrpl:{s}?amount={d:.6}", .{ wallet, amount }) catch "xrpl:error";
                } else {
                    break :blk std.fmt.bufPrint(&uri_buf, "xrpl:{s}", .{wallet}) catch "xrpl:error";
                }
            },
            .cardano => blk: {
                // Cardano uses web+cardano: scheme
                if (self.data.crypto_amount) |amount| {
                    // Cardano amounts in ADA (6 decimal places = lovelace)
                    break :blk std.fmt.bufPrint(&uri_buf, "web+cardano:{s}?amount={d:.6}", .{ wallet, amount }) catch "cardano:error";
                } else {
                    break :blk std.fmt.bufPrint(&uri_buf, "web+cardano:{s}", .{wallet}) catch "cardano:error";
                }
            },
            .usdt, .usdc => blk: {
                // Stablecoins typically on Ethereum/Tron - use ethereum scheme with token
                // For simplicity, encode as ethereum address (user can specify network via crypto_network)
                break :blk std.fmt.bufPrint(&uri_buf, "ethereum:{s}?token={s}", .{ wallet, symbol }) catch "ethereum:error";
            },
            .lightning => blk: {
                // Lightning Network BOLT11 invoice or LNURL
                break :blk std.fmt.bufPrint(&uri_buf, "lightning:{s}", .{wallet}) catch "lightning:error";
            },
            .custom => blk: {
                // Generic format with custom symbol
                if (self.data.crypto_amount) |amount| {
                    break :blk std.fmt.bufPrint(&uri_buf, "{s}:{s}?amount={d:.8}", .{ symbol, wallet, amount }) catch "custom:error";
                } else {
                    break :blk std.fmt.bufPrint(&uri_buf, "{s}:{s}", .{ symbol, wallet }) catch "custom:error";
                }
            },
        };

        return try self.allocator.dupe(u8, uri_str);
    }

    /// Truncate wallet address for display (show first and last N chars)
    fn truncateAddress(address: []const u8, comptime prefix_len: usize, comptime suffix_len: usize) [prefix_len + 3 + suffix_len]u8 {
        var result: [prefix_len + 3 + suffix_len]u8 = undefined;
        if (address.len <= prefix_len + suffix_len + 3) {
            // Address is short enough, pad with spaces
            @memset(&result, ' ');
            @memcpy(result[0..@min(address.len, result.len)], address[0..@min(address.len, result.len)]);
        } else {
            @memcpy(result[0..prefix_len], address[0..prefix_len]);
            result[prefix_len] = '.';
            result[prefix_len + 1] = '.';
            result[prefix_len + 2] = '.';
            @memcpy(result[prefix_len + 3 ..], address[address.len - suffix_len ..]);
        }
        return result;
    }
};

// =============================================================================
// Convenience Function
// =============================================================================

/// Generate invoice PDF from InvoiceData struct
/// Returns an allocator-owned slice that must be freed by the caller.
pub fn generateInvoice(allocator: std.mem.Allocator, data: InvoiceData) ![]u8 {
    var renderer = InvoiceRenderer.init(allocator, data);
    defer renderer.deinit();

    const pdf_output = try renderer.render();

    // Make a copy since the original is owned by renderer.doc
    const result = try allocator.dupe(u8, pdf_output);
    return result;
}

// =============================================================================
// Tests
// =============================================================================

test "generate simple invoice" {
    const allocator = std.testing.allocator;

    const items = [_]LineItem{
        .{ .description = "Web Development", .quantity = 40, .unit_price = 100, .total = 4000 },
        .{ .description = "Consulting", .quantity = 10, .unit_price = 150, .total = 1500 },
    };

    const data = InvoiceData{
        .document_type = "invoice",
        .company_name = "Acme Corp",
        .company_address = "123 Business St, Tech City",
        .company_vat = "ESB12345678",
        .client_name = "Client LLC",
        .client_address = "456 Client Ave",
        .client_vat = "ESB87654321",
        .invoice_number = "INV-2025-001",
        .invoice_date = "2025-11-29",
        .due_date = "2025-12-29",
        .items = &items,
        .subtotal = 5500,
        .tax_rate = 0.21,
        .tax_amount = 1155,
        .total = 6655,
        .notes = "Thank you for your business!",
        .payment_terms = "Payment due within 30 days",
    };

    const pdf_bytes = try generateInvoice(allocator, data);
    defer allocator.free(pdf_bytes);

    try std.testing.expect(pdf_bytes.len > 500);
    try std.testing.expect(std.mem.startsWith(u8, pdf_bytes, "%PDF-1.4"));
}

test "generate crypto payment invoice with identicons" {
    const allocator = std.testing.allocator;

    const items = [_]LineItem{
        .{ .description = "Software Development", .quantity = 1, .unit_price = 5000, .total = 5000 },
    };

    const data = InvoiceData{
        .document_type = "invoice",
        .company_name = "Quantum Labs",
        .company_address = "789 Blockchain Ave, Crypto City",
        .client_name = "DeFi Protocol Inc",
        .client_address = "123 Smart Contract Blvd",
        .invoice_number = "CRYPTO-2026-001",
        .invoice_date = "2026-01-04",
        .due_date = "2026-01-14",
        .items = &items,
        .subtotal = 5000,
        .tax_rate = 0,
        .tax_amount = 0,
        .total = 5000,
        .notes = "Payment accepted in cryptocurrency",
        .payment_terms = "Payment due within 10 days",

        // Crypto payment options
        .qr_mode = .crypto,
        .crypto_wallet = "0x742d35Cc6634C0532925a3b844Bc9e7595f7ABCD",
        .crypto_network = .ethereum,
        .crypto_amount = 2.5,
        .crypto_sender_wallet = "0x8ba1f109551bD432803012645Ac136ddd64DBA72",
        .show_crypto_identicons = true,
        .primary_color = "#627eea", // Ethereum blue
    };

    const pdf_bytes = try generateInvoice(allocator, data);
    defer allocator.free(pdf_bytes);

    // Verify PDF structure
    try std.testing.expect(pdf_bytes.len > 5000); // Should be larger due to embedded images
    try std.testing.expect(std.mem.startsWith(u8, pdf_bytes, "%PDF-1.4"));
    try std.testing.expect(std.mem.endsWith(u8, pdf_bytes, "%%EOF\n"));

    // Verify crypto-related content
    try std.testing.expect(std.mem.indexOf(u8, pdf_bytes, "Ethereum") != null);
    try std.testing.expect(std.mem.indexOf(u8, pdf_bytes, "0x742d35Cc") != null);
}

test "generate bitcoin invoice with QR" {
    const allocator = std.testing.allocator;

    const items = [_]LineItem{
        .{ .description = "Consulting Services", .quantity = 10, .unit_price = 100, .total = 1000 },
    };

    const data = InvoiceData{
        .document_type = "invoice",
        .company_name = "BTC Consulting",
        .company_address = "Satoshi Street 21",
        .client_name = "Hodler LLC",
        .invoice_number = "BTC-001",
        .invoice_date = "2026-01-04",
        .items = &items,
        .subtotal = 1000,
        .total = 1000,

        // Bitcoin payment
        .qr_mode = .crypto,
        .crypto_wallet = "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh",
        .crypto_network = .bitcoin,
        .crypto_amount = 0.015,
        .show_crypto_identicons = false,
        .primary_color = "#f7931a", // Bitcoin orange
    };

    const pdf_bytes = try generateInvoice(allocator, data);
    defer allocator.free(pdf_bytes);

    try std.testing.expect(pdf_bytes.len > 2000);
    try std.testing.expect(std.mem.startsWith(u8, pdf_bytes, "%PDF-1.4"));
    try std.testing.expect(std.mem.indexOf(u8, pdf_bytes, "Bitcoin") != null);
}

test "generate multi-chain invoice - Solana" {
    const allocator = std.testing.allocator;

    const items = [_]LineItem{
        .{ .description = "NFT Minting", .quantity = 100, .unit_price = 5, .total = 500 },
    };

    const data = InvoiceData{
        .document_type = "invoice",
        .company_name = "Solana NFT Studio",
        .client_name = "NFT Collector",
        .invoice_number = "SOL-001",
        .invoice_date = "2026-01-04",
        .items = &items,
        .subtotal = 500,
        .total = 500,
        .qr_mode = .crypto,
        .crypto_wallet = "7EcDhSYGxXyscszYEp35KHN8vvw3svAuLKTzXwCFLtV",
        .crypto_network = .solana,
        .crypto_amount = 2.5,
        .primary_color = "#9945ff", // Solana purple
    };

    const pdf_bytes = try generateInvoice(allocator, data);
    defer allocator.free(pdf_bytes);

    try std.testing.expect(pdf_bytes.len > 2000);
    try std.testing.expect(std.mem.indexOf(u8, pdf_bytes, "Solana") != null);
}
