//! Safe Rust bindings for the zig-lens source code analysis library.
//!
//! # Quick Start
//!
//! ```no_run
//! use zig_lens_sys::ZigLens;
//!
//! let result = ZigLens::analyze_path("./src", Format::Json, None).unwrap();
//! println!("{}", result.as_str());
//! ```
//!
//! # Building
//!
//! The zig-lens static library must be built first:
//! ```bash
//! cd programs/zig_lens && zig build lib
//! ```

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// Raw FFI bindings generated by bindgen
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

use std::ffi::{CStr, CString};
use std::os::raw::c_int;

// Re-export format constants
pub const FORMAT_JSON: c_int = ZIG_LENS_FORMAT_JSON as c_int;
pub const FORMAT_COMPACT: c_int = ZIG_LENS_FORMAT_COMPACT as c_int;
pub const FORMAT_TERMINAL: c_int = ZIG_LENS_FORMAT_TERMINAL as c_int;
pub const FORMAT_MARKDOWN: c_int = ZIG_LENS_FORMAT_MARKDOWN as c_int;
pub const FORMAT_DOT: c_int = ZIG_LENS_FORMAT_DOT as c_int;

// Re-export language constants
pub const LANG_ZIG: c_int = ZIG_LENS_LANG_ZIG as c_int;
pub const LANG_RUST: c_int = ZIG_LENS_LANG_RUST as c_int;
pub const LANG_C: c_int = ZIG_LENS_LANG_C as c_int;
pub const LANG_PYTHON: c_int = ZIG_LENS_LANG_PYTHON as c_int;
pub const LANG_JAVASCRIPT: c_int = ZIG_LENS_LANG_JAVASCRIPT as c_int;

/// Output format for analysis results.
#[derive(Debug, Clone, Copy)]
pub enum Format {
    Json,
    Compact,
    Terminal,
    Markdown,
    Dot,
}

impl Format {
    fn as_c_int(self) -> c_int {
        match self {
            Format::Json => FORMAT_JSON,
            Format::Compact => FORMAT_COMPACT,
            Format::Terminal => FORMAT_TERMINAL,
            Format::Markdown => FORMAT_MARKDOWN,
            Format::Dot => FORMAT_DOT,
        }
    }
}

/// Language of source code for in-memory analysis.
#[derive(Debug, Clone, Copy)]
pub enum Language {
    Zig,
    Rust,
    C,
    Python,
    JavaScript,
}

impl Language {
    fn as_c_int(self) -> c_int {
        match self {
            Language::Zig => LANG_ZIG,
            Language::Rust => LANG_RUST,
            Language::C => LANG_C,
            Language::Python => LANG_PYTHON,
            Language::JavaScript => LANG_JAVASCRIPT,
        }
    }
}

/// Error type for zig-lens operations.
#[derive(Debug)]
pub enum Error {
    NullPointer,
    InvalidArgument,
    AnalysisFailed(String),
    IoError(String),
    OutOfMemory,
    InvalidPath,
    Unknown(c_int, String),
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::NullPointer => write!(f, "null pointer"),
            Error::InvalidArgument => write!(f, "invalid argument"),
            Error::AnalysisFailed(msg) => write!(f, "analysis failed: {msg}"),
            Error::IoError(msg) => write!(f, "I/O error: {msg}"),
            Error::OutOfMemory => write!(f, "out of memory"),
            Error::InvalidPath => write!(f, "invalid path (contains null byte)"),
            Error::Unknown(code, msg) => write!(f, "unknown error ({code}): {msg}"),
        }
    }
}

impl std::error::Error for Error {}

pub type Result<T> = std::result::Result<T, Error>;

/// RAII wrapper for buffers allocated by zig-lens.
/// Automatically freed on drop via `zig_lens_free_buffer`.
pub struct ZigLensBuf {
    ptr: *mut u8,
    len: usize,
}

impl ZigLensBuf {
    /// View the buffer as a UTF-8 string slice.
    pub fn as_str(&self) -> &str {
        // zig-lens always produces valid UTF-8 (JSON, Markdown, terminal output)
        unsafe { std::str::from_utf8_unchecked(std::slice::from_raw_parts(self.ptr, self.len)) }
    }

    /// View the buffer as raw bytes.
    pub fn as_bytes(&self) -> &[u8] {
        unsafe { std::slice::from_raw_parts(self.ptr, self.len) }
    }

    /// Get the byte length.
    pub fn len(&self) -> usize {
        self.len
    }

    /// Check if the buffer is empty.
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    /// Convert to an owned String, consuming the buffer.
    pub fn into_string(self) -> String {
        let s = self.as_str().to_owned();
        // Drop will free the original buffer
        s
    }
}

impl Drop for ZigLensBuf {
    fn drop(&mut self) {
        if !self.ptr.is_null() && self.len > 0 {
            unsafe { zig_lens_free_buffer(self.ptr as *mut i8, self.len) }
        }
    }
}

// ZigLensBuf is Send + Sync because the underlying data is exclusively owned
unsafe impl Send for ZigLensBuf {}
unsafe impl Sync for ZigLensBuf {}

/// Line count result from `count_lines`.
#[derive(Debug, Clone, Copy)]
pub struct LineCount {
    pub total: u32,
    pub blank: u32,
    pub comments: u32,
}

/// Progress callback closure type.
pub type ProgressFn = Box<dyn Fn(i32, &str) + Send>;

// Thread-local storage for progress callback
thread_local! {
    static PROGRESS_CB: std::cell::RefCell<Option<ProgressFn>> = const { std::cell::RefCell::new(None) };
}

/// C-compatible trampoline that reads from thread-local closure.
unsafe extern "C" fn progress_trampoline(percent: c_int, message: *const i8) {
    PROGRESS_CB.with(|cb| {
        if let Some(ref f) = *cb.borrow() {
            let msg = if message.is_null() {
                ""
            } else {
                unsafe { CStr::from_ptr(message) }.to_str().unwrap_or("")
            };
            f(percent as i32, msg);
        }
    });
}

fn get_last_error() -> String {
    let mut buf = [0u8; 512];
    let len = unsafe { zig_lens_get_error(buf.as_mut_ptr() as *mut i8, buf.len()) };
    String::from_utf8_lossy(&buf[..len]).to_string()
}

fn check_result(code: c_int) -> Result<()> {
    match code {
        0 => Ok(()),
        -1 => Err(Error::NullPointer),
        -2 => Err(Error::InvalidArgument),
        -3 => Err(Error::AnalysisFailed(get_last_error())),
        -4 => Err(Error::IoError(get_last_error())),
        -5 => Err(Error::OutOfMemory),
        _ => Err(Error::Unknown(code, get_last_error())),
    }
}

fn with_progress<F, R>(progress: Option<ProgressFn>, f: F) -> R
where
    F: FnOnce(ZigLensProgressCallback) -> R,
{
    let cb = if progress.is_some() {
        PROGRESS_CB.with(|cell| {
            *cell.borrow_mut() = progress;
        });
        Some(progress_trampoline as unsafe extern "C" fn(c_int, *const i8))
    } else {
        None
    };

    let result = f(cb);

    // Clean up thread-local
    PROGRESS_CB.with(|cell| {
        *cell.borrow_mut() = None;
    });

    result
}

/// High-level safe interface to zig-lens.
pub struct ZigLens;

impl ZigLens {
    /// Get the library version string.
    pub fn version() -> &'static str {
        unsafe {
            let ptr = zig_lens_version();
            CStr::from_ptr(ptr).to_str().unwrap_or("unknown")
        }
    }

    /// Analyze a file or directory.
    ///
    /// Returns the analysis result as a buffer in the requested format.
    /// The buffer is automatically freed when dropped.
    pub fn analyze_path(
        path: &str,
        format: Format,
        progress: Option<ProgressFn>,
    ) -> Result<ZigLensBuf> {
        let c_path = CString::new(path).map_err(|_| Error::InvalidPath)?;
        let mut buf_ptr: *mut i8 = std::ptr::null_mut();
        let mut buf_len: usize = 0;

        let code = with_progress(progress, |cb| unsafe {
            zig_lens_analyze_path(
                c_path.as_ptr(),
                format.as_c_int(),
                cb,
                &mut buf_ptr,
                &mut buf_len,
            )
        });

        check_result(code)?;
        Ok(ZigLensBuf {
            ptr: buf_ptr as *mut u8,
            len: buf_len,
        })
    }

    /// Compile an entire codebase into a single Markdown document.
    pub fn compile_codebase(
        path: &str,
        progress: Option<ProgressFn>,
    ) -> Result<ZigLensBuf> {
        let c_path = CString::new(path).map_err(|_| Error::InvalidPath)?;
        let mut buf_ptr: *mut i8 = std::ptr::null_mut();
        let mut buf_len: usize = 0;

        let code = with_progress(progress, |cb| unsafe {
            zig_lens_compile_codebase(c_path.as_ptr(), cb, &mut buf_ptr, &mut buf_len)
        });

        check_result(code)?;
        Ok(ZigLensBuf {
            ptr: buf_ptr as *mut u8,
            len: buf_len,
        })
    }

    /// Generate all report formats into a directory.
    pub fn generate_reports(
        path: &str,
        output_dir: &str,
        progress: Option<ProgressFn>,
    ) -> Result<()> {
        let c_path = CString::new(path).map_err(|_| Error::InvalidPath)?;
        let c_output_dir = CString::new(output_dir).map_err(|_| Error::InvalidPath)?;

        let code = with_progress(progress, |cb| unsafe {
            zig_lens_generate_reports(c_path.as_ptr(), c_output_dir.as_ptr(), cb)
        });

        check_result(code)
    }

    /// Analyze in-memory source code. Returns JSON analysis.
    pub fn analyze_source(source: &[u8], language: Language) -> Result<ZigLensBuf> {
        let mut buf_ptr: *mut i8 = std::ptr::null_mut();
        let mut buf_len: usize = 0;

        let code = unsafe {
            zig_lens_analyze_source(
                source.as_ptr() as *const i8,
                source.len(),
                language.as_c_int(),
                &mut buf_ptr,
                &mut buf_len,
            )
        };

        check_result(code)?;
        Ok(ZigLensBuf {
            ptr: buf_ptr as *mut u8,
            len: buf_len,
        })
    }

    /// Count lines, blank lines, and comment lines in source code.
    /// Pure function — no allocation needed.
    pub fn count_lines(source: &[u8]) -> Result<LineCount> {
        let mut loc: u32 = 0;
        let mut blank: u32 = 0;
        let mut comments: u32 = 0;

        let code = unsafe {
            zig_lens_count_lines(
                source.as_ptr() as *const i8,
                source.len(),
                &mut loc,
                &mut blank,
                &mut comments,
            )
        };

        check_result(code)?;
        Ok(LineCount {
            total: loc,
            blank,
            comments,
        })
    }
}
