//! Externally-anchored tests for zsss.
//!
//! IMPORTANT: `sss` is NOT a GNU/POSIX coreutil. No `sss`/`gsss` reference
//! binary exists (checked /opt/homebrew/opt/coreutils/libexec/gnubin/sss and
//! /opt/homebrew/bin/gsss — both absent). zsss is a bespoke Shamir Secret
//! Sharing + LSB-steganography + event-ticket tool that only shares the
//! coreutils naming scheme. "GNU parity" is therefore not an applicable axis.
//! The relevant contract is the zig-forge golden rule for key/secret code:
//! tests whose inputs AND expected outputs come from a source the library
//! author did not write, and NO roundtrip-only tests.
//!
//! The external anchors used here:
//!
//!   1. GF(2^8) field multiplication — anchored to the worked examples in
//!      NIST FIPS-197 (the AES specification) §4.2 / §4.2.1, which use the
//!      *same* irreducible polynomial x^8+x^4+x^3+x+1 (0x11B) that zsss's
//!      GF256 uses:  {57}·{83} = {c1},  {57}·{13} = {fe}, plus the xtime
//!      ladder {57}·{02}={ae}, {57}·{04}={47}, {57}·{08}={8e}, {57}·{10}={07}.
//!      Source: FIPS-197, "Advanced Encryption Standard (AES)", Section 4.2.
//!
//!   2. Shamir reconstruction — the shares fed to SSS.combine are generated by
//!      an INDEPENDENT polynomial evaluator (`refEval`) built on an independent
//!      Russian-peasant field multiply (`refGfMul`), itself pinned to the
//!      FIPS-197 vectors above. split() is never called, so this is not a
//!      roundtrip: an outside evaluator produces the y-values and the library's
//!      Lagrange interpolator must invert them back to the known secret (which
//!      combine independently re-checks via SHA-256 of the recovered bytes).
//!
//!   3. PNG chunk parsing — crafted inputs per the PNG spec chunk layout
//!      (4-byte big-endian length + 4-byte type + data + 4-byte CRC). A chunk
//!      length larger than the buffer must yield error.InvalidPng, not an
//!      out-of-bounds panic (regression test for the fixed DoS at stego.zig).
//!
//!   4. Ticket text format — literal ZSSS_TICKET_V1 key=value bytes parsed by
//!      TicketData.fromBytes with the expected field values written out
//!      literally, plus a control-character-injection negative vector.

const std = @import("std");
const testing = std.testing;

const main = @import("main.zig");
const stego = @import("stego.zig");
const ticket = @import("ticket.zig");

const GF256 = main.GF256;
const SSS = main.SSS;
const Share = main.Share;

// ---------------------------------------------------------------------------
// Independent reference implementation (NOT the library's tables)
// ---------------------------------------------------------------------------

/// Russian-peasant multiply in GF(2^8) mod 0x11B. Independent of zsss's
/// log/exp tables; anchored to FIPS-197 below.
fn refGfMul(a_in: u8, b_in: u8) u8 {
    var a = a_in;
    var b = b_in;
    var p: u8 = 0;
    var i: u8 = 0;
    while (i < 8) : (i += 1) {
        if (b & 1 != 0) p ^= a;
        const hi = a & 0x80;
        a <<= 1;
        if (hi != 0) a ^= 0x1B; // reduce (x^8 term folds to 0x1B in the low byte)
        b >>= 1;
    }
    return p;
}

/// Evaluate f(x) = coeffs[0] + coeffs[1]*x + ... over GF(2^8), Horner form,
/// using the independent multiply.
fn refEval(coeffs: []const u8, x: u8) u8 {
    var result: u8 = 0;
    var i = coeffs.len;
    while (i > 0) {
        i -= 1;
        result = refGfMul(result, x) ^ coeffs[i];
    }
    return result;
}

// ---------------------------------------------------------------------------
// 1. GF(2^8) field multiplication — anchored to FIPS-197
// ---------------------------------------------------------------------------

test "FIPS-197: reference GF multiply matches AES spec worked examples" {
    // FIPS-197 §4.2: {57}·{83} = {c1}; §4.2.1 xtime ladder for {57}.
    try testing.expectEqual(@as(u8, 0xc1), refGfMul(0x57, 0x83));
    try testing.expectEqual(@as(u8, 0xfe), refGfMul(0x57, 0x13));
    try testing.expectEqual(@as(u8, 0xae), refGfMul(0x57, 0x02));
    try testing.expectEqual(@as(u8, 0x47), refGfMul(0x57, 0x04));
    try testing.expectEqual(@as(u8, 0x8e), refGfMul(0x57, 0x08));
    try testing.expectEqual(@as(u8, 0x07), refGfMul(0x57, 0x10));
}

test "FIPS-197: library GF256.multiply matches AES spec worked examples" {
    GF256.init();
    // Same external vectors, now against the library's log/exp tables.
    try testing.expectEqual(@as(u8, 0xc1), GF256.multiply(0x57, 0x83));
    try testing.expectEqual(@as(u8, 0xfe), GF256.multiply(0x57, 0x13));
    try testing.expectEqual(@as(u8, 0xae), GF256.multiply(0x57, 0x02));
    try testing.expectEqual(@as(u8, 0x47), GF256.multiply(0x57, 0x04));
    try testing.expectEqual(@as(u8, 0x8e), GF256.multiply(0x57, 0x08));
    try testing.expectEqual(@as(u8, 0x07), GF256.multiply(0x57, 0x10));
}

test "GF256 field axiom: a * inverse(a) == 1 for all nonzero a" {
    GF256.init();
    var a: u16 = 1;
    while (a < 256) : (a += 1) {
        const av: u8 = @intCast(a);
        try testing.expectEqual(@as(u8, 1), GF256.multiply(av, GF256.inverse(av)));
    }
}

// ---------------------------------------------------------------------------
// 2. Shamir reconstruction — shares produced by the INDEPENDENT evaluator
// ---------------------------------------------------------------------------

fn buildShare(
    allocator: std.mem.Allocator,
    threshold: u8,
    total: u8,
    index: u8,
    secret_id: [4]u8,
    y_values: []const u8,
) !Share {
    return Share{
        .version = 1,
        .threshold = threshold,
        .total_shares = total,
        .index = index,
        .secret_id = secret_id,
        .data = try allocator.dupe(u8, y_values),
        .checksum = 0,
    };
}

test "Shamir: library combine inverts independently-generated shares (threshold 3)" {
    const allocator = testing.allocator;
    GF256.init();

    // Known secret (3 bytes). combine() will independently re-verify the
    // recovered bytes via SHA-256(secret)[0..4], so we set secret_id honestly.
    const secret = [_]u8{ 0x53, 0x1a, 0xc4 };
    var hash: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(&secret, &hash, .{});
    var secret_id: [4]u8 = undefined;
    @memcpy(&secret_id, hash[0..4]);

    // Fixed degree-2 polynomials, one per secret byte: coeffs[0] is the secret
    // byte, coeffs[1..] are arbitrary-but-fixed. These come from us, but the
    // *reconstruction* is what is under test, and it is checked against the
    // secret above — an external fact combine cannot fake.
    const poly = [3][3]u8{
        .{ secret[0], 0xca, 0x1f },
        .{ secret[1], 0x33, 0x9e },
        .{ secret[2], 0x71, 0x08 },
    };
    const threshold: u8 = 3;
    const total: u8 = 5;

    // Generate 5 shares by evaluating with the INDEPENDENT refEval.
    var all_shares: [5]Share = undefined;
    var made: usize = 0;
    defer {
        for (all_shares[0..made]) |*s| allocator.free(s.data);
    }
    var xi: u8 = 1;
    while (xi <= total) : (xi += 1) {
        var y: [3]u8 = undefined;
        for (0..3) |b| y[b] = refEval(&poly[b], xi);
        all_shares[xi - 1] = try buildShare(allocator, threshold, total, xi, secret_id, &y);
        made += 1;
    }

    // Any k=3 subset must recover the exact secret. Test three distinct
    // subsets — the defining property of a (3,5) Shamir scheme.
    const subsets = [_][3]usize{
        .{ 0, 1, 2 }, // x = 1,2,3
        .{ 2, 3, 4 }, // x = 3,4,5
        .{ 0, 2, 4 }, // x = 1,3,5
    };
    for (subsets) |idx| {
        const chosen = [_]Share{ all_shares[idx[0]], all_shares[idx[1]], all_shares[idx[2]] };
        const recovered = try SSS.combine(allocator, &chosen);
        defer allocator.free(recovered);
        try testing.expectEqualSlices(u8, &secret, recovered);
    }
}

// ---------------------------------------------------------------------------
// 3. PNG chunk parsing — crafted per PNG spec; must not OOB-panic (DoS fix)
// ---------------------------------------------------------------------------

const PNG_SIG = [8]u8{ 0x89, 'P', 'N', 'G', 0x0d, 0x0a, 0x1a, 0x0a };

test "PNG: oversized chunk length is rejected, not an out-of-bounds panic" {
    const allocator = testing.allocator;

    // 8-byte signature + a chunk claiming length 0xFFFFFFFF. Per the PNG spec
    // the length field is a big-endian u32 immediately after the signature;
    // an attacker sets it far beyond the buffer. Pre-fix this sliced
    // data[16..][0..0xFFFFFFFF] and panicked "index out of bounds".
    var buf: [24]u8 = undefined;
    @memcpy(buf[0..8], &PNG_SIG);
    buf[8] = 0xFF; // chunk_len byte 0 (BE)
    buf[9] = 0xFF;
    buf[10] = 0xFF;
    buf[11] = 0xFF;
    @memcpy(buf[12..16], "IHDR");
    @memset(buf[16..24], 0);

    try testing.expectError(stego.StegoError.InvalidPng, stego.getPngDimensions(&buf));
    try testing.expectError(stego.StegoError.InvalidPng, stego.decodePng(allocator, &buf));
}

test "PNG: truncated IHDR chunk (length exceeds remaining bytes) rejected" {
    const allocator = testing.allocator;

    // A chunk that claims length 13 (a real IHDR) but the buffer only holds a
    // few of those bytes. Bound check must fire before slicing.
    var buf: [20]u8 = undefined;
    @memcpy(buf[0..8], &PNG_SIG);
    buf[8] = 0;
    buf[9] = 0;
    buf[10] = 0;
    buf[11] = 13; // claims 13 data bytes...
    @memcpy(buf[12..16], "IHDR");
    @memset(buf[16..20], 0); // ...but only 4 bytes follow

    try testing.expectError(stego.StegoError.InvalidPng, stego.getPngDimensions(&buf));
    try testing.expectError(stego.StegoError.InvalidPng, stego.decodePng(allocator, &buf));
}

test "PNG: absurd IHDR dimensions rejected before allocation (overflow fix)" {
    const allocator = testing.allocator;

    // Well-formed chunk framing, but IHDR width/height = 0x40000000 each. The
    // pre-fix decodePng computed width*height*bpp and could overflow usize /
    // demand an enormous allocation. Must reject as InvalidPng.
    var buf: [33]u8 = undefined;
    @memcpy(buf[0..8], &PNG_SIG);
    buf[8] = 0;
    buf[9] = 0;
    buf[10] = 0;
    buf[11] = 13; // IHDR data length
    @memcpy(buf[12..16], "IHDR");
    // width = 0x40000000
    buf[16] = 0x40;
    buf[17] = 0;
    buf[18] = 0;
    buf[19] = 0;
    // height = 0x40000000
    buf[20] = 0x40;
    buf[21] = 0;
    buf[22] = 0;
    buf[23] = 0;
    buf[24] = 8; // bit depth
    buf[25] = 2; // color type (RGB, bpp=3)
    buf[26] = 0; // compression
    buf[27] = 0; // filter
    buf[28] = 0; // interlace
    @memset(buf[29..33], 0); // CRC (unchecked)

    try testing.expectError(stego.StegoError.InvalidPng, stego.decodePng(allocator, &buf));
}

// ---------------------------------------------------------------------------
// 4. Ticket text format — literal bytes in, expected fields out
// ---------------------------------------------------------------------------

test "Ticket: fromBytes parses the documented ZSSS_TICKET_V1 key=value format" {
    const allocator = testing.allocator;

    // Literal external wire bytes (the documented format), not produced by the
    // library — a fixed transcript with known field values.
    const wire =
        "ZSSS_TICKET_V1\n" ++
        "event_id=summer-fest-2026\n" ++
        "ticket_id=deadbeefcafef00ddeadbeefcafef00d\n" ++
        "issued_at=1700000000\n" ++
        "seat=A12\n" ++
        "tier=VIP\n" ++
        "expires_at=1800000000\n" ++
        "signature=" ++ ("ab" ** 64) ++ "\n";

    var td = try ticket.TicketData.fromBytes(allocator, wire);
    defer td.deinit(allocator);

    try testing.expectEqualStrings("summer-fest-2026", td.event_id);
    try testing.expectEqualStrings("deadbeefcafef00ddeadbeefcafef00d", td.ticket_id);
    try testing.expectEqual(@as(i64, 1700000000), td.issued_at);
    try testing.expectEqualStrings("A12", td.seat.?);
    try testing.expectEqualStrings("VIP", td.tier.?);
    try testing.expectEqual(@as(i64, 1800000000), td.expires_at.?);
}

test "Ticket: control-character field is rejected on serialization (injection guard)" {
    const allocator = testing.allocator;

    // An event_id carrying a newline would, pre-fix, inject a second
    // key=value line (e.g. override expires_at or signature) on the next parse.
    const td = ticket.TicketData{
        .event_id = "evil\nexpires_at=0\nsignature=" ++ ("00" ** 64),
        .ticket_id = "id",
        .issued_at = 1,
        .signature = "ab" ** 64,
    };

    try testing.expectError(error.InvalidTicketField, td.toBytes(allocator));
}
