//! Externally-anchored GNU parity tests for zhashsum.
//!
//! There is no GNU binary literally named `hashsum` — GNU coreutils ships a
//! family of per-algorithm wrappers (md5sum, sha1sum, sha224sum, sha256sum,
//! sha384sum, sha512sum, b2sum). zhashsum is the union of that family behind
//! one binary selected by `--md5 / --sha1 / ... / --blake2b`. So each parity
//! case names BOTH:
//!   - the zhashsum argv (with its algorithm flag), and
//!   - the matching GNU wrapper + argv,
//! runs both, and byte-compares stdout plus the exit code. None of the
//! expected outputs are produced by zhashsum itself — this is a true external
//! anchor against real GNU coreutils 9.x.
//!
//! When no GNU wrapper is installed the GNU-diff cases SkipZigTest, but the
//! literal-anchored test still runs: its expected bytes are transcribed from
//! published spec test vectors (RFC 1321 MD5, RFC 6234/FIPS 180-4 SHA, RFC
//! 7693 BLAKE2, the official BLAKE3 vectors) and GNU coreutils' documented
//! output format — NOT generated by zhashsum.
//!
//! Run via `zig build test`.

const std = @import("std");
const Io = std.Io;
const build_options = @import("build_options");

fn resolveZhashsumExe(arena: std.mem.Allocator, io: Io) ![]const u8 {
    const configured: []const u8 = build_options.zhashsum_exe;
    if (std.fs.path.isAbsolute(configured)) return configured;
    return try Io.Dir.cwd().realPathFileAlloc(io, configured, arena);
}

/// Resolve a GNU coreutils wrapper (e.g. "sha256sum", "b2sum") to an absolute
/// path, trying the homebrew gnubin dir, the `g`-prefixed homebrew names, and
/// (on Linux) /usr/bin.
fn findGnu(arena: std.mem.Allocator, io: Io, basename: []const u8) ?[]const u8 {
    const gnubin_dirs = [_][]const u8{
        "/opt/homebrew/opt/coreutils/libexec/gnubin/",
        "/usr/local/opt/coreutils/libexec/gnubin/",
    };
    for (gnubin_dirs) |dir| {
        const p = std.fmt.allocPrint(arena, "{s}{s}", .{ dir, basename }) catch continue;
        if (Io.Dir.openFile(Io.Dir.cwd(), io, p, .{})) |f| {
            f.close(io);
            return p;
        } else |_| {}
    }
    const g_dirs = [_][]const u8{ "/opt/homebrew/bin/g", "/usr/local/bin/g" };
    for (g_dirs) |pre| {
        const p = std.fmt.allocPrint(arena, "{s}{s}", .{ pre, basename }) catch continue;
        if (Io.Dir.openFile(Io.Dir.cwd(), io, p, .{})) |f| {
            f.close(io);
            return p;
        } else |_| {}
    }
    if (@import("builtin").os.tag == .linux) {
        const p = std.fmt.allocPrint(arena, "/usr/bin/{s}", .{basename}) catch return null;
        if (Io.Dir.openFile(Io.Dir.cwd(), io, p, .{})) |f| {
            f.close(io);
            return p;
        } else |_| {}
    }
    return null;
}

const RunResult = struct {
    stdout: []u8,
    stderr: []u8,
    exit_code: u8,
};

fn runTool(
    arena: std.mem.Allocator,
    io: Io,
    exe: []const u8,
    args: []const []const u8,
    fixture_dir: Io.Dir,
    stdin_fixture: ?[]const u8,
) !RunResult {
    var argv: std.ArrayListUnmanaged([]const u8) = .empty;
    try argv.append(arena, exe);
    for (args) |a| try argv.append(arena, a);

    const stdin_file: ?Io.File = if (stdin_fixture) |name|
        try fixture_dir.openFile(io, name, .{})
    else
        null;
    defer if (stdin_file) |f| f.close(io);

    var child = try std.process.spawn(io, .{
        .argv = argv.items,
        .cwd = .{ .dir = fixture_dir },
        .stdin = if (stdin_file) |f| .{ .file = f } else .ignore,
        .stdout = .pipe,
        .stderr = .pipe,
    });
    defer child.kill(io);

    var multi_reader_buffer: Io.File.MultiReader.Buffer(2) = undefined;
    var multi_reader: Io.File.MultiReader = undefined;
    multi_reader.init(arena, io, multi_reader_buffer.toStreams(), &.{ child.stdout.?, child.stderr.? });
    defer multi_reader.deinit();

    while (multi_reader.fill(4096, .none)) |_| {} else |err| switch (err) {
        error.EndOfStream => {},
        else => |e| return e,
    }
    try multi_reader.checkAnyError();

    const term = try child.wait(io);
    const stdout = try multi_reader.toOwnedSlice(0);
    const stderr = try multi_reader.toOwnedSlice(1);

    return .{
        .stdout = stdout,
        .stderr = stderr,
        .exit_code = switch (term) {
            .exited => |code| code,
            else => 255,
        },
    };
}

const Fixture = struct { name: []const u8, data: []const u8 };

fn allByteValues() [256]u8 {
    var b: [256]u8 = undefined;
    for (0..256) |i| b[i] = @intCast(i);
    return b;
}

fn writeFixtures(io: Io, dir: Io.Dir, arena: std.mem.Allocator) !void {
    const all_bytes = allByteValues();
    // > 8 KiB (crosses the 8192-byte read buffer boundary mid-stream).
    var big: std.ArrayListUnmanaged(u8) = .empty;
    for (0..500) |i| try big.append(arena, @intCast(i % 256));

    const fixtures = [_]Fixture{
        .{ .name = "empty.bin", .data = "" },
        .{ .name = "abc.txt", .data = "abc" },
        .{ .name = "hello.txt", .data = "hello\n" },
        .{ .name = "bytes.bin", .data = &all_bytes },
        .{ .name = "big.bin", .data = big.items },
    };
    for (fixtures) |f| {
        try dir.writeFile(io, .{ .sub_path = f.name, .data = f.data });
    }
}

// Each case maps a zhashsum algorithm flag to the GNU wrapper that implements
// the same algorithm; shared flags/files follow in `rest`.
const AlgoCase = struct {
    name: []const u8,
    zflag: ?[]const u8, // zhashsum algorithm flag (null = default sha256)
    gnu: []const u8, // GNU wrapper basename
    rest: []const []const u8,
    stdin_fixture: ?[]const u8 = null,
    // b2sum needs "-l 256" to match zhashsum's fixed BLAKE2b-256.
    gnu_extra: []const []const u8 = &.{},
    expect_exit: u8 = 0,
};

const algo_cases = [_]AlgoCase{
    // Digests of representative inputs, every GNU-comparable algorithm.
    .{ .name = "sha256 abc", .zflag = "--sha256", .gnu = "sha256sum", .rest = &.{"abc.txt"} },
    .{ .name = "sha256 default flag omitted", .zflag = null, .gnu = "sha256sum", .rest = &.{"abc.txt"} },
    .{ .name = "sha256 empty", .zflag = "--sha256", .gnu = "sha256sum", .rest = &.{"empty.bin"} },
    .{ .name = "sha256 all byte values", .zflag = "--sha256", .gnu = "sha256sum", .rest = &.{"bytes.bin"} },
    .{ .name = "sha256 crosses buffer boundary", .zflag = "--sha256", .gnu = "sha256sum", .rest = &.{"big.bin"} },
    .{ .name = "md5 abc", .zflag = "--md5", .gnu = "md5sum", .rest = &.{"abc.txt"} },
    .{ .name = "md5 empty", .zflag = "--md5", .gnu = "md5sum", .rest = &.{"empty.bin"} },
    .{ .name = "sha1 abc", .zflag = "--sha1", .gnu = "sha1sum", .rest = &.{"abc.txt"} },
    .{ .name = "sha224 abc", .zflag = "--sha224", .gnu = "sha224sum", .rest = &.{"abc.txt"} },
    .{ .name = "sha384 abc", .zflag = "--sha384", .gnu = "sha384sum", .rest = &.{"abc.txt"} },
    .{ .name = "sha512 abc", .zflag = "--sha512", .gnu = "sha512sum", .rest = &.{"abc.txt"} },
    .{ .name = "sha512 bytes", .zflag = "--sha512", .gnu = "sha512sum", .rest = &.{"bytes.bin"} },
    .{ .name = "blake2b256 abc vs b2sum -l 256", .zflag = "--blake2b", .gnu = "b2sum", .rest = &.{"abc.txt"}, .gnu_extra = &.{ "-l", "256" } },
    .{ .name = "blake2b256 bytes vs b2sum -l 256", .zflag = "--blake2b", .gnu = "b2sum", .rest = &.{"bytes.bin"}, .gnu_extra = &.{ "-l", "256" } },
    // Multiple files in one invocation.
    .{ .name = "sha256 multiple files", .zflag = "--sha256", .gnu = "sha256sum", .rest = &.{ "abc.txt", "hello.txt", "empty.bin" } },
    // Binary marker ' *' (audit finding: -b was ignored).
    .{ .name = "sha256 -b binary marker", .zflag = "--sha256", .gnu = "sha256sum", .rest = &.{ "-b", "abc.txt" } },
    // Text mode explicit.
    .{ .name = "sha256 --text", .zflag = "--sha256", .gnu = "sha256sum", .rest = &.{ "--text", "abc.txt" } },
    // stdin.
    .{ .name = "sha256 stdin", .zflag = "--sha256", .gnu = "sha256sum", .rest = &.{}, .stdin_fixture = "abc.txt" },
    .{ .name = "sha256 explicit - stdin", .zflag = "--sha256", .gnu = "sha256sum", .rest = &.{"-"}, .stdin_fixture = "hello.txt" },
    // Error paths (audit HIGH findings): directory + missing file must exit 1.
    .{ .name = "directory operand exits 1", .zflag = "--sha256", .gnu = "sha256sum", .rest = &.{"subdir"}, .expect_exit = 1 },
    .{ .name = "missing file exits 1", .zflag = "--sha256", .gnu = "sha256sum", .rest = &.{"no-such.txt"}, .expect_exit = 1 },
    .{ .name = "missing among present still hashes others, exit 1", .zflag = "--sha256", .gnu = "sha256sum", .rest = &.{ "abc.txt", "no-such.txt", "hello.txt" }, .expect_exit = 1 },
};

test "GNU parity: digest stdout bytes + exit codes match the real GNU wrappers" {
    const io = std.testing.io;
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const zexe = try resolveZhashsumExe(arena, io);

    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    try writeFixtures(io, tmp.dir, arena);
    try tmp.dir.createDirPath(io, "subdir");

    var ran: usize = 0;
    var failures: usize = 0;
    for (algo_cases) |case| {
        const gnu = findGnu(arena, io, case.gnu) orelse continue;

        var zargs: std.ArrayListUnmanaged([]const u8) = .empty;
        if (case.zflag) |f| try zargs.append(arena, f);
        for (case.rest) |a| try zargs.append(arena, a);

        var gargs: std.ArrayListUnmanaged([]const u8) = .empty;
        for (case.gnu_extra) |a| try gargs.append(arena, a);
        for (case.rest) |a| try gargs.append(arena, a);

        const z = try runTool(arena, io, zexe, zargs.items, tmp.dir, case.stdin_fixture);
        const g = try runTool(arena, io, gnu, gargs.items, tmp.dir, case.stdin_fixture);
        ran += 1;

        if (!std.mem.eql(u8, z.stdout, g.stdout)) {
            std.debug.print("FAIL [{s}]: stdout differs\n  zhashsum: {s}\n  gnu {s}: {s}\n", .{ case.name, z.stdout, case.gnu, g.stdout });
            failures += 1;
            continue;
        }
        if (z.exit_code != g.exit_code) {
            std.debug.print("FAIL [{s}]: exit zhashsum={d} gnu={d}\n", .{ case.name, z.exit_code, g.exit_code });
            failures += 1;
            continue;
        }
        if (g.exit_code != case.expect_exit) {
            std.debug.print("FAIL [{s}]: stale expectation — GNU exited {d}, expected {d}\n", .{ case.name, g.exit_code, case.expect_exit });
            failures += 1;
        }
    }

    if (ran == 0) return error.SkipZigTest;
    try std.testing.expectEqual(@as(usize, 0), failures);
}

// -c / --check verification cases. The sums files are AUTHORED BY GNU (captured
// from the GNU wrapper's own output), so both tools verify against an external
// checklist. Output ("name: OK/FAILED") + exit codes are compared.
test "GNU parity: -c check mode stdout + exit match GNU (sums authored by GNU)" {
    const io = std.testing.io;
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const zexe = try resolveZhashsumExe(arena, io);
    const gnu = findGnu(arena, io, "sha256sum") orelse return error.SkipZigTest;

    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    try writeFixtures(io, tmp.dir, arena);

    // GNU-authored good checklist over three files.
    const good = try runTool(arena, io, gnu, &.{ "abc.txt", "hello.txt", "empty.bin" }, tmp.dir, null);
    try tmp.dir.writeFile(io, .{ .sub_path = "good.sums", .data = good.stdout });

    // A checklist with one deliberately-wrong hash (GNU-shaped line, hand-set
    // to 64 hex zeros for abc.txt).
    const bad_line = "0000000000000000000000000000000000000000000000000000000000000000  abc.txt\n";
    try tmp.dir.writeFile(io, .{ .sub_path = "bad.sums", .data = bad_line });

    // A checklist naming a file that does not exist.
    const abc_hash = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"; // SHA-256("abc"), FIPS 180-4
    const miss_line = abc_hash ++ "  gone.txt\n";
    try tmp.dir.writeFile(io, .{ .sub_path = "miss.sums", .data = miss_line });

    const CheckCase = struct {
        name: []const u8,
        args: []const []const u8,
        expect_exit: u8,
    };
    const cases = [_]CheckCase{
        .{ .name = "-c all OK", .args = &.{ "-c", "good.sums" }, .expect_exit = 0 },
        .{ .name = "-c mismatch FAILED", .args = &.{ "-c", "bad.sums" }, .expect_exit = 1 },
        .{ .name = "-c missing file", .args = &.{ "-c", "miss.sums" }, .expect_exit = 1 },
        .{ .name = "-c --quiet all OK (no OK lines)", .args = &.{ "--quiet", "-c", "good.sums" }, .expect_exit = 0 },
        .{ .name = "-c --status mismatch (silent, exit 1)", .args = &.{ "--status", "-c", "bad.sums" }, .expect_exit = 1 },
        .{ .name = "-c --status OK (silent, exit 0)", .args = &.{ "--status", "-c", "good.sums" }, .expect_exit = 0 },
        .{ .name = "-c --ignore-missing all missing", .args = &.{ "--ignore-missing", "-c", "miss.sums" }, .expect_exit = 1 },
    };

    var failures: usize = 0;
    for (cases) |case| {
        // zhashsum needs --sha256 (default) — sums are sha256; GNU sha256sum needs nothing.
        const z = try runTool(arena, io, zexe, case.args, tmp.dir, null);
        const g = try runTool(arena, io, gnu, case.args, tmp.dir, null);

        if (!std.mem.eql(u8, z.stdout, g.stdout)) {
            std.debug.print("FAIL [{s}]: -c stdout differs\n  z:  {s}\n  g:  {s}\n", .{ case.name, z.stdout, g.stdout });
            failures += 1;
            continue;
        }
        if (z.exit_code != g.exit_code or g.exit_code != case.expect_exit) {
            std.debug.print("FAIL [{s}]: exit z={d} g={d} want={d}\n", .{ case.name, z.exit_code, g.exit_code, case.expect_exit });
            failures += 1;
        }
    }
    try std.testing.expectEqual(@as(usize, 0), failures);
}

// Literal spec-vector anchors — independent of any installed GNU binary.
// Digests transcribed from published test vectors; output format from GNU
// coreutils' documented "<hex><sp><sp|*><name>\n" shape.
test "literal spec-vector anchors: digests + output format" {
    const io = std.testing.io;
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const zexe = try resolveZhashsumExe(arena, io);

    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    try tmp.dir.writeFile(io, .{ .sub_path = "abc.txt", .data = "abc" });
    try tmp.dir.writeFile(io, .{ .sub_path = "empty.bin", .data = "" });

    const Case = struct {
        name: []const u8,
        args: []const []const u8,
        expected: []const u8,
    };
    const cases = [_]Case{
        // RFC 1321 MD5 test suite: MD5("") = d41d8cd9...
        .{ .name = "md5 empty (RFC 1321)", .args = &.{ "--md5", "empty.bin" }, .expected = "d41d8cd98f00b204e9800998ecf8427e  empty.bin\n" },
        // RFC 1321 / RFC 6151: MD5("abc") = 900150983cd24fb0d6963f7d28e17f72
        .{ .name = "md5 abc (RFC 1321)", .args = &.{ "--md5", "abc.txt" }, .expected = "900150983cd24fb0d6963f7d28e17f72  abc.txt\n" },
        // FIPS 180-4 / RFC 6234: SHA-1("abc")
        .{ .name = "sha1 abc (FIPS 180-4)", .args = &.{ "--sha1", "abc.txt" }, .expected = "a9993e364706816aba3e25717850c26c9cd0d89d  abc.txt\n" },
        // FIPS 180-4: SHA-256("abc")
        .{ .name = "sha256 abc (FIPS 180-4)", .args = &.{ "--sha256", "abc.txt" }, .expected = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad  abc.txt\n" },
        // FIPS 180-4: SHA-224("abc")
        .{ .name = "sha224 abc (FIPS 180-4)", .args = &.{ "--sha224", "abc.txt" }, .expected = "23097d223405d8228642a477bda255b32aadbce4bda0b3f7e36c9da7  abc.txt\n" },
        // FIPS 180-4: SHA-512("abc")
        .{ .name = "sha512 abc (FIPS 180-4)", .args = &.{ "--sha512", "abc.txt" }, .expected = "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f  abc.txt\n" },
        // RFC 7693 Appendix A: BLAKE2b-256("abc")
        .{ .name = "blake2b256 abc (RFC 7693)", .args = &.{ "--blake2b", "abc.txt" }, .expected = "bddd813c634239723171ef3fee98579b94964e3bb1cb3e427262c8c068d52319  abc.txt\n" },
        // BLAKE2s-256("abc") reference vector
        .{ .name = "blake2s256 abc (BLAKE2 ref)", .args = &.{ "--blake2s", "abc.txt" }, .expected = "508c5e8c327c14e2e1a72ba34eeb452f37458b209ed63a294d999b4c86675982  abc.txt\n" },
        // Official BLAKE3 test vectors: BLAKE3("abc")
        .{ .name = "blake3 abc (BLAKE3 official)", .args = &.{ "--blake3", "abc.txt" }, .expected = "6437b3ac38465133ffb63b75273a8db548c558465d79db03fd359c6cd5bd9d85  abc.txt\n" },
        // GNU binary-mode marker ' *' (audit finding: -b was ignored).
        .{ .name = "sha256 -b binary marker", .args = &.{ "--sha256", "-b", "abc.txt" }, .expected = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad *abc.txt\n" },
    };

    var failures: usize = 0;
    for (cases) |case| {
        const r = try runTool(arena, io, zexe, case.args, tmp.dir, null);
        if (!std.mem.eql(u8, r.stdout, case.expected) or r.exit_code != 0) {
            std.debug.print("FAIL [{s}]\n  want: {s}\n  got:  {s} (exit {d})\n", .{ case.name, case.expected, r.stdout, r.exit_code });
            failures += 1;
        }
    }
    try std.testing.expectEqual(@as(usize, 0), failures);
}

// Regression anchor for the two HIGH audit findings.
test "audit HIGH findings: oversized-name safety + directory/read-error handling" {
    const io = std.testing.io;
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const zexe = try resolveZhashsumExe(arena, io);

    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    try tmp.dir.createDirPath(io, "subdir");

    // Finding #1 (OOB): a >= 4096-byte path argument used to memcpy past a
    // [4096]u8 stack buffer and panic / corrupt the stack. It must now be
    // handled gracefully: no crash (exit != 139/134/255), exit 1, nothing on
    // stdout. (5000 chars > the old 4096 buffer.)
    {
        const long_name = try arena.alloc(u8, 5000);
        @memset(long_name, 'a');
        const r = try runTool(arena, io, zexe, &.{long_name}, tmp.dir, null);
        try std.testing.expect(r.exit_code == 1); // clean failure, not a crash
        try std.testing.expectEqual(@as(usize, 0), r.stdout.len);
    }

    // Finding #2 (read errors treated as EOF): a directory used to hash as the
    // empty-input digest with exit 0. GNU prints "Is a directory" exit 1 with
    // no stdout. e3b0c442... is SHA-256("") — it must NOT appear.
    {
        const r = try runTool(arena, io, zexe, &.{ "--sha256", "subdir" }, tmp.dir, null);
        try std.testing.expectEqual(@as(u8, 1), r.exit_code);
        try std.testing.expectEqual(@as(usize, 0), r.stdout.len);
        try std.testing.expect(std.mem.indexOf(u8, r.stderr, "Is a directory") != null);
        try std.testing.expect(std.mem.indexOf(u8, r.stderr, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855") == null);
    }

    // Unknown option must error + exit 1 (audit finding), not be silently
    // swallowed with exit 0.
    {
        const r = try runTool(arena, io, zexe, &.{ "--bogus", "subdir" }, tmp.dir, null);
        try std.testing.expectEqual(@as(u8, 1), r.exit_code);
        try std.testing.expect(std.mem.indexOf(u8, r.stderr, "unrecognized option") != null);
    }
}
