//! GNU-parity tests for zxz, externally anchored against XZ Utils 5.8.3.
//!
//! Two anchor sources, neither authored by this library:
//!   1. Literal .xz stream bytes emitted by `/opt/homebrew/bin/xz` (XZ Utils
//!      5.8.3): `printf 'hello\n' | xz -c -6`. These are baked in as
//!      `HELLO_XZ` below, so the correctness anchor bites even if GNU xz is
//!      not installed at test time.
//!   2. When XZ_BIN is present and executable, fixtures are (re)generated by
//!      real GNU xz at test time and zxz's decode is diffed against both the
//!      original plaintext and `xz -dc` output.
//!
//! These tests drive the *installed zxz binary* (env ZXZ_BIN) so they exercise
//! the real CLI contract: decoded bytes, process exit codes, and the on-disk
//! source-file/overwrite/symlink behavior — the behaviors the audit flagged.
//!
//! NOT roundtrip tests: the compressed inputs are produced by an external tool
//! (GNU xz), and the expected decoded bytes are asserted literally.

const std = @import("std");
const testing = std.testing;

// ---------------------------------------------------------------------------
// External anchor: exact bytes GNU xz 5.8.3 emits for `printf 'hello\n'|xz -c -6`.
// Captured 2026-07 from /opt/homebrew/bin/xz (XZ Utils 5.8.3 / liblzma 5.8.3).
// Decodes to the ASCII bytes "hello\n".
const HELLO_XZ = [_]u8{
    0xfd, 0x37, 0x7a, 0x58, 0x5a, 0x00, 0x00, 0x04, 0xe6, 0xd6, 0xb4, 0x46,
    0x04, 0xc0, 0x0a, 0x06, 0x21, 0x01, 0x16, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0xaa, 0x30, 0x8e, 0xa6, 0x01, 0x00, 0x05, 0x68,
    0x65, 0x6c, 0x6c, 0x6f, 0x0a, 0x00, 0x00, 0x00, 0xa5, 0x60, 0x97, 0xf1,
    0x94, 0xf6, 0xfd, 0xe0, 0x00, 0x01, 0x26, 0x06, 0x3a, 0x93, 0x3b, 0x0a,
    0x1f, 0xb6, 0xf3, 0x7d, 0x01, 0x00, 0x00, 0x00, 0x00, 0x04, 0x59, 0x5a,
};
const HELLO_PLAIN = "hello\n";

// ---------------------------------------------------------------------------
// Minimal C file I/O so the tests don't depend on the Io-fied std.fs surface.
extern "c" fn open(path: [*:0]const u8, flags: c_int, ...) c_int;
extern "c" fn close(fd: c_int) c_int;
extern "c" fn write(fd: c_int, buf: [*]const u8, count: usize) isize;
const c_read = @extern(*const fn (c_int, [*]u8, usize) callconv(.c) isize, .{ .name = "read" });
extern "c" fn unlink(path: [*:0]const u8) c_int;
extern "c" fn access(path: [*:0]const u8, mode: c_int) c_int;
extern "c" fn mkdir(path: [*:0]const u8, mode: c_uint) c_int;
extern "c" fn getcwd(buf: [*]u8, size: usize) ?[*:0]u8;
extern "c" fn getenv(name: [*:0]const u8) ?[*:0]const u8;

fn envVar(name: [*:0]const u8) ?[]const u8 {
    const v = getenv(name) orelse return null;
    return std.mem.span(v);
}

const is_darwin = @import("builtin").os.tag.isDarwin();
const O_RDONLY: c_int = 0x0000;
const O_WRONLY: c_int = 0x0001;
const O_CREAT: c_int = if (is_darwin) 0x0200 else 0o100;
const O_TRUNC: c_int = if (is_darwin) 0x0400 else 0o1000;
const F_OK: c_int = 0;

var cwd_buf: [4096]u8 = undefined;
var base_buf: [4096]u8 = undefined;

fn baseDir() []const u8 {
    const cwd = getcwd(&cwd_buf, cwd_buf.len) orelse @panic("getcwd failed");
    const cwd_slice = std.mem.span(cwd);
    const dir = std.fmt.bufPrint(&base_buf, "{s}/zig-out/zxz-parity-tmp", .{cwd_slice}) catch @panic("path too long");
    // best-effort create (ignore EEXIST)
    var zbuf: [4096]u8 = undefined;
    const z = std.fmt.bufPrintZ(&zbuf, "{s}", .{dir}) catch @panic("path too long");
    _ = mkdir(z.ptr, 0o755);
    return dir;
}

fn joinZ(buf: []u8, dir: []const u8, name: []const u8) [:0]const u8 {
    return std.fmt.bufPrintZ(buf, "{s}/{s}", .{ dir, name }) catch @panic("path too long");
}

fn writeFile(pathZ: [:0]const u8, data: []const u8) void {
    const fd = open(pathZ.ptr, O_WRONLY | O_CREAT | O_TRUNC, @as(c_int, 0o644));
    if (fd < 0) @panic("writeFile: open failed");
    var off: usize = 0;
    while (off < data.len) {
        const n = write(fd, data.ptr + off, data.len - off);
        if (n <= 0) @panic("writeFile: write failed");
        off += @intCast(n);
    }
    _ = close(fd);
}

fn readFile(allocator: std.mem.Allocator, pathZ: [:0]const u8) ?[]u8 {
    const fd = open(pathZ.ptr, O_RDONLY);
    if (fd < 0) return null;
    defer _ = close(fd);
    var list: std.ArrayListUnmanaged(u8) = .empty;
    errdefer list.deinit(allocator);
    var tmp: [8192]u8 = undefined;
    while (true) {
        const n = c_read(fd, &tmp, tmp.len);
        if (n < 0) return null;
        if (n == 0) break;
        list.appendSlice(allocator, tmp[0..@intCast(n)]) catch return null;
    }
    return list.toOwnedSlice(allocator) catch null;
}

fn exists(pathZ: [:0]const u8) bool {
    return access(pathZ.ptr, F_OK) == 0;
}

fn rm(pathZ: [:0]const u8) void {
    _ = unlink(pathZ.ptr);
}

// ---------------------------------------------------------------------------
fn zxzBin() []const u8 {
    return envVar("ZXZ_BIN") orelse "zig-out/bin/zxz";
}

fn xzBin() ?[]const u8 {
    const b = envVar("XZ_BIN") orelse return null;
    var buf: [4096]u8 = undefined;
    const z = std.fmt.bufPrintZ(&buf, "{s}", .{b}) catch return null;
    if (access(z.ptr, 1) != 0) return null; // X_OK
    return b;
}

const RunOut = struct {
    exit: ?u8,
    stdout: []u8,
    stderr: []u8,
    fn free(self: RunOut, a: std.mem.Allocator) void {
        a.free(self.stdout);
        a.free(self.stderr);
    }
};

fn run(allocator: std.mem.Allocator, argv: []const []const u8) !RunOut {
    var threaded = std.Io.Threaded.init(allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();
    const r = try std.process.run(allocator, io, .{ .argv = argv });
    const exit: ?u8 = switch (r.term) {
        .exited => |c| c,
        else => null,
    };
    return .{ .exit = exit, .stdout = r.stdout, .stderr = r.stderr };
}

// ===========================================================================
// 1. Correctness anchor: zxz -dc of GNU-produced bytes == "hello\n", exit 0.
//    (Primary anchor for the decode + write-all-output path.)
test "decompress GNU-produced .xz to stdout equals hello (exit 0)" {
    const a = testing.allocator;
    const dir = baseDir();
    var pb: [4096]u8 = undefined;
    const p = joinZ(&pb, dir, "anchor_hello.xz");
    writeFile(p, &HELLO_XZ);
    defer rm(p);

    const r = try run(a, &.{ zxzBin(), "-dc", p });
    defer r.free(a);
    try testing.expectEqual(@as(?u8, 0), r.exit);
    try testing.expectEqualStrings(HELLO_PLAIN, r.stdout);
}

// 2. CRITICAL path-safety anchor: a corrupt .xz must NOT delete the source and
//    must NOT leave a partial output file, and must exit nonzero.
//    (Mutation target: reintroducing the unconditional unlink makes this RED.)
test "corrupt .xz: source kept, no partial output, nonzero exit" {
    const a = testing.allocator;
    const dir = baseDir();
    var pb: [4096]u8 = undefined;
    var ob: [4096]u8 = undefined;
    const src = joinZ(&pb, dir, "corrupt.xz");
    const out = joinZ(&ob, dir, "corrupt");
    // Valid magic, garbage afterwards -> decode fails partway.
    var bad: [64]u8 = undefined;
    @memcpy(bad[0..6], &[_]u8{ 0xFD, '7', 'z', 'X', 'Z', 0x00 });
    for (bad[6..]) |*x| x.* = 0x00;
    bad[10] = 0xFF; // corrupt stream-flags CRC region
    writeFile(src, &bad);
    rm(out);
    defer rm(src);
    defer rm(out);

    const r = try run(a, &.{ zxzBin(), "-d", src });
    defer r.free(a);
    try testing.expect(r.exit == null or r.exit.? != 0); // nonzero exit
    try testing.expect(exists(src)); // source MUST survive a failed decode
    try testing.expect(!exists(out)); // no empty/partial output left behind
}

// 3. Multi-stream (concatenated) anchor: two GNU-produced streams back-to-back
//    must both decode. xz's default is LZMA_CONCATENATED.
test "concatenated .xz streams both decode" {
    const a = testing.allocator;
    const dir = baseDir();
    var pb: [4096]u8 = undefined;
    const p = joinZ(&pb, dir, "double.xz");
    var doubled: [HELLO_XZ.len * 2]u8 = undefined;
    @memcpy(doubled[0..HELLO_XZ.len], &HELLO_XZ);
    @memcpy(doubled[HELLO_XZ.len..], &HELLO_XZ);
    writeFile(p, &doubled);
    defer rm(p);

    const r = try run(a, &.{ zxzBin(), "-dc", p });
    defer r.free(a);
    try testing.expectEqual(@as(?u8, 0), r.exit);
    try testing.expectEqualStrings("hello\nhello\n", r.stdout);
}

// 4. GNU-parity: missing input file exits nonzero (GNU xz exits 1).
test "missing file exits nonzero" {
    const a = testing.allocator;
    const dir = baseDir();
    var pb: [4096]u8 = undefined;
    const p = joinZ(&pb, dir, "definitely_missing.xz");
    rm(p);

    const r = try run(a, &.{ zxzBin(), "-dc", p });
    defer r.free(a);
    try testing.expect(r.exit == null or r.exit.? != 0);
}

// 5. Compression is refused with a nonzero exit and produces no file
//    (never a silent no-op success).
test "compress request refused nonzero, no output file" {
    const a = testing.allocator;
    const dir = baseDir();
    var pb: [4096]u8 = undefined;
    var ob: [4096]u8 = undefined;
    const src = joinZ(&pb, dir, "plain.txt");
    const out = joinZ(&ob, dir, "plain.txt.xz");
    writeFile(src, "some plain text\n");
    rm(out);
    defer rm(src);
    defer rm(out);

    const r = try run(a, &.{ zxzBin(), src });
    defer r.free(a);
    try testing.expect(r.exit == null or r.exit.? != 0);
    try testing.expect(!exists(out));
}

// 6. Overwrite protection: without -f an existing output is not clobbered and
//    the command fails; with -f it is overwritten with the decoded content.
test "overwrite protection without -f; -f overwrites" {
    const a = testing.allocator;
    const dir = baseDir();
    var xb: [4096]u8 = undefined;
    var ob: [4096]u8 = undefined;
    const xzp = joinZ(&xb, dir, "over.xz");
    const outp = joinZ(&ob, dir, "over");
    writeFile(xzp, &HELLO_XZ); // decodes to "hello\n" at path "over"
    writeFile(outp, "PRECIOUS"); // pre-existing output file
    defer rm(xzp);
    defer rm(outp);

    // Without -f: must fail and leave "over" untouched.
    {
        const r = try run(a, &.{ zxzBin(), "-d", xzp });
        defer r.free(a);
        try testing.expect(r.exit == null or r.exit.? != 0);
        const content = readFile(a, outp) orelse return error.MissingFile;
        defer a.free(content);
        try testing.expectEqualStrings("PRECIOUS", content);
    }
    // With -f: overwrite with decoded content.
    {
        const r = try run(a, &.{ zxzBin(), "-df", xzp });
        defer r.free(a);
        try testing.expectEqual(@as(?u8, 0), r.exit);
        const content = readFile(a, outp) orelse return error.MissingFile;
        defer a.free(content);
        try testing.expectEqualStrings(HELLO_PLAIN, content);
    }
}

// 7. Legacy .lzma is refused without deleting the source (doc-drift fix).
test "lzma input refused, source kept" {
    const a = testing.allocator;
    const dir = baseDir();
    var pb: [4096]u8 = undefined;
    const p = joinZ(&pb, dir, "legacy.lzma");
    writeFile(p, "not really lzma");
    defer rm(p);

    const r = try run(a, &.{ zxzBin(), "-d", p });
    defer r.free(a);
    try testing.expect(r.exit == null or r.exit.? != 0);
    try testing.expect(exists(p)); // source must survive the rejection
}

// 8. --version / --help go to stdout (not stderr), exit 0.
test "version and help print to stdout, exit 0" {
    const a = testing.allocator;
    {
        const r = try run(a, &.{ zxzBin(), "--version" });
        defer r.free(a);
        try testing.expectEqual(@as(?u8, 0), r.exit);
        try testing.expect(r.stdout.len > 0);
        try testing.expect(std.mem.indexOf(u8, r.stdout, "zxz") != null);
    }
    {
        const r = try run(a, &.{ zxzBin(), "--help" });
        defer r.free(a);
        try testing.expectEqual(@as(?u8, 0), r.exit);
        try testing.expect(std.mem.indexOf(u8, r.stdout, "Usage") != null);
    }
}

// 9. Live cross-check against the real GNU xz binary, when available:
//    for a spread of payloads, GNU xz produces the .xz, zxz decodes it, and the
//    result must equal BOTH the original bytes AND `xz -dc` output.
test "live GNU xz cross-check over multiple payloads" {
    const a = testing.allocator;
    const xz = xzBin() orelse {
        std.debug.print("XZ_BIN not available/executable; skipping live cross-check\n", .{});
        return error.SkipZigTest;
    };
    const dir = baseDir();

    const payloads = [_][]const u8{
        "",
        "a",
        "The quick brown fox jumps over the lazy dog.\n",
        "\x00\x01\x02\x03\xff\xfe\xfd binary\x00 data\n",
    };

    for (payloads, 0..) |payload, idx| {
        var namebuf: [64]u8 = undefined;
        const name = std.fmt.bufPrint(&namebuf, "live{d}.bin", .{idx}) catch unreachable;
        var pb: [4096]u8 = undefined;
        var xb: [4096]u8 = undefined;
        const plain = joinZ(&pb, dir, name);
        writeFile(plain, payload);
        defer rm(plain);

        var xnamebuf: [80]u8 = undefined;
        const xname = std.fmt.bufPrint(&xnamebuf, "live{d}.bin.xz", .{idx}) catch unreachable;
        const xzp = joinZ(&xb, dir, xname);
        defer rm(xzp);

        // GNU xz produces the compressed fixture (external producer).
        {
            const c = try run(a, &.{ xz, "-c", "-k", plain });
            defer c.free(a);
            try testing.expectEqual(@as(?u8, 0), c.exit);
            writeFile(xzp, c.stdout);
        }

        // zxz decodes it.
        const zr = try run(a, &.{ zxzBin(), "-dc", xzp });
        defer zr.free(a);
        try testing.expectEqual(@as(?u8, 0), zr.exit);
        try testing.expectEqualSlices(u8, payload, zr.stdout);

        // And GNU xz -dc must agree byte-for-byte with zxz.
        const gr = try run(a, &.{ xz, "-dc", xzp });
        defer gr.free(a);
        try testing.expectEqual(@as(?u8, 0), gr.exit);
        try testing.expectEqualSlices(u8, gr.stdout, zr.stdout);
    }
}
