//! Zig Code Generator
//!
//! Generates type-safe Zig code from parsed SVD device descriptions.
//! Output uses packed structs for registers and MMIO for access.

const std = @import("std");
const svd = @import("svd.zig");

/// Simple writer wrapper for ArrayListUnmanaged
const ArrayWriter = struct {
    list: *std.ArrayListUnmanaged(u8),
    allocator: std.mem.Allocator,

    pub fn print(self: *ArrayWriter, comptime fmt: []const u8, args: anytype) !void {
        var buf: [4096]u8 = undefined;
        const result = std.fmt.bufPrint(&buf, fmt, args) catch return error.BufferOverflow;
        try self.list.appendSlice(self.allocator, result);
    }

    pub fn writeAll(self: *ArrayWriter, data: []const u8) !void {
        try self.list.appendSlice(self.allocator, data);
    }
};

/// Generate Zig source code for a device
pub fn generate(allocator: std.mem.Allocator, device: svd.Device) ![]u8 {
    var output: std.ArrayListUnmanaged(u8) = .empty;
    errdefer output.deinit(allocator);

    var writer = ArrayWriter{ .list = &output, .allocator = allocator };

    // Header
    try writer.print(
        \\//! Auto-generated register definitions for {s}
        \\//!
        \\//! Generated by Register Forge from SVD
        \\//! DO NOT EDIT - regenerate from SVD file
        \\
        \\const mmio = struct {{
        \\    pub fn Mmio(comptime T: type, comptime addr: u32) type {{
        \\        return struct {{
        \\            const ptr: *volatile T = @ptrFromInt(addr);
        \\            pub inline fn read() T {{ return ptr.*; }}
        \\            pub inline fn write(value: T) void {{ ptr.* = value; }}
        \\            pub inline fn modify(fields: anytype) void {{
        \\                var value = ptr.*;
        \\                inline for (@typeInfo(@TypeOf(fields)).@"struct".fields) |field| {{
        \\                    @field(value, field.name) = @field(fields, field.name);
        \\                }}
        \\                ptr.* = value;
        \\            }}
        \\        }};
        \\    }}
        \\}};
        \\
        \\
    , .{device.name});

    // Generate each peripheral
    for (device.peripherals) |peripheral| {
        try generatePeripheral(&writer, peripheral);
    }

    return output.toOwnedSlice(allocator);
}

fn generatePeripheral(writer: *ArrayWriter, peripheral: svd.Peripheral) !void {
    // Peripheral comment
    try writer.print(
        \\// =============================================================================
        \\// {s}
        \\// {s}
        \\// Base Address: 0x{X:0>8}
        \\// =============================================================================
        \\
        \\pub const {s} = struct {{
        \\    pub const base_address: u32 = 0x{X:0>8};
        \\
        \\
    , .{
        peripheral.name,
        peripheral.description,
        peripheral.base_address,
        toLower(peripheral.name),
        peripheral.base_address,
    });

    // Generate each register
    for (peripheral.registers) |register| {
        try generateRegister(writer, peripheral.base_address, register);
    }

    try writer.writeAll("};\n\n");
}

fn generateRegister(writer: *ArrayWriter, base_address: u32, register: svd.Register) !void {
    const full_address = base_address + register.offset;

    // Generate packed struct for register fields
    try writer.print(
        \\    /// {s}
        \\    /// Offset: 0x{X:0>2}
        \\    pub const {s} = mmio.Mmio(packed struct {{
        \\
    , .{ register.description, register.offset, register.name });

    // Sort fields by bit offset and generate
    var sorted_fields: [64]svd.Field = undefined;
    var field_count: usize = 0;
    for (register.fields) |f| {
        if (field_count < 64) {
            sorted_fields[field_count] = f;
            field_count += 1;
        }
    }

    // Simple bubble sort by bit_offset
    for (0..field_count) |i| {
        for (i + 1..field_count) |j| {
            if (sorted_fields[j].bit_offset < sorted_fields[i].bit_offset) {
                const tmp = sorted_fields[i];
                sorted_fields[i] = sorted_fields[j];
                sorted_fields[j] = tmp;
            }
        }
    }

    // Generate fields with padding for gaps
    var current_bit: u8 = 0;
    var reserved_count: u32 = 0;

    for (sorted_fields[0..field_count]) |field| {
        // Add padding if there's a gap
        if (field.bit_offset > current_bit) {
            const gap = field.bit_offset - current_bit;
            try writer.print("        _reserved{d}: u{d} = 0,\n", .{ reserved_count, gap });
            reserved_count += 1;
        }

        // Generate field
        const field_type = getFieldType(field.bit_width);
        try writer.print("        /// {s}\n", .{field.description});
        try writer.print("        {s}: {s},\n", .{ field.name, field_type });

        current_bit = field.bit_offset + field.bit_width;
    }

    // Add padding to fill to register size
    if (current_bit < register.size) {
        const gap = register.size - current_bit;
        try writer.print("        _reserved{d}: u{d} = 0,\n", .{ reserved_count, gap });
    }

    try writer.print(
        \\    }}, 0x{X:0>8});
        \\
        \\
    , .{full_address});
}

fn getFieldType(bit_width: u8) []const u8 {
    return switch (bit_width) {
        1 => "bool",
        2 => "u2",
        3 => "u3",
        4 => "u4",
        5 => "u5",
        6 => "u6",
        7 => "u7",
        8 => "u8",
        16 => "u16",
        32 => "u32",
        else => "u8", // fallback
    };
}

fn toLower(s: []const u8) []const u8 {
    // For simplicity, just return as-is (in production would properly lowercase)
    return s;
}

test "generate basic" {
    const allocator = std.testing.allocator;

    const device = svd.Device{
        .name = "TEST",
        .description = "Test Device",
        .peripherals = &[_]svd.Peripheral{
            .{
                .name = "GPIO",
                .description = "GPIO Port",
                .base_address = 0x40000000,
                .registers = &[_]svd.Register{
                    .{
                        .name = "ODR",
                        .description = "Output Data",
                        .offset = 0x00,
                        .size = 32,
                        .fields = &[_]svd.Field{
                            .{ .name = "OD0", .description = "Bit 0", .bit_offset = 0, .bit_width = 1 },
                        },
                    },
                },
            },
        },
    };

    const output = try generate(allocator, device);
    defer allocator.free(output);

    try std.testing.expect(std.mem.indexOf(u8, output, "GPIO") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "ODR") != null);
}
