//! Zig Code Generator
//!
//! Generates type-safe Zig code from parsed SVD device descriptions.
//! Output uses packed structs for registers and MMIO for access.

const std = @import("std");
const svd = @import("svd.zig");

/// Simple writer wrapper for ArrayListUnmanaged
const ArrayWriter = struct {
    list: *std.ArrayListUnmanaged(u8),
    allocator: std.mem.Allocator,

    pub fn print(self: *ArrayWriter, comptime fmt: []const u8, args: anytype) !void {
        var buf: [4096]u8 = undefined;
        const result = std.fmt.bufPrint(&buf, fmt, args) catch return error.BufferOverflow;
        try self.list.appendSlice(self.allocator, result);
    }

    pub fn writeAll(self: *ArrayWriter, data: []const u8) !void {
        try self.list.appendSlice(self.allocator, data);
    }
};

/// Generate Zig source code for a device
pub fn generate(allocator: std.mem.Allocator, device: svd.Device) ![]u8 {
    var output: std.ArrayListUnmanaged(u8) = .empty;
    errdefer output.deinit(allocator);

    var writer = ArrayWriter{ .list = &output, .allocator = allocator };

    // Header
    try writer.print(
        \\//! Auto-generated register definitions for {s}
        \\//!
        \\//! Generated by Register Forge from SVD
        \\//! DO NOT EDIT - regenerate from SVD file
        \\
        \\const mmio = struct {{
        \\    pub fn Mmio(comptime T: type, comptime addr: u32) type {{
        \\        return struct {{
        \\            const ptr: *volatile T = @ptrFromInt(addr);
        \\            pub inline fn read() T {{ return ptr.*; }}
        \\            pub inline fn write(value: T) void {{ ptr.* = value; }}
        \\            pub inline fn modify(fields: anytype) void {{
        \\                var value = ptr.*;
        \\                inline for (@typeInfo(@TypeOf(fields)).@"struct".fields) |field| {{
        \\                    @field(value, field.name) = @field(fields, field.name);
        \\                }}
        \\                ptr.* = value;
        \\            }}
        \\        }};
        \\    }}
        \\}};
        \\
        \\
    , .{device.name});

    // Generate each peripheral
    for (device.peripherals) |peripheral| {
        try generatePeripheral(&writer, peripheral);
    }

    return output.toOwnedSlice(allocator);
}

fn generatePeripheral(writer: *ArrayWriter, peripheral: svd.Peripheral) !void {
    // Peripheral comment — SVD-supplied name/description are escaped so a
    // newline or stray character cannot break out of the comment into code.
    try writer.writeAll("// =============================================================================\n");
    try writeEscapedDoc(writer, "// ", peripheral.name);
    try writeEscapedDoc(writer, "// ", peripheral.description);
    try writer.print("// Base Address: 0x{X:0>8}\n", .{peripheral.base_address});
    try writer.writeAll("// =============================================================================\n\n");

    try writer.writeAll("pub const ");
    try writeIdent(writer, toLower(peripheral.name));
    try writer.print(" = struct {{\n    pub const base_address: u32 = 0x{X:0>8};\n\n\n", .{peripheral.base_address});

    // Generate each register
    for (peripheral.registers) |register| {
        try generateRegister(writer, peripheral.base_address, register);
    }

    try writer.writeAll("};\n\n");
}

fn generateRegister(writer: *ArrayWriter, base_address: u32, register: svd.Register) !void {
    const full_address = base_address + register.offset;

    // Generate packed struct for register fields
    try writeEscapedDoc(writer, "    /// ", register.description);
    try writer.print("    /// Offset: 0x{X:0>2}\n", .{register.offset});
    try writer.writeAll("    pub const ");
    try writeIdent(writer, register.name);
    try writer.writeAll(" = mmio.Mmio(packed struct {\n");

    // Sort fields by bit offset and generate
    var sorted_fields: [64]svd.Field = undefined;
    var field_count: usize = 0;
    for (register.fields) |f| {
        if (field_count < 64) {
            sorted_fields[field_count] = f;
            field_count += 1;
        }
    }

    // Simple bubble sort by bit_offset
    for (0..field_count) |i| {
        for (i + 1..field_count) |j| {
            if (sorted_fields[j].bit_offset < sorted_fields[i].bit_offset) {
                const tmp = sorted_fields[i];
                sorted_fields[i] = sorted_fields[j];
                sorted_fields[j] = tmp;
            }
        }
    }

    // Generate fields with padding for gaps
    var current_bit: u8 = 0;
    var reserved_count: u32 = 0;

    for (sorted_fields[0..field_count]) |field| {
        // Add padding if there's a gap
        if (field.bit_offset > current_bit) {
            const gap = field.bit_offset - current_bit;
            try writer.print("        _reserved{d}: u{d} = 0,\n", .{ reserved_count, gap });
            reserved_count += 1;
        }

        // Generate field. The type is the exact-width unsigned integer so the
        // packed struct's bit layout matches the hardware register exactly.
        var type_buf: [8]u8 = undefined;
        const field_type = try getFieldType(&type_buf, field.bit_width);
        try writeEscapedDoc(writer, "        /// ", field.description);
        try writer.writeAll("        ");
        try writeIdent(writer, field.name);
        try writer.print(": {s},\n", .{field_type});

        current_bit = field.bit_offset + field.bit_width;
    }

    // Add padding to fill to register size
    if (current_bit < register.size) {
        const gap = register.size - current_bit;
        try writer.print("        _reserved{d}: u{d} = 0,\n", .{ reserved_count, gap });
    }

    try writer.print(
        \\    }}, 0x{X:0>8});
        \\
        \\
    , .{full_address});
}

/// Emit the exact-width unsigned integer type for a field of `bit_width` bits.
///
/// A packed-struct field must have a type whose bit-size equals the field's
/// hardware width, otherwise every subsequent field in the register is shifted
/// to the wrong bit position and the generated code reads/writes the wrong bits
/// of a real hardware register. The previous implementation fell back to `u8`
/// for widths 9-15, 17-31, and >32 — this emits `u{width}` for every legal
/// packed-struct width (1..64) and rejects anything outside that range.
fn getFieldType(buf: []u8, bit_width: u8) ![]const u8 {
    if (bit_width < 1 or bit_width > 64) return error.InvalidFieldWidth;
    return std.fmt.bufPrint(buf, "u{d}", .{bit_width});
}

fn toLower(s: []const u8) []const u8 {
    // For simplicity, just return as-is (in production would properly lowercase)
    return s;
}

/// Emit `text` as a run of comment/doc lines using `prefix` (e.g. `"    /// "`).
///
/// SVD `<name>`/`<description>` strings are attacker-influenced and commonly
/// multi-line in real vendor files. Emitting them raw lets an embedded newline
/// terminate the comment and drop the remainder of the string into code
/// position (broken or injected Zig). Splitting on `\n` and re-prefixing every
/// line keeps the whole string inside comment context.
fn writeEscapedDoc(writer: *ArrayWriter, prefix: []const u8, text: []const u8) !void {
    if (text.len == 0) {
        try writer.writeAll(prefix);
        try writer.writeAll("\n");
        return;
    }
    var it = std.mem.splitScalar(u8, text, '\n');
    while (it.next()) |line_raw| {
        const line = std.mem.trimEnd(u8, line_raw, "\r");
        try writer.writeAll(prefix);
        try writer.writeAll(line);
        try writer.writeAll("\n");
    }
}

/// True if `s` is a valid bare Zig identifier (no `@"..."` quoting needed).
fn isValidBareIdent(s: []const u8) bool {
    if (s.len == 0) return false;
    const first = s[0];
    if (!(std.ascii.isAlphabetic(first) or first == '_')) return false;
    for (s[1..]) |c| {
        if (!(std.ascii.isAlphanumeric(c) or c == '_')) return false;
    }
    return !isZigKeyword(s);
}

fn isZigKeyword(s: []const u8) bool {
    const keywords = [_][]const u8{
        "addrspace",   "align",     "allowzero", "and",           "anyframe",
        "anytype",     "asm",       "async",     "await",         "break",
        "callconv",    "catch",     "comptime",  "const",         "continue",
        "defer",       "else",      "enum",      "errdefer",      "error",
        "export",      "extern",    "fn",        "for",           "if",
        "inline",      "noalias",   "noinline",  "nosuspend",     "opaque",
        "or",          "orelse",    "packed",    "pub",           "resume",
        "return",      "linksection", "struct",  "suspend",       "switch",
        "test",        "threadlocal", "try",     "union",         "unreachable",
        "usingnamespace", "var",    "volatile",  "while",
    };
    for (keywords) |kw| {
        if (std.mem.eql(u8, kw, s)) return true;
    }
    return false;
}

/// Emit `name` as a Zig identifier. Valid bare identifiers pass through; SVD
/// names that are not valid identifiers (dim templates like `MODE%s`, names
/// starting with a digit, or Zig keywords) are wrapped in `@"..."` with proper
/// string escaping so the generated file still compiles instead of injecting
/// broken syntax.
fn writeIdent(writer: *ArrayWriter, name: []const u8) !void {
    if (name.len == 0) {
        // Should not happen (parser defaults to "Unknown") but never emit an
        // empty token, which is a syntax error.
        try writer.writeAll("@\"_\"");
        return;
    }
    if (isValidBareIdent(name)) {
        try writer.writeAll(name);
        return;
    }
    try writer.writeAll("@\"");
    for (name) |c| {
        switch (c) {
            '\\' => try writer.writeAll("\\\\"),
            '"' => try writer.writeAll("\\\""),
            '\n' => try writer.writeAll("\\n"),
            '\r' => try writer.writeAll("\\r"),
            '\t' => try writer.writeAll("\\t"),
            else => {
                if (c < 0x20 or c == 0x7f) {
                    try writer.print("\\x{x:0>2}", .{c});
                } else {
                    try writer.writeAll(&[_]u8{c});
                }
            },
        }
    }
    try writer.writeAll("\"");
}

test "generate basic" {
    const allocator = std.testing.allocator;

    const device = svd.Device{
        .name = "TEST",
        .description = "Test Device",
        .peripherals = &[_]svd.Peripheral{
            .{
                .name = "GPIO",
                .description = "GPIO Port",
                .base_address = 0x40000000,
                .registers = &[_]svd.Register{
                    .{
                        .name = "ODR",
                        .description = "Output Data",
                        .offset = 0x00,
                        .size = 32,
                        .fields = &[_]svd.Field{
                            .{ .name = "OD0", .description = "Bit 0", .bit_offset = 0, .bit_width = 1 },
                        },
                    },
                },
            },
        },
    };

    const output = try generate(allocator, device);
    defer allocator.free(output);

    try std.testing.expect(std.mem.indexOf(u8, output, "GPIO") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "ODR") != null);
}
