//! Differential corpus generator (test-only).
//!
//! `crypto-refgen <zig-forge root>` rewrites
//!   programs/simd_crypto_ffi/testdata/differential/rust_reference.txt
//!   programs/zig-quantum-encryption/testdata/differential/rust_reference.txt
//! Inputs are expanded from per-record `seed`s with SplitMix64 (`expand` below; the Zig tests
//! carry an identical copy), so the files stay small while inputs run to tens of kilobytes.
//! Every expected output is computed here by a reference crate, never by the code under test.

use std::fmt::Write as _;
use std::str::FromStr;

use bitcoin::bip32::{DerivationPath, Xpriv, Xpub};
use bitcoin::secp256k1::{self, Secp256k1};
use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256, Sha512};

struct SplitMix64(u64);
impl SplitMix64 {
    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }
    fn below(&mut self, n: u64) -> u64 {
        self.next() % n
    }
}

/// `len` bytes: the little-endian bytes of successive SplitMix64 outputs seeded with `seed`.
fn expand(seed: u64, len: usize) -> Vec<u8> {
    let mut g = SplitMix64(seed);
    let mut out = Vec::with_capacity(len + 8);
    while out.len() < len {
        out.extend_from_slice(&g.next().to_le_bytes());
    }
    out.truncate(len);
    out
}

fn fixed<const N: usize>(seed: u64) -> [u8; N] {
    expand(seed, N).try_into().unwrap()
}

struct Out {
    text: String,
    count: usize,
}
impl Out {
    fn new(header: &[&str]) -> Self {
        let mut text = String::new();
        for h in header {
            writeln!(text, "# {h}").unwrap();
        }
        text.push_str("# Generated by tools/crypto-refgen; regenerate with scripts/crypto-conformance.sh --regen.\n\n");
        Out { text, count: 0 }
    }
    fn rec(&mut self, fields: &[(&str, String)]) {
        for (k, v) in fields {
            writeln!(self.text, "{k}={v}").unwrap();
        }
        self.text.push('\n');
        self.count += 1;
    }
}

/// Lengths that straddle every block and padding boundary of SHA-256 (64), SHA-512 (128),
/// BLAKE3 (64-byte blocks, 1024-byte chunks, SIMD batches of up to 16 chunks) and ChaCha20.
const EDGE_LENS: &[usize] = &[
    0, 1, 2, 3, 31, 32, 33, 55, 56, 57, 63, 64, 65, 111, 112, 113, 127, 128, 129, 191, 192, 255, 256, 257,
    511, 512, 513, 1023, 1024, 1025, 2047, 2048, 2049, 3072, 4095, 4096, 4097, 8192, 16383, 16384, 16385,
];

fn simd_crypto_ffi(g: &mut SplitMix64) -> Out {
    let mut o = Out::new(&[
        "Differential corpus for programs/simd_crypto_ffi (quantum_* C ABI) against the Rust crates walletcore links:",
        "sha2 0.10.9, hmac 0.12.1, pbkdf2 0.12.2, blake3 1.8.5, chacha20 0.9.1, ripemd 0.1.3, k256 0.13.4,",
        "bitcoin 0.32.102 (bip32, bech32 addresses; ECDSA via secp256k1 0.29.1 = libsecp256k1 through secp256k1-sys 0.10.1).",
        "Inputs: SplitMix64 expansion of `seed` (see expand() in tools/crypto-refgen/src/main.rs).",
    ]);
    let mut lens: Vec<usize> = EDGE_LENS.to_vec();
    for _ in 0..60 {
        lens.push(g.below(3000) as usize);
    }
    for &len in &lens {
        let seed = g.next();
        let m = expand(seed, len);
        let h1 = Sha256::digest(&m);
        o.rec(&[("kind", "sha256".into()), ("seed", seed.to_string()), ("len", len.to_string()), ("out", hex(&h1))]);
        o.rec(&[("kind", "sha256d".into()), ("seed", seed.to_string()), ("len", len.to_string()), ("out", hex(&Sha256::digest(h1)))]);
        o.rec(&[("kind", "sha512".into()), ("seed", seed.to_string()), ("len", len.to_string()), ("out", hex(&Sha512::digest(&m)))]);
        o.rec(&[("kind", "ripemd160".into()), ("seed", seed.to_string()), ("len", len.to_string()), ("out", hex(&ripemd::Ripemd160::digest(&m)))]);
        let outlen = 1 + g.below(300) as usize;
        let mut x = vec![0u8; outlen];
        let mut h = blake3::Hasher::new();
        h.update(&m);
        h.finalize_xof().fill(&mut x);
        o.rec(&[("kind", "blake3".into()), ("seed", seed.to_string()), ("len", len.to_string()), ("outlen", outlen.to_string()), ("out", hex(&x))]);
    }
    // BLAKE3 inputs large enough for every SIMD degree (up to 16 chunks in flight) and the tree.
    for len in [16 * 1024, 16 * 1024 + 1, 31 * 1024 + 7, 64 * 1024, 100_000, 1 << 20] {
        let seed = g.next();
        let m = expand(seed, len);
        o.rec(&[("kind", "blake3".into()), ("seed", seed.to_string()), ("len", len.to_string()), ("outlen", "32".into()), ("out", hex(blake3::hash(&m).as_bytes()))]);
    }
    for i in 0..120 {
        let (ks, ms) = (g.next(), g.next());
        // Keys around and beyond the 64/128-byte block size exercise the hash-the-key path.
        let klen = if i < 20 { [0, 1, 32, 63, 64, 65, 127, 128, 129, 200][i % 10] } else { g.below(260) as usize };
        let mlen = g.below(2000) as usize;
        let (k, m) = (expand(ks, klen), expand(ms, mlen));
        let mut a = Hmac::<Sha256>::new_from_slice(&k).unwrap();
        a.update(&m);
        let mut b = Hmac::<Sha512>::new_from_slice(&k).unwrap();
        b.update(&m);
        let common = |kind: &str, out: Vec<u8>| -> Vec<(&'static str, String)> {
            vec![("kind", kind.to_string()), ("kseed", ks.to_string()), ("klen", klen.to_string()), ("mseed", ms.to_string()), ("mlen", mlen.to_string()), ("out", hex(&out))]
        };
        o.rec(&common("hmac_sha256", a.finalize().into_bytes().to_vec()));
        o.rec(&common("hmac_sha512", b.finalize().into_bytes().to_vec()));
    }
    for _ in 0..40 {
        let (ps, ss) = (g.next(), g.next());
        let (plen, slen) = (g.below(150) as usize, g.below(150) as usize);
        let iters = 1 + g.below(40) as u32;
        let dklen = 1 + g.below(200) as usize;
        let (p, s) = (expand(ps, plen), expand(ss, slen));
        let mut a = vec![0u8; dklen];
        pbkdf2::pbkdf2_hmac::<Sha256>(&p, &s, iters, &mut a);
        let mut b = vec![0u8; dklen];
        pbkdf2::pbkdf2_hmac::<Sha512>(&p, &s, iters, &mut b);
        for (kind, out) in [("pbkdf2_sha256", a), ("pbkdf2_sha512", b)] {
            o.rec(&[("kind", kind.into()), ("pseed", ps.to_string()), ("plen", plen.to_string()), ("sseed", ss.to_string()), ("slen", slen.to_string()), ("iterations", iters.to_string()), ("dklen", dklen.to_string()), ("out", hex(&out))]);
        }
    }
    {
        use chacha20::cipher::{KeyIvInit, StreamCipher, StreamCipherSeek};
        let mut lens: Vec<usize> = EDGE_LENS.to_vec();
        for _ in 0..40 {
            lens.push(g.below(5000) as usize);
        }
        for len in lens {
            let (ks, ns, ms) = (g.next(), g.next(), g.next());
            let counter = if g.below(4) == 0 { 0 } else { g.below(1 << 31) as u32 };
            let key: [u8; 32] = fixed(ks);
            let nonce: [u8; 12] = fixed(ns);
            let mut buf = expand(ms, len);
            let mut c = chacha20::ChaCha20::new(&key.into(), &nonce.into());
            c.seek(counter as u64 * 64);
            c.apply_keystream(&mut buf);
            o.rec(&[("kind", "chacha20".into()), ("kseed", ks.to_string()), ("nseed", ns.to_string()), ("counter", counter.to_string()), ("mseed", ms.to_string()), ("len", len.to_string()), ("out", hex(&buf))]);
        }
    }
    let secp = Secp256k1::new();
    for _ in 0..200 {
        let ks = g.next();
        let sk = match secp256k1::SecretKey::from_slice(&fixed::<32>(ks)) {
            Ok(k) => k,
            Err(_) => continue,
        };
        let pk = secp256k1::PublicKey::from_secret_key(&secp, &sk);
        let digest: [u8; 32] = fixed(g.next());
        let sig = secp.sign_ecdsa(&secp256k1::Message::from_digest(digest), &sk); // RFC 6979, low-S
        // Second, independent reference: RustCrypto k256 (RFC 6979), normalised to low-S.
        let k = k256::ecdsa::SigningKey::from_bytes(&sk.secret_bytes().into()).unwrap();
        let ks2: k256::ecdsa::Signature = k256::ecdsa::signature::hazmat::PrehashSigner::sign_prehash(&k, &digest).unwrap();
        let ks2 = ks2.normalize_s().unwrap_or(ks2);
        assert_eq!(ks2.to_bytes().as_slice(), sig.serialize_compact(), "libsecp256k1 and k256 disagree");
        let pkc = pk.serialize();
        o.rec(&[
            ("kind", "secp256k1".into()),
            ("sk", hex(&sk.secret_bytes())),
            ("digest", hex(&digest)),
            ("pubkey", hex(&pkc)),
            ("hash160", hex(&ripemd::Ripemd160::digest(Sha256::digest(pkc)))),
            ("sig", hex(&sig.serialize_compact())),
            ("der", hex(&sig.serialize_der())),
            ("p2wpkh_main", bitcoin::Address::p2wpkh(&bitcoin::CompressedPublicKey(pk), bitcoin::Network::Bitcoin).to_string()),
            ("p2wpkh_test", bitcoin::Address::p2wpkh(&bitcoin::CompressedPublicKey(pk), bitcoin::Network::Testnet).to_string()),
        ]);
    }
    for _ in 0..60 {
        let seed_s = g.next();
        let slen = [16, 32, 64][g.below(3) as usize];
        let seed = expand(seed_s, slen);
        let master = Xpriv::new_master(bitcoin::Network::Bitcoin, &seed).unwrap();
        let depth = 1 + g.below(5);
        let mut path = String::from("m");
        for _ in 0..depth {
            let hard = g.below(2) == 0;
            let idx = g.below(1 << 31);
            write!(path, "/{idx}{}", if hard { "'" } else { "" }).unwrap();
        }
        let dp = DerivationPath::from_str(&path).unwrap();
        let xprv = master.derive_priv(&secp, &dp).unwrap();
        let xpub = Xpub::from_priv(&secp, &xprv);
        o.rec(&[
            ("kind", "bip32".into()),
            ("seed", seed_s.to_string()),
            ("seedlen", slen.to_string()),
            ("path", path),
            ("xprv", hex(&xprv.encode())),
            ("xpub", hex(&xpub.encode())),
        ]);
    }
    o
}

fn zig_quantum_encryption(g: &mut SplitMix64) -> Out {
    use hkdf::Hkdf;
    use sha3::Sha3_256;
    let mut o = Out::new(&[
        "Differential corpus for programs/zig-quantum-encryption (hybrid KEM classical half and combiners)",
        "against x25519-dalek 2.0.1, sha3 0.10.9 and hkdf 0.12.4 (HKDF over HMAC-SHA3-256).",
        "Inputs: SplitMix64 expansion of `seed` (see expand() in tools/crypto-refgen/src/main.rs).",
    ]);
    for _ in 0..100 {
        let (ss, us) = (g.next(), g.next());
        let scalar: [u8; 32] = fixed(ss);
        let u: [u8; 32] = fixed(us);
        let pk = x25519_dalek::PublicKey::from(&x25519_dalek::StaticSecret::from(scalar));
        o.rec(&[
            ("kind", "x25519".into()),
            ("scalar", hex(&scalar)),
            ("u", hex(&u)),
            ("shared", hex(&x25519_dalek::x25519(scalar, u))),
            ("public", hex(pk.as_bytes())),
        ]);
    }
    for _ in 0..100 {
        let ss_m: [u8; 32] = fixed(g.next());
        let ss_x: [u8; 32] = fixed(g.next());
        let ct_x: [u8; 32] = fixed(g.next());
        let pk_x: [u8; 32] = fixed(g.next());
        let mut h = Sha3_256::new();
        h.update(b"HYBRID-ML-KEM-768-X25519-v1");
        h.update(ss_m);
        h.update(ss_x);
        let v1 = h.finalize();
        let ikm = [ss_m, ss_x, ct_x, pk_x].concat();
        let mut v2 = [0u8; 32];
        Hkdf::<Sha3_256>::new(Some(b""), &ikm).expand(b"HYBRID-ML-KEM-768-X25519-v2", &mut v2).unwrap();
        o.rec(&[
            ("kind", "combiner".into()),
            ("ss_m", hex(&ss_m)),
            ("ss_x", hex(&ss_x)),
            ("ct_x", hex(&ct_x)),
            ("pk_x", hex(&pk_x)),
            ("v1", hex(&v1)),
            ("v2", hex(&v2)),
        ]);
    }
    o
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn main() {
    let root = std::env::args().nth(1).expect("usage: crypto-refgen <zig-forge root>");
    for (dir, out) in [
        ("programs/simd_crypto_ffi", simd_crypto_ffi(&mut SplitMix64(0x5157_4b43_4f4e_4631))),
        ("programs/zig-quantum-encryption", zig_quantum_encryption(&mut SplitMix64(0x5157_4b43_4f4e_4632))),
    ] {
        let d = format!("{root}/{dir}/testdata/differential");
        std::fs::create_dir_all(&d).unwrap();
        std::fs::write(format!("{d}/rust_reference.txt"), &out.text).unwrap();
        println!("{dir}: {} records", out.count);
    }
}
