//! Raw EndpointSecurity bindings, transcribed from the macOS SDK headers
//! (`ESTypes.h`, `ESMessageCore.h`, `ESMessage.h`, `ESClient.h`).
//!
//! Names are the C names on purpose: this file is meant to be read beside the
//! header, and `anchors_test.zig` looks types and enumerators up by those names
//! to compare every size, offset and value against what Apple's clang computes
//! (`layout_anchors.zig`, generated by `tools/gen_layout_anchors.py`).
//!
//! Conventions:
//!   * `_Nonnull T *` → `*T`; `_Nullable T *` → `?*T`; arrays of tokens → `?[*]T`.
//!   * Anonymous C unions/structs become named fields (`v` for the versioned
//!     tail union, `fields` for the struct inside it); the anchor test resolves
//!     C's promoted member names through those.
//!   * Fields marked "message version >= N" in the header are only meaningful
//!     when `es_message_t.version >= N`; see `versioned.zig` for the table and
//!     the gated accessors in `message.zig` / `event.zig`.
//!   * Functions introduced after macOS 10.15 are weak imports (`?*const fn`)
//!     so a binary can load on an older macOS and check for null at runtime.
//!
//! `es_handler_block_t` is an Objective-C block; build one with
//! `darwin_kit.block` (see `client.zig`). A plain function pointer is not a
//! block and must never be passed to `es_new_client`.

const std = @import("std");
const darwin = @import("darwin_kit");
pub const enums = @import("enums.zig");

// ───────────────────────────── ESTypes.h ─────────────────────────────

pub const es_event_id_t = extern struct { reserved: [32]u8 };

pub const es_action_type_t = enums.es_action_type_t;
pub const es_set_or_clear_t = enums.es_set_or_clear_t;
pub const es_proc_check_type_t = enums.es_proc_check_type_t;
pub const es_xpc_domain_type_t = enums.es_xpc_domain_type_t;
pub const es_bootstrap_target_type_t = enums.es_bootstrap_target_type_t;
pub const es_authentication_type_t = enums.es_authentication_type_t;
pub const es_sudo_plugin_type_t = enums.es_sudo_plugin_type_t;
pub const es_event_type_t = enums.es_event_type_t;
pub const es_auth_result_t = enums.es_auth_result_t;
pub const es_result_type_t = enums.es_result_type_t;
pub const es_return_t = enums.es_return_t;
pub const es_respond_result_t = enums.es_respond_result_t;
pub const es_new_client_result_t = enums.es_new_client_result_t;
pub const es_clear_cache_result_t = enums.es_clear_cache_result_t;
pub const es_mute_path_type_t = enums.es_mute_path_type_t;
pub const es_address_type_t = enums.es_address_type_t;
pub const es_mute_inversion_type_t = enums.es_mute_inversion_type_t;
pub const es_mute_inverted_return_t = enums.es_mute_inverted_return_t;
pub const es_authorization_rule_class_t = enums.es_authorization_rule_class_t;
pub const es_od_member_type_t = enums.es_od_member_type_t;
pub const es_od_account_type_t = enums.es_od_account_type_t;
pub const es_od_record_type_t = enums.es_od_record_type_t;
pub const es_gatekeeper_user_override_file_type_t = enums.es_gatekeeper_user_override_file_type_t;
pub const es_tcc_event_type_t = enums.es_tcc_event_type_t;
pub const es_tcc_authorization_right_t = enums.es_tcc_authorization_right_t;
pub const es_tcc_authorization_reason_t = enums.es_tcc_authorization_reason_t;
pub const es_tcc_identity_type_t = enums.es_tcc_identity_type_t;
pub const es_cs_validation_category_t = enums.es_cs_validation_category_t;
pub const es_auto_unlock_type_t = enums.es_auto_unlock_type_t;
pub const es_btm_item_type_t = enums.es_btm_item_type_t;
pub const es_destination_type_t = enums.es_destination_type_t;
pub const es_get_task_type_t = enums.es_get_task_type_t;
pub const es_openssh_login_result_type_t = enums.es_openssh_login_result_type_t;
pub const es_mount_disposition_t = enums.es_mount_disposition_t;
pub const es_proc_suspend_resume_type_t = enums.es_proc_suspend_resume_type_t;
pub const es_profile_source_t = enums.es_profile_source_t;
pub const es_touchid_mode_t = enums.es_touchid_mode_t;
pub const es_deadline_miss_mode_t = enums.es_deadline_miss_mode_t;

pub const es_cdhash_t = [20]u8;
pub const es_sha256_t = [32]u8;

/// Length-prefixed binary blob.
pub const es_token_t = extern struct {
    size: usize,
    data: ?[*]const u8,

    pub fn slice(self: es_token_t) []const u8 {
        return if (self.data) |d| d[0..self.size] else "";
    }
};

/// Length-prefixed string; `length` is what strlen() would return and the
/// bytes are usually followed by a NUL, but only `length` bytes are guaranteed.
pub const es_string_token_t = extern struct {
    length: usize,
    data: ?[*]const u8,

    pub fn slice(self: es_string_token_t) []const u8 {
        return if (self.data) |d| d[0..self.length] else "";
    }
};

pub const es_muted_path_t = extern struct {
    type: es_mute_path_type_t,
    event_count: usize,
    events: ?[*]const es_event_type_t,
    path: es_string_token_t,

    pub fn eventSlice(self: es_muted_path_t) []const es_event_type_t {
        return if (self.events) |e| e[0..self.event_count] else &.{};
    }
};

pub const es_muted_paths_t = extern struct {
    count: usize,
    paths: ?[*]const es_muted_path_t,

    pub fn slice(self: es_muted_paths_t) []const es_muted_path_t {
        return if (self.paths) |p| p[0..self.count] else &.{};
    }
};

pub const es_muted_process_t = extern struct {
    audit_token: audit_token_t,
    event_count: usize,
    events: ?[*]const es_event_type_t,

    pub fn eventSlice(self: es_muted_process_t) []const es_event_type_t {
        return if (self.events) |e| e[0..self.event_count] else &.{};
    }
};

pub const es_muted_processes_t = extern struct {
    count: usize,
    processes: ?[*]const es_muted_process_t,

    pub fn slice(self: es_muted_processes_t) []const es_muted_process_t {
        return if (self.processes) |p| p[0..self.count] else &.{};
    }
};

pub const es_signed_file_info_t = extern struct {
    cdhash: es_cdhash_t,
    signing_id: es_string_token_t,
    team_id: es_string_token_t,
};

pub const es_lightweight_code_requirement_t = extern struct {
    team_id: es_string_token_t,
    signing_id: es_string_token_t,
};

// ─────────────────────── system types ES embeds ───────────────────────

pub const audit_token_t = darwin.AuditToken;
pub const uuid_t = [16]u8;
pub const pid_t = std.c.pid_t;
pub const uid_t = std.c.uid_t;
pub const gid_t = std.c.gid_t;
pub const mode_t = u16;
pub const dev_t = i32;
pub const cpu_type_t = i32;
pub const cpu_subtype_t = i32;
pub const user_addr_t = u64;
pub const user_size_t = u64;
pub const timespec = std.c.timespec;
pub const timeval = std.c.timeval;
pub const struct_stat = std.c.Stat;

/// `acl_t` from <sys/acl.h>: pointer to an opaque `struct _acl`. ES documents
/// that the ACLs it delivers are not compatible with the `acl_*` functions.
pub const acl_t = ?*opaque {};

/// <sys/attr.h>
pub const struct_attrlist = extern struct {
    bitmapcount: u16,
    reserved: u16,
    commonattr: u32,
    volattr: u32,
    dirattr: u32,
    fileattr: u32,
    forkattr: u32,
};

/// <sys/mount.h>, 64-bit inode layout (`struct statfs` with `_DARWIN_FEATURE_64_BIT_INODE`).
pub const struct_statfs = extern struct {
    f_bsize: u32,
    f_iosize: i32,
    f_blocks: u64,
    f_bfree: u64,
    f_bavail: u64,
    f_files: u64,
    f_ffree: u64,
    f_fsid: extern struct { val: [2]i32 },
    f_owner: uid_t,
    f_type: u32,
    f_flags: u32,
    f_fssubtype: u32,
    f_fstypename: [16]u8,
    f_mntonname: [1024]u8,
    f_mntfromname: [1024]u8,
    f_flags_ext: u32,
    f_reserved: [7]u32,

    pub fn mountPoint(self: *const struct_statfs) []const u8 {
        return std.mem.sliceTo(&self.f_mntonname, 0);
    }
    pub fn mountedFrom(self: *const struct_statfs) []const u8 {
        return std.mem.sliceTo(&self.f_mntfromname, 0);
    }
    pub fn fsTypeName(self: *const struct_statfs) []const u8 {
        return std.mem.sliceTo(&self.f_fstypename, 0);
    }
};

// ─────────────────────────── ESMessageCore.h ───────────────────────────

pub const es_file_t = extern struct {
    path: es_string_token_t,
    path_truncated: bool,
    stat: struct_stat,
};

pub const es_process_t = extern struct {
    audit_token: audit_token_t,
    ppid: pid_t,
    original_ppid: pid_t,
    group_id: pid_t,
    session_id: pid_t,
    codesigning_flags: u32,
    is_platform_binary: bool,
    is_es_client: bool,
    cdhash: es_cdhash_t,
    signing_id: es_string_token_t,
    team_id: es_string_token_t,
    executable: *es_file_t,
    tty: ?*es_file_t, // message version >= 2
    start_time: timeval, // message version >= 3
    responsible_audit_token: audit_token_t, // message version >= 4
    parent_audit_token: audit_token_t, // message version >= 4
    cs_validation_category: es_cs_validation_category_t, // message version >= 10
    reserved: [16]u8,
    cdhash_full: es_token_t, // message version >= 11
};

// ───────────────────────────── ESMessage.h ─────────────────────────────

pub const es_thread_t = extern struct { thread_id: u64 };

pub const es_thread_state_t = extern struct {
    flavor: c_int,
    state: es_token_t,
};

pub const es_fd_t = extern struct {
    fd: i32,
    fdtype: u32,
    pipe: extern struct { pipe_id: u64 },

    /// `fdtype` value for which `pipe` is valid (libproc PROX_FDTYPE_PIPE).
    pub const fdtype_pipe: u32 = 6;
};

pub const es_btm_launch_item_t = extern struct {
    item_type: es_btm_item_type_t,
    legacy: bool,
    managed: bool,
    uid: uid_t,
    item_url: es_string_token_t,
    app_url: es_string_token_t,
};

pub const es_profile_t = extern struct {
    identifier: es_string_token_t,
    uuid: es_string_token_t,
    install_source: es_profile_source_t,
    organization: es_string_token_t,
    display_name: es_string_token_t,
    scope: es_string_token_t,
};

pub const es_event_exec_t = extern struct {
    target: *es_process_t,
    dyld_exec_path: es_string_token_t, // message version >= 7
    v: extern union {
        reserved: [64]u8,
        fields: extern struct {
            script: ?*es_file_t, // message version >= 2
            cwd: *es_file_t, // message version >= 3
            last_fd: c_int, // message version >= 4
            image_cputype: cpu_type_t, // message version >= 6
            image_cpusubtype: cpu_subtype_t, // message version >= 6
        },
    },
};

pub const es_event_tcc_modify_t = extern struct {
    service: es_string_token_t,
    identity: es_string_token_t,
    identity_type: es_tcc_identity_type_t,
    update_type: es_tcc_event_type_t,
    instigator_token: audit_token_t,
    instigator: ?*es_process_t,
    responsible_token: ?*audit_token_t,
    responsible: ?*es_process_t,
    right: es_tcc_authorization_right_t,
    reason: es_tcc_authorization_reason_t,
};

pub const es_event_open_t = extern struct {
    fflag: i32,
    file: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_kextload_t = extern struct {
    identifier: es_string_token_t,
    reserved: [64]u8,
};

pub const es_event_kextunload_t = extern struct {
    identifier: es_string_token_t,
    reserved: [64]u8,
};

pub const es_event_unlink_t = extern struct {
    target: *es_file_t,
    parent_dir: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_mmap_t = extern struct {
    protection: i32,
    max_protection: i32,
    flags: i32,
    file_pos: u64,
    source: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_link_t = extern struct {
    source: *es_file_t,
    target_dir: *es_file_t,
    target_filename: es_string_token_t,
    reserved: [64]u8,
};

pub const es_event_mount_t = extern struct {
    statfs: *struct_statfs,
    disposition: es_mount_disposition_t, // message version >= 8
    reserved: [60]u8,
};

pub const es_event_unmount_t = extern struct {
    statfs: *struct_statfs,
    reserved: [64]u8,
};

pub const es_event_remount_t = extern struct {
    statfs: *struct_statfs,
    remount_flags: u64, // message version >= 8
    disposition: es_mount_disposition_t, // message version >= 8
    reserved: [52]u8,
};

pub const es_event_fork_t = extern struct {
    child: *es_process_t,
    reserved: [64]u8,
};

pub const es_event_mprotect_t = extern struct {
    protection: i32,
    address: user_addr_t,
    size: user_size_t,
    reserved: [64]u8,
};

pub const es_event_signal_t = extern struct {
    sig: c_int,
    target: *es_process_t,
    instigator: ?*es_process_t, // message version >= 9
    reserved: [56]u8,
};

pub const es_event_rename_t = extern struct {
    source: *es_file_t,
    destination_type: es_destination_type_t,
    destination: extern union {
        existing_file: *es_file_t,
        new_path: extern struct {
            dir: *es_file_t,
            filename: es_string_token_t,
        },
    },
    reserved: [64]u8,
};

pub const es_event_setextattr_t = extern struct {
    target: *es_file_t,
    extattr: es_string_token_t,
    reserved: [64]u8,
};

pub const es_event_getextattr_t = extern struct {
    target: *es_file_t,
    extattr: es_string_token_t,
    reserved: [64]u8,
};

pub const es_event_deleteextattr_t = extern struct {
    target: *es_file_t,
    extattr: es_string_token_t,
    reserved: [64]u8,
};

pub const es_event_setmode_t = extern struct {
    mode: mode_t,
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_setflags_t = extern struct {
    flags: u32,
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_setowner_t = extern struct {
    uid: uid_t,
    gid: gid_t,
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_close_t = extern struct {
    modified: bool,
    target: *es_file_t,
    v: extern union {
        reserved: [64]u8,
        fields: extern struct {
            was_mapped_writable: bool, // message version >= 6
        },
    },
};

pub const es_event_create_t = extern struct {
    destination_type: es_destination_type_t,
    destination: extern union {
        existing_file: *es_file_t,
        new_path: extern struct {
            dir: *es_file_t,
            filename: es_string_token_t,
            mode: mode_t,
        },
    },
    reserved2: [16]u8,
    v: extern union {
        reserved: [48]u8,
        fields: extern struct {
            acl: acl_t, // message version >= 2
        },
    },
};

pub const es_event_exit_t = extern struct {
    stat: c_int,
    reserved: [64]u8,
};

pub const es_event_exchangedata_t = extern struct {
    file1: *es_file_t,
    file2: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_write_t = extern struct {
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_truncate_t = extern struct {
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_chdir_t = extern struct {
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_stat_t = extern struct {
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_chroot_t = extern struct {
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_listextattr_t = extern struct {
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_iokit_open_t = extern struct {
    user_client_type: u32,
    user_client_class: es_string_token_t,
    parent_registry_id: u64, // message version >= 10
    parent_path: es_string_token_t, // message version >= 10
    reserved: [40]u8,
};

pub const es_event_get_task_t = extern struct {
    target: *es_process_t,
    type: es_get_task_type_t, // message version >= 5
    reserved: [60]u8,
};

pub const es_event_get_task_read_t = extern struct {
    target: *es_process_t,
    type: es_get_task_type_t, // message version >= 5
    reserved: [60]u8,
};

pub const es_event_get_task_inspect_t = extern struct {
    target: *es_process_t,
    type: es_get_task_type_t, // message version >= 5
    reserved: [60]u8,
};

pub const es_event_get_task_name_t = extern struct {
    target: *es_process_t,
    type: es_get_task_type_t, // message version >= 5
    reserved: [60]u8,
};

pub const es_event_getattrlist_t = extern struct {
    attrlist: struct_attrlist,
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_setattrlist_t = extern struct {
    attrlist: struct_attrlist,
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_file_provider_update_t = extern struct {
    source: *es_file_t,
    target_path: es_string_token_t,
    reserved: [64]u8,
};

pub const es_event_file_provider_materialize_t = extern struct {
    instigator: ?*es_process_t,
    source: *es_file_t,
    target: *es_file_t,
    instigator_token: audit_token_t, // message version >= 8
    reserved: [32]u8,
};

pub const es_event_readlink_t = extern struct {
    source: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_lookup_t = extern struct {
    source_dir: *es_file_t,
    relative_target: es_string_token_t,
    reserved: [64]u8,
};

pub const es_event_access_t = extern struct {
    mode: i32,
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_utimes_t = extern struct {
    target: *es_file_t,
    atime: timespec,
    mtime: timespec,
    reserved: [64]u8,
};

pub const es_event_clone_t = extern struct {
    source: *es_file_t,
    target_dir: *es_file_t,
    target_name: es_string_token_t,
    reserved: [64]u8,
};

pub const es_event_copyfile_t = extern struct {
    source: *es_file_t,
    target_file: ?*es_file_t,
    target_dir: *es_file_t,
    target_name: es_string_token_t,
    mode: mode_t,
    flags: i32,
    reserved: [56]u8,
};

pub const es_event_fcntl_t = extern struct {
    target: *es_file_t,
    cmd: i32,
    reserved: [64]u8,
};

pub const es_event_readdir_t = extern struct {
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_fsgetpath_t = extern struct {
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_settime_t = extern struct {
    reserved: [64]u8,
};

pub const es_event_dup_t = extern struct {
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_uipc_bind_t = extern struct {
    dir: *es_file_t,
    filename: es_string_token_t,
    mode: mode_t,
    reserved: [64]u8,
};

pub const es_event_uipc_connect_t = extern struct {
    file: *es_file_t,
    domain: c_int,
    type: c_int,
    protocol: c_int,
    reserved: [64]u8,
};

pub const es_event_setacl_t = extern struct {
    target: *es_file_t,
    set_or_clear: es_set_or_clear_t,
    acl: extern union {
        set: acl_t,
    },
    reserved: [64]u8,
};

pub const es_event_pty_grant_t = extern struct {
    dev: dev_t,
    reserved: [64]u8,
};

pub const es_event_pty_close_t = extern struct {
    dev: dev_t,
    reserved: [64]u8,
};

pub const es_event_proc_check_t = extern struct {
    target: ?*es_process_t,
    type: es_proc_check_type_t,
    flavor: c_int,
    reserved: [64]u8,
};

pub const es_event_searchfs_t = extern struct {
    attrlist: struct_attrlist,
    target: *es_file_t,
    reserved: [64]u8,
};

pub const es_event_proc_suspend_resume_t = extern struct {
    target: ?*es_process_t,
    type: es_proc_suspend_resume_type_t,
    reserved: [64]u8,
};

pub const es_event_cs_invalidated_t = extern struct {
    reserved: [64]u8,
};

pub const es_event_trace_t = extern struct {
    target: *es_process_t,
    reserved: [64]u8,
};

pub const es_event_remote_thread_create_t = extern struct {
    target: *es_process_t,
    thread_state: ?*es_thread_state_t,
    reserved: [64]u8,
};

pub const es_event_setuid_t = extern struct {
    uid: uid_t,
    reserved: [64]u8,
};

pub const es_event_setgid_t = extern struct {
    gid: uid_t,
    reserved: [64]u8,
};

pub const es_event_seteuid_t = extern struct {
    euid: uid_t,
    reserved: [64]u8,
};

pub const es_event_setegid_t = extern struct {
    egid: uid_t,
    reserved: [64]u8,
};

pub const es_event_setreuid_t = extern struct {
    ruid: uid_t,
    euid: uid_t,
    reserved: [64]u8,
};

pub const es_event_setregid_t = extern struct {
    rgid: uid_t,
    egid: uid_t,
    reserved: [64]u8,
};

pub const es_event_authentication_od_t = extern struct {
    instigator: ?*es_process_t,
    record_type: es_string_token_t,
    record_name: es_string_token_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_authentication_touchid_t = extern struct {
    instigator: ?*es_process_t,
    touchid_mode: es_touchid_mode_t,
    has_uid: bool,
    uid: extern union { uid: uid_t },
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_authentication_token_t = extern struct {
    instigator: ?*es_process_t,
    pubkey_hash: es_string_token_t,
    token_id: es_string_token_t,
    kerberos_principal: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_authentication_auto_unlock_t = extern struct {
    username: es_string_token_t,
    type: es_auto_unlock_type_t,
};

pub const es_event_authentication_t = extern struct {
    success: bool,
    type: es_authentication_type_t,
    data: extern union {
        od: *es_event_authentication_od_t,
        touchid: *es_event_authentication_touchid_t,
        token: *es_event_authentication_token_t,
        auto_unlock: *es_event_authentication_auto_unlock_t,
    },
};

pub const es_event_xp_malware_detected_t = extern struct {
    signature_version: es_string_token_t,
    malware_identifier: es_string_token_t,
    incident_identifier: es_string_token_t,
    detected_path: es_string_token_t,
    detected_executable: es_string_token_t, // message version >= 10
};

pub const es_event_xp_malware_remediated_t = extern struct {
    signature_version: es_string_token_t,
    malware_identifier: es_string_token_t,
    incident_identifier: es_string_token_t,
    action_type: es_string_token_t,
    success: bool,
    result_description: es_string_token_t,
    remediated_path: es_string_token_t,
    remediated_process_audit_token: ?*audit_token_t,
};

pub const es_graphical_session_id_t = u32;

pub const es_event_lw_session_login_t = extern struct {
    username: es_string_token_t,
    graphical_session_id: es_graphical_session_id_t,
};

pub const es_event_lw_session_logout_t = extern struct {
    username: es_string_token_t,
    graphical_session_id: es_graphical_session_id_t,
};

pub const es_event_lw_session_lock_t = extern struct {
    username: es_string_token_t,
    graphical_session_id: es_graphical_session_id_t,
};

pub const es_event_lw_session_unlock_t = extern struct {
    username: es_string_token_t,
    graphical_session_id: es_graphical_session_id_t,
};

pub const es_event_screensharing_attach_t = extern struct {
    success: bool,
    source_address_type: es_address_type_t,
    source_address: es_string_token_t,
    viewer_appleid: es_string_token_t,
    authentication_type: es_string_token_t,
    authentication_username: es_string_token_t,
    session_username: es_string_token_t,
    existing_session: bool,
    graphical_session_id: es_graphical_session_id_t,
};

pub const es_event_screensharing_detach_t = extern struct {
    source_address_type: es_address_type_t,
    source_address: es_string_token_t,
    viewer_appleid: es_string_token_t,
    graphical_session_id: es_graphical_session_id_t,
};

pub const es_event_openssh_login_t = extern struct {
    success: bool,
    result_type: es_openssh_login_result_type_t,
    source_address_type: es_address_type_t,
    source_address: es_string_token_t,
    username: es_string_token_t,
    has_uid: bool,
    uid: extern union { uid: uid_t },
};

pub const es_event_openssh_logout_t = extern struct {
    source_address_type: es_address_type_t,
    source_address: es_string_token_t,
    username: es_string_token_t,
    uid: uid_t,
};

pub const es_event_login_login_t = extern struct {
    success: bool,
    failure_message: es_string_token_t,
    username: es_string_token_t,
    has_uid: bool,
    uid: extern union { uid: uid_t },
};

pub const es_event_login_logout_t = extern struct {
    username: es_string_token_t,
    uid: uid_t,
};

pub const es_event_btm_launch_item_add_t = extern struct {
    instigator: ?*es_process_t,
    app: ?*es_process_t,
    item: *es_btm_launch_item_t,
    executable_path: es_string_token_t,
    instigator_token: ?*audit_token_t, // message version >= 8
    app_token: ?*audit_token_t, // message version >= 8
};

pub const es_event_btm_launch_item_remove_t = extern struct {
    instigator: ?*es_process_t,
    app: ?*es_process_t,
    item: *es_btm_launch_item_t,
    instigator_token: ?*audit_token_t, // message version >= 8
    app_token: ?*audit_token_t, // message version >= 8
};

pub const es_event_su_t = extern struct {
    success: bool,
    failure_message: es_string_token_t,
    from_uid: uid_t,
    from_username: es_string_token_t,
    has_to_uid: bool,
    to_uid: extern union { uid: uid_t },
    to_username: es_string_token_t,
    shell: es_string_token_t,
    argc: usize,
    argv: ?[*]es_string_token_t,
    env_count: usize,
    env: ?[*]es_string_token_t,
};

pub const es_sudo_reject_info_t = extern struct {
    plugin_name: es_string_token_t,
    plugin_type: es_sudo_plugin_type_t,
    failure_message: es_string_token_t,
};

pub const es_event_sudo_t = extern struct {
    success: bool,
    reject_info: ?*es_sudo_reject_info_t,
    has_from_uid: bool,
    from_uid: extern union { uid: uid_t },
    from_username: es_string_token_t,
    has_to_uid: bool,
    to_uid: extern union { uid: uid_t },
    to_username: es_string_token_t,
    command: es_string_token_t,
};

pub const es_event_profile_add_t = extern struct {
    instigator: ?*es_process_t,
    is_update: bool,
    profile: *es_profile_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_profile_remove_t = extern struct {
    instigator: ?*es_process_t,
    profile: *es_profile_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_authorization_petition_t = extern struct {
    instigator: ?*es_process_t,
    petitioner: ?*es_process_t,
    flags: u32,
    right_count: usize,
    rights: ?[*]es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
    petitioner_token: audit_token_t, // message version >= 8
};

pub const es_authorization_result_t = extern struct {
    right_name: es_string_token_t,
    rule_class: es_authorization_rule_class_t,
    granted: bool,
};

pub const es_event_authorization_judgement_t = extern struct {
    instigator: ?*es_process_t,
    petitioner: ?*es_process_t,
    return_code: c_int,
    result_count: usize,
    results: ?[*]es_authorization_result_t,
    instigator_token: audit_token_t, // message version >= 8
    petitioner_token: audit_token_t, // message version >= 8
};

pub const es_od_member_id_t = extern struct {
    member_type: es_od_member_type_t,
    member_value: extern union {
        uuid: uuid_t,
        name: es_string_token_t,
    },
};

pub const es_event_od_group_add_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    group_name: es_string_token_t,
    member: *es_od_member_id_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_od_group_remove_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    group_name: es_string_token_t,
    member: *es_od_member_id_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_od_member_id_array_t = extern struct {
    member_type: es_od_member_type_t,
    member_count: usize,
    member_array: extern union {
        uuids: [*]uuid_t,
        names: [*]es_string_token_t,
    },
};

pub const es_event_od_group_set_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    group_name: es_string_token_t,
    members: *es_od_member_id_array_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_od_modify_password_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    account_type: es_od_account_type_t,
    account_name: es_string_token_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_od_disable_user_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    user_name: es_string_token_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_od_enable_user_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    user_name: es_string_token_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_od_attribute_value_add_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    record_type: es_od_record_type_t,
    record_name: es_string_token_t,
    attribute_name: es_string_token_t,
    attribute_value: es_string_token_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_od_attribute_value_remove_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    record_type: es_od_record_type_t,
    record_name: es_string_token_t,
    attribute_name: es_string_token_t,
    attribute_value: es_string_token_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_od_attribute_set_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    record_type: es_od_record_type_t,
    record_name: es_string_token_t,
    attribute_name: es_string_token_t,
    attribute_value_count: usize,
    attribute_values: ?[*]es_string_token_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_od_create_user_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    user_name: es_string_token_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_od_create_group_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    group_name: es_string_token_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_od_delete_user_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    user_name: es_string_token_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_od_delete_group_t = extern struct {
    instigator: ?*es_process_t,
    error_code: c_int,
    group_name: es_string_token_t,
    node_name: es_string_token_t,
    db_path: es_string_token_t,
    instigator_token: audit_token_t, // message version >= 8
};

pub const es_event_xpc_connect_t = extern struct {
    service_name: es_string_token_t,
    service_domain_type: es_xpc_domain_type_t,
};

pub const es_event_bootstrap_check_in_t = extern struct {
    instigator: ?*es_process_t,
    instigator_token: audit_token_t,
    service_name: es_string_token_t,
};

pub const es_event_bootstrap_look_up_t = extern struct {
    instigator: ?*es_process_t,
    instigator_token: audit_token_t,
    service_name: es_string_token_t,
    target_type: es_bootstrap_target_type_t,
    target: extern union {
        process: extern struct {
            target: ?*es_process_t,
            target_token: audit_token_t,
            job_label: es_string_token_t,
        },
        job: extern struct {
            job_label: es_string_token_t,
            lwcr: ?*es_lightweight_code_requirement_t,
        },
    },
};

pub const es_event_gatekeeper_user_override_t = extern struct {
    file_type: es_gatekeeper_user_override_file_type_t,
    file: extern union {
        file_path: es_string_token_t,
        file: *es_file_t,
    },
    sha256: ?*es_sha256_t,
    signing_info: ?*es_signed_file_info_t,
};

/// Event payloads. Members introduced before macOS 13 are stored inline;
/// later ones are pointers into the message.
pub const es_events_t = extern union {
    access: es_event_access_t,
    chdir: es_event_chdir_t,
    chroot: es_event_chroot_t,
    clone: es_event_clone_t,
    close: es_event_close_t,
    copyfile: es_event_copyfile_t,
    create: es_event_create_t,
    cs_invalidated: es_event_cs_invalidated_t,
    deleteextattr: es_event_deleteextattr_t,
    dup: es_event_dup_t,
    exchangedata: es_event_exchangedata_t,
    exec: es_event_exec_t,
    exit: es_event_exit_t,
    file_provider_materialize: es_event_file_provider_materialize_t,
    file_provider_update: es_event_file_provider_update_t,
    fcntl: es_event_fcntl_t,
    fork: es_event_fork_t,
    fsgetpath: es_event_fsgetpath_t,
    get_task: es_event_get_task_t,
    get_task_read: es_event_get_task_read_t,
    get_task_inspect: es_event_get_task_inspect_t,
    get_task_name: es_event_get_task_name_t,
    getattrlist: es_event_getattrlist_t,
    getextattr: es_event_getextattr_t,
    iokit_open: es_event_iokit_open_t,
    kextload: es_event_kextload_t,
    kextunload: es_event_kextunload_t,
    link: es_event_link_t,
    listextattr: es_event_listextattr_t,
    lookup: es_event_lookup_t,
    mmap: es_event_mmap_t,
    mount: es_event_mount_t,
    mprotect: es_event_mprotect_t,
    open: es_event_open_t,
    proc_check: es_event_proc_check_t,
    proc_suspend_resume: es_event_proc_suspend_resume_t,
    pty_close: es_event_pty_close_t,
    pty_grant: es_event_pty_grant_t,
    readdir: es_event_readdir_t,
    readlink: es_event_readlink_t,
    remote_thread_create: es_event_remote_thread_create_t,
    remount: es_event_remount_t,
    rename: es_event_rename_t,
    searchfs: es_event_searchfs_t,
    setacl: es_event_setacl_t,
    setattrlist: es_event_setattrlist_t,
    setextattr: es_event_setextattr_t,
    setflags: es_event_setflags_t,
    setmode: es_event_setmode_t,
    setowner: es_event_setowner_t,
    settime: es_event_settime_t,
    setuid: es_event_setuid_t,
    setgid: es_event_setgid_t,
    seteuid: es_event_seteuid_t,
    setegid: es_event_setegid_t,
    setreuid: es_event_setreuid_t,
    setregid: es_event_setregid_t,
    signal: es_event_signal_t,
    stat: es_event_stat_t,
    trace: es_event_trace_t,
    truncate: es_event_truncate_t,
    uipc_bind: es_event_uipc_bind_t,
    uipc_connect: es_event_uipc_connect_t,
    unlink: es_event_unlink_t,
    unmount: es_event_unmount_t,
    utimes: es_event_utimes_t,
    write: es_event_write_t,

    authentication: *es_event_authentication_t,
    xp_malware_detected: *es_event_xp_malware_detected_t,
    xp_malware_remediated: *es_event_xp_malware_remediated_t,
    lw_session_login: *es_event_lw_session_login_t,
    lw_session_logout: *es_event_lw_session_logout_t,
    lw_session_lock: *es_event_lw_session_lock_t,
    lw_session_unlock: *es_event_lw_session_unlock_t,
    screensharing_attach: *es_event_screensharing_attach_t,
    screensharing_detach: *es_event_screensharing_detach_t,
    openssh_login: *es_event_openssh_login_t,
    openssh_logout: *es_event_openssh_logout_t,
    login_login: *es_event_login_login_t,
    login_logout: *es_event_login_logout_t,
    btm_launch_item_add: *es_event_btm_launch_item_add_t,
    btm_launch_item_remove: *es_event_btm_launch_item_remove_t,
    profile_add: *es_event_profile_add_t,
    profile_remove: *es_event_profile_remove_t,
    su: *es_event_su_t,
    authorization_petition: *es_event_authorization_petition_t,
    authorization_judgement: *es_event_authorization_judgement_t,
    sudo: *es_event_sudo_t,
    od_group_add: *es_event_od_group_add_t,
    od_group_remove: *es_event_od_group_remove_t,
    od_group_set: *es_event_od_group_set_t,
    od_modify_password: *es_event_od_modify_password_t,
    od_disable_user: *es_event_od_disable_user_t,
    od_enable_user: *es_event_od_enable_user_t,
    od_attribute_value_add: *es_event_od_attribute_value_add_t,
    od_attribute_value_remove: *es_event_od_attribute_value_remove_t,
    od_attribute_set: *es_event_od_attribute_set_t,
    od_create_user: *es_event_od_create_user_t,
    od_create_group: *es_event_od_create_group_t,
    od_delete_user: *es_event_od_delete_user_t,
    od_delete_group: *es_event_od_delete_group_t,
    xpc_connect: *es_event_xpc_connect_t,
    gatekeeper_user_override: *es_event_gatekeeper_user_override_t,
    tcc_modify: *es_event_tcc_modify_t,
    bootstrap_check_in: *es_event_bootstrap_check_in_t,
    bootstrap_look_up: *es_event_bootstrap_look_up_t,
};

pub const es_result_t = extern struct {
    result_type: es_result_type_t,
    result: extern union {
        auth: es_auth_result_t,
        flags: u32,
        reserved: [32]u8,
    },
};

/// One delivered event. The C struct ends with a flexible `uint64_t opaque[]`
/// that is omitted here; never copy an `es_message_t` by value, only hold
/// pointers into what ES delivered and retain/release them.
pub const es_message_t = extern struct {
    version: u32,
    time: timespec,
    mach_time: u64,
    deadline: u64,
    process: *es_process_t,
    seq_num: u64, // message version >= 2
    action_type: es_action_type_t,
    action: extern union {
        auth: es_event_id_t,
        notify: es_result_t,
    },
    event_type: es_event_type_t,
    event: es_events_t,
    thread: ?*es_thread_t, // message version >= 4
    global_seq_num: u64, // message version >= 4
};

// ESMessage.h functions

pub extern "c" fn es_message_size(msg: *const es_message_t) usize;
pub extern "c" fn es_copy_message(msg: *const es_message_t) ?*es_message_t;
pub extern "c" fn es_free_message(msg: *es_message_t) void;
/// macOS 11.0+
pub const es_retain_message = @extern(?*const fn (msg: *const es_message_t) callconv(.c) void, .{ .name = "es_retain_message", .linkage = .weak });
/// macOS 11.0+
pub const es_release_message = @extern(?*const fn (msg: *const es_message_t) callconv(.c) void, .{ .name = "es_release_message", .linkage = .weak });
pub extern "c" fn es_exec_arg_count(event: *const es_event_exec_t) u32;
pub extern "c" fn es_exec_env_count(event: *const es_event_exec_t) u32;
/// macOS 11.0+
pub const es_exec_fd_count = @extern(?*const fn (event: *const es_event_exec_t) callconv(.c) u32, .{ .name = "es_exec_fd_count", .linkage = .weak });
pub extern "c" fn es_exec_arg(event: *const es_event_exec_t, index: u32) es_string_token_t;
pub extern "c" fn es_exec_env(event: *const es_event_exec_t, index: u32) es_string_token_t;
/// macOS 11.0+
pub const es_exec_fd = @extern(?*const fn (event: *const es_event_exec_t, index: u32) callconv(.c) *const es_fd_t, .{ .name = "es_exec_fd", .linkage = .weak });
/// macOS 27.0+. Returns a retained `xpc_object_t` (dictionary) or null.
pub const es_exec_entitlements = @extern(?*const fn (event: *const es_event_exec_t) callconv(.c) ?*anyopaque, .{ .name = "es_exec_entitlements", .linkage = .weak });

// ───────────────────────────── ESClient.h ─────────────────────────────

pub const es_client_t = opaque {};

/// `void (^)(es_client_t *, const es_message_t *)` — an Objective-C block pointer.
pub const es_handler_block_t = darwin.block.Ref;

pub extern "c" fn es_subscribe(client: *es_client_t, events: [*]const es_event_type_t, event_count: u32) es_return_t;
pub extern "c" fn es_unsubscribe(client: *es_client_t, events: [*]const es_event_type_t, event_count: u32) es_return_t;
pub extern "c" fn es_unsubscribe_all(client: *es_client_t) es_return_t;
pub extern "c" fn es_subscriptions(client: *es_client_t, count: *usize, subscriptions: *?[*]es_event_type_t) es_return_t;
pub extern "c" fn es_respond_auth_result(client: *es_client_t, message: *const es_message_t, result: es_auth_result_t, cache: bool) es_respond_result_t;
pub extern "c" fn es_respond_flags_result(client: *es_client_t, message: *const es_message_t, authorized_flags: u32, cache: bool) es_respond_result_t;
pub extern "c" fn es_mute_process(client: *es_client_t, audit_token: *const audit_token_t) es_return_t;
/// macOS 12.0+
pub const es_mute_process_events = @extern(?*const fn (client: *es_client_t, audit_token: *const audit_token_t, events: [*]const es_event_type_t, event_count: usize) callconv(.c) es_return_t, .{ .name = "es_mute_process_events", .linkage = .weak });
pub extern "c" fn es_unmute_process(client: *es_client_t, audit_token: *const audit_token_t) es_return_t;
/// macOS 12.0+
pub const es_unmute_process_events = @extern(?*const fn (client: *es_client_t, audit_token: *const audit_token_t, events: [*]const es_event_type_t, event_count: usize) callconv(.c) es_return_t, .{ .name = "es_unmute_process_events", .linkage = .weak });
/// Deprecated in macOS 12.0 in favour of `es_muted_processes_events`.
pub extern "c" fn es_muted_processes(client: *es_client_t, count: *usize, audit_tokens: *?[*]audit_token_t) es_return_t;
/// macOS 12.0+
pub const es_muted_processes_events = @extern(?*const fn (client: *es_client_t, muted_processes: *?*es_muted_processes_t) callconv(.c) es_return_t, .{ .name = "es_muted_processes_events", .linkage = .weak });
/// macOS 12.0+
pub const es_release_muted_processes = @extern(?*const fn (muted_processes: *es_muted_processes_t) callconv(.c) void, .{ .name = "es_release_muted_processes", .linkage = .weak });
/// macOS 12.0+
pub const es_mute_path = @extern(?*const fn (client: *es_client_t, path: [*:0]const u8, type: es_mute_path_type_t) callconv(.c) es_return_t, .{ .name = "es_mute_path", .linkage = .weak });
/// macOS 12.0+
pub const es_mute_path_events = @extern(?*const fn (client: *es_client_t, path: [*:0]const u8, type: es_mute_path_type_t, events: [*]const es_event_type_t, event_count: usize) callconv(.c) es_return_t, .{ .name = "es_mute_path_events", .linkage = .weak });
/// Deprecated in macOS 12.0 in favour of `es_mute_path`.
pub extern "c" fn es_mute_path_prefix(client: *es_client_t, path_prefix: [*:0]const u8) es_return_t;
/// Deprecated in macOS 12.0 in favour of `es_mute_path`.
pub extern "c" fn es_mute_path_literal(client: *es_client_t, path_literal: [*:0]const u8) es_return_t;
pub extern "c" fn es_unmute_all_paths(client: *es_client_t) es_return_t;
/// macOS 13.0+
pub const es_unmute_all_target_paths = @extern(?*const fn (client: *es_client_t) callconv(.c) es_return_t, .{ .name = "es_unmute_all_target_paths", .linkage = .weak });
/// macOS 12.0+
pub const es_unmute_path = @extern(?*const fn (client: *es_client_t, path: [*:0]const u8, type: es_mute_path_type_t) callconv(.c) es_return_t, .{ .name = "es_unmute_path", .linkage = .weak });
/// macOS 12.0+
pub const es_unmute_path_events = @extern(?*const fn (client: *es_client_t, path: [*:0]const u8, type: es_mute_path_type_t, events: [*]const es_event_type_t, event_count: usize) callconv(.c) es_return_t, .{ .name = "es_unmute_path_events", .linkage = .weak });
/// macOS 12.0+
pub const es_muted_paths_events = @extern(?*const fn (client: *es_client_t, muted_paths: *?*es_muted_paths_t) callconv(.c) es_return_t, .{ .name = "es_muted_paths_events", .linkage = .weak });
/// macOS 12.0+
pub const es_release_muted_paths = @extern(?*const fn (muted_paths: *es_muted_paths_t) callconv(.c) void, .{ .name = "es_release_muted_paths", .linkage = .weak });
/// macOS 13.0+
pub const es_invert_muting = @extern(?*const fn (client: *es_client_t, mute_type: es_mute_inversion_type_t) callconv(.c) es_return_t, .{ .name = "es_invert_muting", .linkage = .weak });
/// macOS 13.0+
pub const es_muting_inverted = @extern(?*const fn (client: *es_client_t, mute_type: es_mute_inversion_type_t) callconv(.c) es_mute_inverted_return_t, .{ .name = "es_muting_inverted", .linkage = .weak });
pub extern "c" fn es_clear_cache(client: *es_client_t) es_clear_cache_result_t;
/// macOS 27.0+. `block` is `void (^)(void)`, invoked once every message queued before the call has been delivered.
pub const es_sync_client = @extern(?*const fn (client: *es_client_t, block: darwin.block.Ref) callconv(.c) es_return_t, .{ .name = "es_sync_client", .linkage = .weak });
pub extern "c" fn es_new_client(client: *?*es_client_t, handler: es_handler_block_t) es_new_client_result_t;
/// macOS 27.0+. Like `es_new_client` but only delivers events from descendants of the calling process.
pub const es_new_descendants_client = @extern(?*const fn (client: *?*es_client_t, handler: es_handler_block_t) callconv(.c) es_new_client_result_t, .{ .name = "es_new_descendants_client", .linkage = .weak });
/// macOS 27.0+
pub const es_set_deadline_miss_mode = @extern(?*const fn (client: *es_client_t, mode: es_deadline_miss_mode_t) callconv(.c) es_return_t, .{ .name = "es_set_deadline_miss_mode", .linkage = .weak });
/// macOS 27.0+
pub const es_get_deadline_miss_mode = @extern(?*const fn (client: *es_client_t, mode: *es_deadline_miss_mode_t) callconv(.c) es_return_t, .{ .name = "es_get_deadline_miss_mode", .linkage = .weak });
/// macOS 27.0+
pub const es_set_deadline_max_milliseconds = @extern(?*const fn (client: *es_client_t, events: [*]const es_event_type_t, event_count: u32, milliseconds: u32) callconv(.c) es_return_t, .{ .name = "es_set_deadline_max_milliseconds", .linkage = .weak });
/// macOS 27.0+
pub const es_get_deadline_max_milliseconds = @extern(?*const fn (client: *es_client_t, event: es_event_type_t, milliseconds: *u32) callconv(.c) es_return_t, .{ .name = "es_get_deadline_max_milliseconds", .linkage = .weak });
/// macOS 27.0+
pub const es_set_deadline_min_milliseconds = @extern(?*const fn (client: *es_client_t, events: [*]const es_event_type_t, event_count: u32, milliseconds: u32) callconv(.c) es_return_t, .{ .name = "es_set_deadline_min_milliseconds", .linkage = .weak });
/// macOS 27.0+
pub const es_get_deadline_min_milliseconds = @extern(?*const fn (client: *es_client_t, event: es_event_type_t, milliseconds: *u32) callconv(.c) es_return_t, .{ .name = "es_get_deadline_min_milliseconds", .linkage = .weak });
pub extern "c" fn es_delete_client(client: ?*es_client_t) es_return_t;
